### ISSUE TITLE
[EN DatetimeV2] "everyday", "thanksgiving", "daily", "now" are tagged as datetimeV2

### ISSUE THREAD

**Issue by AngelaYing** [Microsoft/Recognizers-Text#1026]
"everyday", "thanksgiving", "daily", "now" are tagged as DatetimeV2.
For example, query = "create a thanksgiving note", "thanksgiving" will be tagged as DatetimeV2 in this condition.

**Comment by tellarin** [comment]
Hi @AngelaYing,
by design this is considered correct behaviour. Any mention of a holiday will be tagged as date.
Same for "everyday" and "daily" as they are recurring times.
"Now" is tagged is some situations and not in others.
