### ISSUE TITLE
[* Number] Ordinal recognizer could not tag "last" 

### ISSUE THREAD

**Issue by AngelaYing** [Microsoft/Recognizers-Text#1027]
For Query = "delete last sentence in the note", the word "last" will not be annotated as ordinal, while it works for queries "delete [first|second|...] sentence in the note". 

Could ordinal support "next" or "last"?

**Comment by tellarin** [comment]
Support for "Last" is planned in Ordinal. However "next" doesn't seem like it fits well in the Ordinal behaviour.

**Comment by tellarin** [comment]
When you open new issues, please keep the issue template as it makes it easier to analyze/classify issues. Thanks!
