### ISSUE TITLE
[CN DateTimeV2] 一个钟头 cannot be recognized

### ISSUE THREAD

**Issue by Theodosia1005** [Microsoft/Recognizers-Text#1067]
**Describe the bug**
DateTimeRecognizer.RecognizeDateTime("一个钟头", Culture.Chinese) got 0 result

**To Reproduce**
1. var result = DateTimeRecognizer.RecognizeDateTime("一个钟头", Culture.Chinese);
2. result.Count == 0

**Expected behavior**
should get a duration of an hour

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.
一个钟头
半个钟头

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package
 - Version of package v1.1.4

**Additional context**

**Comment by guom08** [comment]
This one has been fixed.
