### ISSUE TITLE
Support for PT-PT or PT-BR for date-time

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/Recognizers-Text#11]
I'm interested in date/time for Portuguese. How hard would it be to adapt existing code for Portuguese strings? Is there any steps one could follow? 

Thanks in advance.

**Comment by chrimc62** [comment]
I think Börje was already looking at this?

**Comment by tellarin** [comment]
Hi @AndreMantas,

Numbers and DateTime support in PT-BR (and partial PT-PT) are coming. There should be a PR by the end of the week.

Any help expanding them would be greatly appreciated.

Thanks.

**Comment by AndreMantas** [comment]
Any updates on this? Would gladly help, just don't know how.

**Comment by tellarin** [comment]
Hi Andre, this was delayed due to some refactoring and bug fixes.
If you could translate the datetime unit tests from English or Spanish to Portuguese, and add Portuguese-specific test cases, that would be very helpful.
We'll publish a spec soon to help people with how and where they can contribute. Any suggestions are very welcome.

**Comment by AndreMantas** [comment]
Hi tellarin. Didn't see the notification before so sorry for delay.

So, you mean the unit tests in this folder right? https://github.com/Microsoft/Recognizers-Text/tree/master/Microsoft.Recognizers.Text.DateTime.Tests/English

Any particular classes that are more important than others?

**Comment by tellarin** [comment]
@AndreMantas, this was on hold for a while as many structural changes to the project were ongoing. 
Now it's much easier to add new languages and to reuse resources and tests across C# and Javascript. 
The PT timex is ongoing now and should be done soon.
