### ISSUE TITLE
[EN DateTimeV2] Does not recognize "less than 24 hours"

### ISSUE THREAD

**Issue by Dillagent** [Microsoft/Recognizers-Text#117]
If I ask a question like  "____________ in the LAST 24 hours"  datetime entity works correctly.  However, asking "______ for less than 24 hours."

**Comment by tellarin** [comment]
@Dillagent, we've added this case to the list to be supported in the near future. 
Thanks for the feedback.

**Comment by tellarin** [comment]
This and similar durations should be supported as durations with modifier.
