### ISSUE TITLE
[French Number] Incomplete regex

### ISSUE THREAD

**Issue by ejadib** [Microsoft/Recognizers-Text#14]
It seems [this regex](https://github.com/Microsoft/Recognizers-Text/blob/master/Microsoft.Recognizers.Text.Number/French/Parsers/FrenchNumberParserConfiguration.cs#L36) is incomplete

@matthewshim-ms

**Comment by tellarin** [comment]
@matthewshim-ms, could you take a look at this?

Thanks.

**Comment by matthewshim-ms** [comment]
@tellarin  resolved in PR #27
