### ISSUE TITLE
[DotNet] Move RegexExtensions to RegExpUtility

### ISSUE THREAD

**Issue by GasparAcevedoZainSouthworks** [microsoft/Recognizers-Text#1427]
**Is your feature request related to a problem? Please describe.**
It's a bit confusing how regexes work in different languages solutions.

**Describe the solution you'd like**
We need a unique entity that contains all the regexes functionality and that it's easily identified in all the languages implementations. As of today, we have either just RegexExtensions(.net) or RegexExtensions plus RegExpUtility(Java, JavaScript, and Python).

**Describe alternatives you've considered**
We should create (or rename one of the existing ones) a new entity that has all the regexes functionality currently being used in the project. This should have the exact same public methods than their pairs in every language. Then we should analyze all the solutions and refactor them to start using this new entity.

**Comment by tellarin** [comment]
@GasparAcevedoZainSouthworks @Aliandi Could you folks retake this once the Python work is done?

**Comment by Aliandi** [comment]
@tellarin sure, we'll add it to our backlog and take it when we finish Python
