### ISSUE TITLE
[StyleCop] Enable StyleCop in DataDrivenTests once ported to NetCore 

### ISSUE THREAD

**Issue by denscollo** [microsoft/Recognizers-Text#1447]
**Issue**
To enforce StyleCop compliance, the build process was configured to fail when an SA warning is found in #1425.
However, to avoid #1425 being blocked by #1050 while the DataDrivenTests project was being modified and since there was a merge conflict, we decided to temporarily exclude this project from breaking build due to SA warnings by removing the StyleCop NuGet package.

**Action to take**
Once the DataDrivenTests Project is done with the porting (#1050), the package should be added again so that this project is also part of the StyleCop analysis

**Comment by tellarin** [comment]
@denscollo @Aliandi Now that the test projects have been converted to .NET Core, can we re-enable this?

**Comment by Aliandi** [comment]
@tellarin sure, we'll add it to our backlog and take it ASAP

**Comment by Aliandi** [comment]
@tellarin We've reviewed this and it looks like #1050 already took care of enabling StyleCop. If you agree, this issue could be closed.

**Comment by tellarin** [comment]
You're correct. Sorry I didn't see that earlier.
