### ISSUE TITLE
[FR-CA DateTimeV2] Docs say French Canadian DateTimeV2 is supported, but is not in LUIS.

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/Recognizers-Text#1470]
**Describe the bug**
[The docs](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#french-canadian-entity-support) say that DateTimeV2 is supported in French Canadian, but it is not listed as a prebuilt entity in LUIS.

**To Reproduce**
1. View the docs and see that French Canadian DateTimeV2 is supported
2. Try to add DateTimeV2 as a prebuilt entity in a FR-CAN LUIS app

**Expected behavior**
Either docs to show it is not supported, or for it to be available in LUIS.

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.

**Docs**

![image](https://user-images.githubusercontent.com/40401643/53354043-da6b4580-38da-11e9-9254-4b70b4bc2324.png)

**LUIS**
![image](https://user-images.githubusercontent.com/40401643/53354088-f0790600-38da-11e9-8edd-e71145c5e90b.png)
![image](https://user-images.githubusercontent.com/40401643/53354116-fbcc3180-38da-11e9-9bdf-b325dcbafd1f.png)

**Comment by tellarin** [comment]
@mdrichardson While LUIS uses Recognizers-Text, this project has no control over how items are exposed in its UI.
I'll forward your comment to the team at MS, but you can also raise LUIS-specific feedback at https://cognitive.uservoice.com/forums/551524-language-understanding-luis

Thanks.
