### ISSUE TITLE
[ES Ordinal] Detection of 1st/3rd ordinals in Spanish

### ISSUE THREAD

**Issue by paulovn** [Microsoft/Recognizers-Text#1471]
In Spanish, the 1st (`primero`) and 3rd (`tercero`) masculine ordinals lose their final vowel when they act as ordinal determinants (before a noun), e.g. `el primer lugar` (_the first place_). The current regex misses those occurrences.

The fix is simple: in https://github.com/Microsoft/Recognizers-Text/blob/master/Patterns/Spanish/Spanish-Numbers.yaml#L64

change
```
def: (primer[oa]|segund[oa]|tercer[oa]|cuart[oa]|quint[oa]|sext[oa]|s[eé]ptim[oa]|octav[oa]|noven[oa])
```

for 
```
def: (primer[oa]?|segund[oa]|tercer[oa]?|cuart[oa]|quint[oa]|sext[oa]|s[eé]ptim[oa]|octav[oa]|noven[oa])
```
i.e., just add two question marks

**Comment by paulovn** [comment]
On a similar topic, the 18th ordinal is not correctly parsed when in its single-word form (`decimoctavo`):
 * `décimo octavo` is correctly parsed as `18`
 * `decimoctavo` however is parsed as `10ctavo`

The patch is again easy: in https://github.com/Microsoft/Recognizers-Text/blob/master/Patterns/Spanish/Spanish-Numbers.yaml#L72 we just need an order change in the regex. From
```
 def: ((({TensOrdinalRegex}(\s)?)?{OneToNineOrdinalRegex})|{TensOrdinalRegex}|{SpecialUnderHundredOrdinalRegex})
```
to

```
 def: ({SpecialUnderHundredOrdinalRegex}|(({TensOrdinalRegex}(\s)?)?{OneToNineOrdinalRegex})|{TensOrdinalRegex})
```
... so that `decimoctavo` is matched first, before `decimoXXXX` has a chance to step in.

**Comment by tellarin** [comment]
@paulovn Sorry. These had fallen through the cracks. Merged now.
Thanks for the feedback and corrections!
