### ISSUE TITLE
[Javascript] Output readable error message in build tests for duplicate specs

### ISSUE THREAD

**Issue by guom08** [microsoft/Recognizers-Text#1478]
**Is your feature request related to a problem? Please describe.**
Javascript test load code would not raise proper error message in some cases.
For example, when the test cases have duplication, the online build would prompt uncaught exception without any useful hint.

**Describe the solution you'd like**
Prompt the correct message to help locate the problem

**Comment by tellarin** [comment]
Currently the test code generates an exception and crashes out.

**Comment by tellarin** [comment]
No longer needed as we have a validation script that checks for duplicate specs and breaks the build.
