### ISSUE TITLE
[EN DateTimeV2] Incorrect time span in query {book my time for swimming every Tuesday and Thursday 19:00 - 21:00} - regression

### ISSUE THREAD

**Issue by jiayinge** [Microsoft/Recognizers-Text#1482]
**Describe the bug**
“thursday 19:00 - 21” other than “thursday 19:00 – 21:00” is recognized as a resolution from query "book my time for swimming every Tuesday and Thursday 19:00 - 21:00".

Nuget package v1.1.5

**Comment by tellarin** [comment]
Regression fixed in #1484.
