### ISSUE TITLE
[FA *] Persian language

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/Recognizers-Text#1485]
How can I help for persian language?

**Comment by tellarin** [comment]
@khoshroomahdi Thanks for the interest to help out!
The suggested flow to start a new language is to read the links at the end of the project README and start by translating the specs for Numbers firstly.

**Comment by khoshroomahdi** [comment]
i create folder and copy number from English to that folder.when i replace text as i Persian is an RTL the sort  changed. does it make problem or not?

**Comment by tellarin** [comment]
I'm not sure I get what you mean by 'sort changed'. 
If you mean the content of each json spec file, the order of specs cases in the file is not an issue. 
Later, the code that reads the file will need to take into account that the input sentence is RTL.
You can make a draft PR with partial work so we can take a look too.
Thanks!

**Comment by tellarin** [comment]
Closing this issue as it's not currently in the pipeline.
Feel free to discuss here if anyone is interested in contributing support.
