### ISSUE TITLE
[SV *] Swedish Lang

### ISSUE THREAD

**Issue by pete1854** [microsoft/Recognizers-Text#1493]
Hi,
Is there any development for the Swedish language (sv-SE)?

How can I contribute? 

We’re currently customizing the Virtual Assistant for our business, and we lack support for sv-SE in the recognizer, Luis and QnA services. If possible, we’d like to contribute in localizing these services to swedish.

Kind regards,
Peter

**Comment by tellarin** [comment]
@pete1854 any help is greatly appreciated! We suggest following a flow similar to #1485 to start.

**Comment by tellarin** [comment]
BTW, we'll try to publish a summarized guideline on how to contrib a new language.

**Comment by pete1854** [comment]
Thanks @tellarin. We’ll get started.

**Comment by pete1854** [comment]
@tellarin what’s the reason for subtype being available only for en-us? I’m writing tests for the numbermodel and found a comment about this in one of the base classes when going through the code. /P

**Comment by tellarin** [comment]
@pete1854 the current work model is that new features are introduced in English first, then propagated to other languages as mature. The comment is there to make sure people don't expect that to exist in all cultures yet.
In this case, as the effort to support a new language starts, it would be natural for the new language to already support the new features from English too.
However, some features are marked as _experimental_ or _preview_ (code calls behind ```Options``` flags). Feel free to not support those for now, or to have a separate discussion on them for details.

**Comment by pete1854** [comment]
@tellarin maybe this is the wrong place to ask this question (in that case I apologize), but:

In BaseNumberParser.cs the following call doesnt't return the expected result:
`var stringMatch = TextNumberRegex.Match(intPart);`
where `intPart` is "**trehundra**". 

The pattern for the matcher is:

`(och| -|dussintals|biljarder|miljarder|dussintal|miljoner|biljard|miljard|trettio|fjorton|sjutton|sjuttio|tjogvis|tretton|sextio|sexton|hundra|femtio|femton|fyrtio|tretti|miljon|dussin|nittio|nitton|åttio|tjugo|ingen|arton|tusen|inga|tolv|elva|tjog|fyra|noll|åtta|nio|tio|ett|två|sex|sju|fem|tre|en|sjuttiondelar|trettiondelar|femtiondelar|trettondelar|sjuttondelar|sextiondelar|biljarddelar|miljarddelar|nittiondelar|fyrtiondelar|fjortondelar|tjugondelar|nittondelar|åttiondelar|femtondelar|sjättedelar|tolftedelar|miljondelar|tredjedelar|sjundedelar|fjärdedelar|sextondelar|hundradelar|sjuttionde|åttondelar|elftedelar|artondelar|trettionde|femtedelar|tusendelar|sjuttonde|niondelar|tiondelar|fjortonde|femtionde|trettonde|nittionde|sextionde|biljardte|miljardte|fyrtionde|sextonde|åttionde|hundrade|nittonde|femtonde|miljonte|tjugonde|åttonde|artonde|kvartar|tusende|tolfte|sjätte|nionde|tionde|fjärde|halvor|tredje|sjunde|första|förste|andre|andra|kvart|elfte|femte|ettan|halva|tvåan|tvåa|etta)`

The matcher returns zero matches. Pasting the pattern into any Regex-editor results in **two** matches: "**tre**" and "**hundra**".

What am I missing here?

**Comment by tellarin** [comment]
@pete1854 Currently, there is a small difference between languages that always separate numbers with spaces (like "three hundred" in English, and "dreihundert" in German. In the constructor of ```BaseNumberParser``` line 26, you need to add a check for Swedish so that word boundaries are not auto-added to the regex. The regex without boundaries is also used in other compound regexes.
My suggestion for this type of questions is that you create a "draft PR". It makes it easier to see what's going on in the code.
Also, if you already have the translated specs for Numbers, please make a PR with them first, so we can review/merge quickly.
Thanks!

**Comment by pete1854** [comment]
Thanks @tellarin I’ll propose a PR shortly for Choices and Numbers.

**Comment by tellarin** [comment]
Can you make it two separate PRs to ease review?

**Comment by tellarin** [comment]
BTW, I've made some minor readability changes to that piece of the code (#1510). Please add "sv-SE" to the new culture list in line 18.

**Comment by pete1854** [comment]
Hi @tellarin. I’m having some issues when it comes to resolving fractional values, e.g. ”Två och tre tjugofemtedelar” (”two and three twenty-fifths”). In swedish, the denominator is written without a dash, i.e. ”two and three twentyfifths”. This results in the tokenizer failing to identify tokens ”twenty” and ”fifths”. What are my options here? I could add the composite value (”tjugofemtedelar”) to the ordinal map, but there must be a smarter way of solving this. Any suggestions?

**Comment by pete1854** [comment]
PR #1548 is in preparation for the upcoming PR for SV Numbers

**Comment by tellarin** [comment]
Closing this issue as it's not currently in the pipeline.
Feel free to discuss here if anyone is interested in continuing extending support.
