### ISSUE TITLE
[French Number] Unit tests failing

### ISSUE THREAD

**Issue by ejadib** [Microsoft/Recognizers-Text#15]
It seems that some of the regexes are malformed. To look into this please fix first #13 and #14 

@matthewshim-ms

**Comment by tellarin** [comment]
@matthewshim-ms, this was also fixed in the last PR, right?

**Comment by matthewshim-ms** [comment]
@tellarin correct, all unit tests pass right now for common use cases, and commented out niche cases per suggestion

**Comment by tellarin** [comment]
@matthewshim-ms Cool. Closing this now then. :)
