### ISSUE TITLE
Error parsing double values

### ISSUE THREAD

**Issue by pete1854** [Microsoft/Recognizers-Text#1517]
**Describe the bug**
When trying to parse the Swedish value "tre komma fjorton" (3,14) an exception is thrown in BaseNumberParser.cs, line 858.

**To Reproduce**
1. Add a Spec denoting a decimal number in text, e.g.: 
`{
    "Input": "Svaret blir tre komma fjorton",
    "NotSupported":"javascript",
    "NotSupportedByDesign": "python,java",
    "Results": [
      {
        "Text": "tre komma fjorton",
        "TypeName": "number",
        "Resolution": {
          "subtype": "decimal",
          "value": "3,14"
        },
        "Start": 12,
        "End": 28
      }
    ]
  }`
2. Run the `NumberModel` test.
3. The following is code is executed in the parser:
```
Line 854: var prefix = "0.";
855: var tempInt = GetIntValue(matchStrs);
856: var all = prefix + tempInt;
857:
858: ret = double.Parse(all); //"0.14"
```

4. Line 858 throws a FormatException because Swedish decimal numbers use a comma instead of a dot.

**Expected behavior**
double.Parse should return 0.14 and the input string should be "0,14".

**Platform (please complete the following information):**
 - Platform: .NET (not tested on other platforms)
 - Environment: VS during testing
 
**Additional context**
n/a

**Comment by iMicknl** [comment]
Have a look at `Extractors/DoubleExtractor.cs`, this is the place where is defined if you use the dot or comma notatation. Have a look at the [Dutch DoubleExtractor](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.Number/Dutch/Extractors/DoubleExtractor.cs) for example and compare it with the current Swedish version.

```
                {
                    GenerateLongFormatNumberRegexes(LongFormatType.DoubleNumDotComma, placeholder),
                    RegexTagGenerator.GenerateRegexTag(Constants.DOUBLE_PREFIX, Constants.NUMBER_SUFFIX)
                },
                {
                    GenerateLongFormatNumberRegexes(LongFormatType.DoubleNumNoBreakSpaceComma, placeholder),
                    RegexTagGenerator.GenerateRegexTag(Constants.DOUBLE_PREFIX, Constants.NUMBER_SUFFIX)
                },
                {
                    GenerateLongFormatNumberRegexes(LongFormatType.DoubleNumBlankComma, placeholder),
                    RegexTagGenerator.GenerateRegexTag(Constants.DOUBLE_PREFIX, Constants.NUMBER_SUFFIX)
                },
```

Be advised that the output will use the dot separator eventually for consistency, see https://github.com/Microsoft/Recognizers-Text/issues/774 which tracks this.

**Comment by pete1854** [comment]
Thanks @iMicknl - but how does that affect the double.Parse operation on line 858 in my code excerpt above? I mean, the "prefix" variable is hard coded to have a dot notation ("0."). Maybe I'm doing something wrong here and I shouldn't end up here when running the NumberModel test w/ the above Spec? I'm quite new to the code and doesn't fully know my way around the yet.
Kind regards,
Peter

**Comment by pete1854** [comment]
Just out of curiosity I changed line 854 to
`var prefix = $"0{Config.DecimalSeparatorChar}";`
and then it all works as expected. Does the code assume it should be run in a `en-US` locale (since the the code is implemented using the hard-coded dot separator)?

**Comment by iMicknl** [comment]
Sorry, I misunderstood your initial issue. You are correct, have a look at https://github.com/Microsoft/Recognizers-Text/issues/885. However my previous reply is still a change you should made for Swedish.

**Comment by pete1854** [comment]
Hi again,
No problem :) I'm just happy that I was not alone having this issue. I checked my Parser settings and they are configured as per Swedish standards.

**Comment by tellarin** [comment]
To be handled together with #774. This has been long in the pipe, but haven't been out yet.
Sorry for the inconvenience. A current workaround is to set the environment to English US and things should work.
Please comment on #774 if you notice other side-effects.
