### ISSUE TITLE
[FR DateTimeV2] French datetime matches numbers

### ISSUE THREAD

**Issue by omaremadeldin** [microsoft/Recognizers-Text#1523]
For some reason DateTime Model in French matches numbers from 0 to 24
Example: "Je veux le numéro 3", `3` is matched as datetime when it should not.

**Comment by Zeraphil** [comment]
Is this issue fix deployed? The latest version from Nuget, 1.3.2, still has this behavior. "Je veux le numéro 17" is matched as datetime.

**Comment by tellarin** [comment]
@Zeraphil, sorry for the delay to reply. I can't reproduce on /master. I'll try 1.3.2 later to double check. But the next package is in the release train now anyways.
