### ISSUE TITLE
[CN DateTimeV2] '2018年12月' wrong extraction

### ISSUE THREAD

**Issue by zbjdonald** [Microsoft/Recognizers-Text#1525]
**Describe the bug**
When it parses '2018年10月'，there is two results with '2018' and '10月', rather than '2018年10月'. It works in '2018年大年' / '2018年十月' case.

**To Reproduce**
Parse '2018年10月'

**Expected behavior**
Same result as '2018年十月'

**Sample input/output**

**Platform (please complete the following information):**
 - Platform: [Python]
 - Environment: 
 - Version of package [latest]

**Additional context**

**Comment by tellarin** [comment]
@Grey0202, could you take a look at this?
