### ISSUE TITLE
[DE Ordinal] add "letzter", "vorletzter" and similar ordinals from the back

### ISSUE THREAD

**Issue by Ablesius** [microsoft/Recognizers-Text#1555]
**Is your feature request related to a problem? Please describe.**
I would like to be able to access ordinals as counted from the back of a list, words like "letzter" ("last") and "vorletzter" ("second to last").

**Describe the solution you'd like**
Please provide me with the necessary information to implement the feature myself; so far I haven't found anything that seems related to that. I've been pointed to https://github.com/Microsoft/Recognizers-Text/blob/master/Patterns/German/German-Numbers.yaml, but I'm not sure what to add there:
* is there a list of allowed keys like "ZeroToNineIntegerRegex" and the other ones? 
* Or are the names completely arbitrary? 
* Where would I have to add them beside the German-Numbers.yaml above?

Any help is going to be appreciated :) cheers
Alex

**Comment by tellarin** [comment]
@Ablesius To implement this you can follow the framework from English that already has this support.
Basically, changes from English (new regexes in YAML or extractor/parser config tweaks) need to be ported/tested in German.
I'll try to track the relevant commits and mention them in this issue.

**Comment by Ablesius** [comment]
@tellarin I've opened a pull request, but the tests fail. If you have the time, maybe you could help me out there: https://github.com/microsoft/Recognizers-Text/pull/1557 :) cheers

**Comment by tellarin** [comment]
@Ablesius, sorry for the delay. I've reviewed the PR and left comments there. Basically the tests need to be marked as "NotSupported" for now. Until the feature is fully implemented in German.

**Comment by Ablesius** [comment]
@tellarin thanks for the pointers and the support :)
