### ISSUE TITLE
[TimexExpression] Number of Issues With TimexExpression lib

### ISSUE THREAD

**Issue by kevinthomasbradley** [microsoft/Recognizers-Text#1560]
Date / Timex Expression | Expected Result | DateTimeRecognizer | TimexHelpers (Relevant) | TimexResolver | Overall Assessment
-- | -- | -- | -- | -- | --
2019 | Date Range | Recognizes Correct Range | Recognizes Correct Range | Doesn’t Recognize | 2/3 Match
2019-04 | Date Range | Recognizes Correct Range | Recognizes Correct Range | Recognizes Correct Range | 3/3 Match
2019-04-25 | Date | Recognizes Correct Date | Recognizes Correct Date | Recognizes Correct Date | 3/3 Match
XXXX-06 | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Recognizes Correct Range | 1/3 Match
XXXX-XX-06 | Date | Doesn’t Recognize | Wrong Date 1/1/01 | Doesn’t Recognize | 0/3 Match - FAIL
XXXX-12-25 | Date | Doesn’t Recognize | Partial Date 12/25/01 | Recognizes Correct Date | 1.5/3 Match
2019-W18 | Date Range | Wrong Range 1/1/19 – 1/1/20 | Wrong Range 1/1/19 – 1/1/20 | Doesn’t Recognize | 0/3 Match - FAIL
2019-04-W01 | Date Range | Wrong Range 4/1/19 – 5/1/19 | Wrong Range 1/1/01 – 1/1/01 | Doesn’t Recognize | 0/3 Match - FAIL
XXXX-04-W01 | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Wrong Range 4/1/19 – 5/1/19 | 0/3 – FAIL ("XXXX-04-WXX-1")
XXXX-WXX-1 | Date | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Recognizes Past + Next Monday | 1/3 Match
2019-06-01T15 | Date Time | Recognized Date Only | Recognized Data Time Separ. | Recognizes Correct Date Time | 1.5/3 Match
XXXX-06-01T15 | Date Time | Doesn’t Recognize | Recognized Data Time Separ. + /01 year | Recognizes Correct Date Time | 1.5/3 Match
XXXX-WXX-1T15 | Date Time Range | Doesn’t Recognize | Doesn’t Recognize | Recognizes Correct Date Time | 1/3 Match
XXXX-WXX-1TMO | Date Time Range | Doesn’t Recognize | Doesn’t Recognize | Identifies Morning but no Date / Value | 0/3 Match - FAIL
T15 | Time | Doesn’t Recognize | Doesn’t Recognize | Recognizes | 1/3 Match
P2W | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Duration Value 1209600 | 0/3 Match – FAIL* Expand Identifies ‘2 Weeks’
P2M | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Duration Value 5184000 | 0/3 Match – FAIL* Expand Identifies ‘2 Months’
P2D | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Duration Value 172800 | 0/3 Match – FAIL* Expand Identifies ‘2 Days’
P2Y | Date Range | Doesn’t Recognize | Wrong Range 1/1/01 – 1/1/01 | Duration Value 63072000 | 0/3 Match – FAIL* Expand Identifies ‘2 Years
PT20M | Time Range | Doesn’t Recognize | Exception | Duration Value 1200 | 0/3 Match – FAIL* TimeRangeFromTimex & ExpandTimeRange throws exception
PT6H | Time Range | Doesn’t Recognize | Exception | Duration Value 21600 | 0/3 Match – FAIL* TimeRangeFromTimex & ExpandTimeRange throws exception
PT10S | Time Range | Doesn’t Recognize | Exception | Duration Value 10 | 0/3 Match – FAIL* TimeRangeFromTimex & ExpandTimeRange throws exception
2019-04-27,2019-05-11,P2W | Date Range | Recognizes Correct Date Separ. | Wrong Range 1/1/01 – 1/1/01 | Doesn’t Recognize | 1/3 Match
2019-04-12,2019-04-26,P2W | Date Range | Recognizes Correct Date Separ. | Wrong Range 1/1/01 – 1/1/01 | Doesn’t Recognize | 1/3 Match
2019-02-26,2019-04-26,P2M | Date Range | Recognizes Correct Date Separ. | Wrong Range 1/1/01 – 1/1/01 | Doesn’t Recognize | 1/3 Match
1992-01-01,1995-01-01,P3Y | Date Range | Recognizes Correct Date Separ. | Wrong Range 1/1/01 – 1/1/01 | Doesn’t Recognize | 1/3 Match

**Comment by tellarin** [comment]
Thanks, @kevinthomasbradley for the detailed feedback. We'll analyze and prioritize accordingly.

**Comment by johnataylor** [comment]
Yes indeed @kevinthomasbradley a very detailed bug. Thanks.

**Comment by ayanez17** [comment]
@tellarin @johnataylor Any update on this?

**Comment by markbeau** [comment]
Is there an update?

**Comment by tellarin** [comment]
@ayanez17 @markbeau @kevinthomasbradley we've collected some more feedback and an update is coming soon.
Sorry for the long delay.
