### ISSUE TITLE
[EN DateTimev2 | JavaScript] JS doesn't support EnglishOthers "en-*" as a culture

### ISSUE THREAD

**Issue by amirbouker** [microsoft/Recognizers-Text#1569]
**Describe the bug**
Recognizers-Text node js project doesn't support EnglishOthers "en-*" as a culture 
but in the Dot-net project it is supported 
therefor when I try to retrieve a datetime format different from MM/DD it doesn't work while the user is speaking English but he is not from US

**To Reproduce**
user from UK : book room from 10/06/2019 to 12/06/2019 (period 2 days from 10th June to 12th June )
const result= Recognizers.recognizeDateTime(
    args.text,
    Recognizers.Culture.EnglishOthers
  );
result[0].resolution.values[0] = 
{
    end: "2019-12-06",
    start: "2019-10-06",
    timex: "(2019-10-06,2019-12-06,P61D)",
    type: "daterange"
}
**Expected behavior**
Recognizers-Text node js should be able to accept EnglishOthers 
result[0].resolution.values[0] = 
{
    end: "2019-12-06",
    start: "2019-10-06",
    timex: "(2019-10-06,2019-12-06,P2D)",
    type: "daterange"
}
the period in the timex should be P2D

**Platform (please complete the following information):**
 - Platform: JavaScript
 - Environment: npm package :@microsoft/recognizers-text-suite @microsoft/recognizers-text-suite

**Additional context**
Dot-net list of cultures : 
    - https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text/Culture.cs
Node js list of cultures : 
    - https://github.com/microsoft/Recognizers-Text/blob/master/JavaScript/packages/recognizers-text/src/culture.ts

**Comment by tellarin** [comment]
@Grey0202 is working on this.

**Comment by tellarin** [comment]
New packages will be released soon.
