### ISSUE TITLE
[EN DateTimeV2] No resolved value for "summer 2018"

### ISSUE THREAD

**Issue by ZijiaLin** [microsoft/Recognizers-Text#1583]
[
  {
    "Text": "summer 2018",
    "Start": 0,
    "End": 10,
    "TypeName": "datetimeV2.daterange",
    "Resolution": {
      "values": [
        {
          "timex": "2018-SU",
          "type": "daterange",
          "value": "not resolved"
        }
      ]
    }
  }
]

**Comment by tellarin** [comment]
@substill @ZijiaLin Unfortunately seasons of the year depend on the user location so the recognizers cannot provide a resolution. I.e. "summer" in the USA is different than "summer" in Australia.
For such cases, consumers need to use the season terms in the timex to fully resolve to the right range.

**Comment by tellarin** [comment]
Closing this as it will be addressed by an extension to the timexexpression lib.
