### ISSUE TITLE
[EN DateTimeV2] "this quarter", "last quarter" not recognized

### ISSUE THREAD

**Issue by balasab** [microsoft/Recognizers-Text#1606]
1.Sales for this quarter
2..sales for last quarter
I am expecting to recognize this quarter and last quarter for the current year with a range of date.
But unfortunately luis doesn't return any date.
Please make sure this works

**Comment by hiteshtare** [comment]
1.Show my Working Days for last quarter
2.Show my Working Days for yesterday
Luis recognize this quarter and last quarter for the current year with a range of date.
But this library failes to parse the luis response.
version: microsoft/recognizers-text-suite : 1.1.4

**Comment by tellarin** [comment]
@hiteshtare, this issue has been fixed in the current repo. It will be included in the next NPM release to happen soon.

**Comment by hiteshtare** [comment]
@tellarin, Thanks for the info :+1:
