### ISSUE TITLE
[EN DateTimeV2] US holidays improvements

### ISSUE THREAD

**Issue by wlifuture** [microsoft/Recognizers-Text#1616]
St. Patrick's day, Earth day, Presidents day, Cyber Monday, Veterans day. To @wlifuture

**Comment by wlifuture** [comment]
Resolving by PR #1617 [https://github.com/microsoft/Recognizers-Text/pull/1617](url)

**Comment by wlifuture** [comment]
Patch previous PR #1613 that initially improve two holidays

**Comment by wlifuture** [comment]
And latest "easter" + related special days which are based on lunar calendar

**Comment by tellarin** [comment]
@wlifuture are more coming in the near future? Or can we close this issue for now?

**Comment by wlifuture** [comment]
> @wlifuture are more coming in the near future? Or can we close this issue for now?

Closing the issue for now.
