### ISSUE TITLE
geographyV2 missing Malaysia's states

### ISSUE THREAD

**Issue by huislaw** [microsoft/Recognizers-Text#1641]
I'm using geographyV2 to get Malaysia's states via LUIS. Some states can detect but some cannot. Some same state can detect in utterance using "at" but not in "in" . 
Am I missing something?

Examples as below via the Test Panel:

how's the weather in johor
---------------------------
Text	Entity
"johor"	geographyV2

how's the weather in sabah?
---------------------------
Entities
No predicted entities

how's the weather at sabah?
---------------------------
Entities
Text	Entity
"sabah"	geographyV2

hows the weather at pahang
---------------------------
Entities
No predicted entities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc4ddee5-63b7-865f-d8e3-7ee080ac9fe8
* Version Independent ID: 42a03274-7cba-0fc1-80ad-93f3c44a7d8e
* Content: [Geography V2 prebuilt entity - Azure Cognitive Services](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-geographyv2)
* Content Source: [articles/cognitive-services/LUIS/luis-reference-prebuilt-geographyV2.md](https://github.com/Microsoft/azure-docs/blob/master/articles/cognitive-services/LUIS/luis-reference-prebuilt-geographyV2.md)
* Service: **cognitive-services**
* Sub-service: **language-understanding**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by tellarin** [comment]
@huislaw Unfortunately LUIS Geography is not one of the entities covered by the Recognizers-Text project, so this issue is out of scope here.
@cahann, is there a GitHub place for such feedback?

**Comment by huislaw** [comment]
Hmmm, where should I report this?

**Comment by huislaw** [comment]
No one?
