### ISSUE TITLE
[EN Ordinal] OrdinalModel parse regression

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/Recognizers-Text#1642]
**Describe the bug**
```cs
System.ArgumentException: 'An item with the same key has already been added.
Key: [value, start+1]'
```

**To Reproduce**
1. Upgrade Microsoft.Recognizers.Text to 1.2.1
2. Run this code:
```cs
            var Culture = Recognizers.Text.Culture.English;
            var model = new NumberRecognizer(Culture).GetOrdinalModel(Culture);
            var result = model.Parse("the one before the last");
```
3. See error

**Expected behavior**
No exception

**Platform (please complete the following information):**
 - Platform: .net
 - Environment: nuget package
 - Version of package: 1.2.1

**Additional context**
1.2.0 did not have this exception

**Comment by tellarin** [comment]
Package 1.2.1 has been retracted and a fix is on the way. Thanks for catching this!

**Comment by tellarin** [comment]
This issue was mitigated in PR #1648. The code will be refactored to improve it soon.
