### ISSUE TITLE
[EN Ordinal] SuppressExtendedTypes does not produce expected results

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/Recognizers-Text#1654]
**Describe the bug**
GetOrdinalModel with SuppressExtendedTypes does not have the same resolution as previously.

**To Reproduce**
Using 1.2.2
```cs
var m1 = new NumberRecognizer(Culture, NumberOptions.SuppressExtendedTypes).GetOrdinalModel(Culture);
var result1 = m1.Parse("the second to last");
```
**= []**

**Expected behavior**
using 1.1.3
```cs
var m1 = new NumberRecognizer(Culture).GetOrdinalModel(Culture);
var result1 = m1.Parse("the second to last");
```
**= [{"Text":"second","Start":4,"End":9,"TypeName":"ordinal","Resolution":{"value":"2"}}]**

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget
 - Version of package v1.2.2

**Additional context**
Using NumberOptions.SuppressExtendedTypes with the same utterance should produce the same result as previous versions.

**Comment by tellarin** [comment]
Hi @EricDahlvang,
in my view this behaviour is actually a model fix. "second" should never have been tagged as Ordinal originally. But I can also understand your PoV.
We'll discuss this a little further and get back to you.

**Comment by tellarin** [comment]
@EricDahlvang can we close this specific issue as "acceptable" now as "model refinement"? 
I'd like to double-check before the next triage.

**Comment by EricDahlvang** [comment]
Certainly!  Thanks @tellarin !
