### ISSUE TITLE
Missing German Culture

### ISSUE THREAD

**Issue by Zerryth** [microsoft/Recognizers-Text#1689]
**Describe the bug**
in recognizers_text, looks like German Culture (`de-de`) is missing
* [Culture class](https://github.com/microsoft/Recognizers-Text/blob/master/Python/libraries/recognizers-text/recognizers_text/culture.py)

This is in turn makes the Bot Framework SDK look inconsistent when porting `ChoicePrompt` class into Python:

![image](https://user-images.githubusercontent.com/35248895/60472794-20387180-9c1f-11e9-96d6-732b757f6509.png)

**Expected behavior**
To include German culture, as in C#

**Comment by tellarin** [comment]
Duplicate of #1516.

**Comment by v-kydela** [comment]
@tellarin - Please either reopen this issue or explicitly mention Python in the other issue

**Comment by tellarin** [comment]
@v-kydela, I've added it there in the title.
