### ISSUE TITLE
[FR DateTimeV2] Start date occurs after end date

### ISSUE THREAD

**Issue by AleksCallebat** [microsoft/Recognizers-Text#1691]
While looking in french to interpret "3 juin au 8 aout", I get a 
{ start :'2019-06-03' , end : '2018-08-08}

Is there a possibility to ensure that the end of a daterange comes after the begining?

**Comment by tellarin** [comment]
We can't replicate this issue in the latest .NET nor JavaScript versions. Both output the correct result.
