### ISSUE TITLE
[FR Currency] Issue when parsing french word "sur" in currencies

### ISSUE THREAD

**Issue by jchomarat** [microsoft/Recognizers-Text#1699]
When I send the following sentence to Luis
Je veux un crédit de EUR 1000 sur 3 ans (I want to loan EUR 10000 for 3 years), the entity money recognized is "EUR 1000 sur".
However, if I invert the currency and put it after the amount, it works. But Speech service formats it that way (currency in front of amount)

Thanks

**Comment by tellarin** [comment]
Fixed in #1802.
