### ISSUE TITLE
Manual build instructions for JavaScript don't work

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#171]
The manual build instructions for JavaScript don't appear to work.

At least the paths are wrong, but even after working around that the "npm run build" failed.

**Comment by pcostantini** [comment]
Hi John,
Could you post the NPM output log?

In the instructions there is a missing `npm install` step, right after `npm run prebuild-all`.

We'll be updating the README with this missing instructions and other fixes very soon

**Comment by johnataylor** [comment]
The instructions start out in the wrong folder for starters - this is certainly wrong:

git clone https://github.com/southworkscom/Recognizers-Text.git
cd Recognizers-Text

**Comment by pcostantini** [comment]
The latest README updates should reflect the new instructions

**Comment by tellarin** [comment]
@johnataylor can you confirm if we can close this one?
