### ISSUE TITLE
Unit test failures in JavaScript

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#172]
When I build the JavaScript code (using the build.cmd as the manual steps appear to be broken) I get three unit tests broken:

  5305 passed
  **3 failed**
  209 skipped

  DateTime - Spanish - DateTimePeriodParser - "Estaré afuera de 2:00pm, 2016-2-21 a 3:32, 04/23/2016"
  C:\private\Recognizers-Text\JavaScript\test\runner-datetime.js:100
   100:                 t.is(actual.value.timex, expected.Value.Timex, 'Result.Value.Timex');
  Result.Value.Timex
  Difference:
  - '(2016-02-21T14:00,2016-04-23T03:32,PT1477H)'
  + '(2016-02-21T14:00,2016-04-23T03:32,PT1478H)'
  _.zip.forEach.o (test/runner-datetime.js:100:19)
  Test.t [as fn] (test/runner.js:26:35)
  DateTime - English - DateTimePeriodParser - "I'll be out from 2:00pm, 2016-2-21 to 3:32, 04/23/2016"
  C:\private\Recognizers-Text\JavaScript\test\runner-datetime.js:100
   100:                 t.is(actual.value.timex, expected.Value.Timex, 'Result.Value.Timex');
  Result.Value.Timex
  Difference:
  - '(2016-02-21T14:00,2016-04-23T03:32,PT1477H)'
  + '(2016-02-21T14:00,2016-04-23T03:32,PT1478H)'
  _.zip.forEach.o (test/runner-datetime.js:100:19)
  Test.t [as fn] (test/runner.js:26:35)
  DateTime - English - DateTimePeriodParser - "I'll be out I'll be out from 2:00pm, 2016-2-21 to 3:32, 04/23/2016"
  C:\private\Recognizers-Text\JavaScript\test\runner-datetime.js:100
   100:                 t.is(actual.value.timex, expected.Value.Timex, 'Result.Value.Timex');
  Result.Value.Timex
  Difference:
  - '(2016-02-21T14:00,2016-04-23T03:32,PT1477H)'
  + '(2016-02-21T14:00,2016-04-23T03:32,PT1478H)'

**Comment by johnataylor** [comment]
Sounds good - so lets keep the issue open then for now.

**Comment by tellarin** [comment]
@johnataylor, can you test again on your side? The daylight saving time fix in Javascript is merged.

**Comment by tellarin** [comment]
@johnataylor ping :)
