### ISSUE TITLE
Samples link is broken in Readme.md

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#173]
The following appears to be broken:

https://github.com/Microsoft/Recognizers-Text/blob/master/samples

**Comment by johnataylor** [comment]
and the Specs and Patterns links also appear broken.

**Comment by johnataylor** [comment]
...more broken links under API Documentation

https://github.com/Microsoft/Recognizers-Text/blob/master/recognizers-number/src/number/numberRecognizer.ts

**Comment by johnataylor** [comment]
I still see lots of broken links on the Readme

**Comment by pcostantini** [comment]
Hi @johnataylor ,
The links should be fixed now on the master branch
Thanks

**Comment by tellarin** [comment]
Links were fixed. Thanks for reporting this!
