### ISSUE TITLE
[CN DateTimeV2] Wrong duration of extracted date range in Chinese

### ISSUE THREAD

**Issue by songwenhao1** [microsoft/Recognizers-Text#1731]
**Describe the bug**
计费周期 2019年6月1日-6月30日

**Expected result**
{
  "Text": "2019年6月1日-6月30日",
  "Start": 5,
  "End": 19,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        **"timex": "(2019-06-01,XXXX-06-30,P30D)",**
        "type": "daterange",
        "start": "2019-06-01",
        "end": "2019-06-30"
      },
      {
        "timex": "(2019-06-01,XXXX-06-30,P395D)",
        "type": "daterange",
        "start": "2019-06-01",
        "end": "2020-06-30"
      }
    ]
  }
}

**Actual result**
{
  "Text": "2019年6月1日-6月30日",
  "Start": 5,
  "End": 19,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        **"timex": "(2019-06-01,XXXX-06-30,P395D)",**
        "type": "daterange",
        "start": "2019-06-01",
        "end": "2019-06-30"
      },
      {
        "timex": "(2019-06-01,XXXX-06-30,P395D)",
        "type": "daterange",
        "start": "2019-06-01",
        "end": "2020-06-30"
      }
    ]
  }
}

**Comment by tellarin** [comment]
I guess the first timex should be (2019-06-01,XXXX-06-30,P30D)?

**Comment by songwenhao1** [comment]
@tellarin Yes,  but in our code, the result is 29 (30 - 1).

**Comment by tellarin** [comment]
@songwenhao1, the second timex is correct and it is 395 = 365 (one year) + 30.
Why would the new one for the first resolution be 29 and not 30?
