### ISSUE TITLE
Installation instructions refer to non-existent NPM Packages

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#175]
The section in the Readme for JavaScript refers to installing three different Node Packages - the last two of the three are missing:

https://github.com/Microsoft/Recognizers-Text/tree/master/JavaScript#installation

**Comment by pcostantini** [comment]
The NPM packages are not yet published.

In the meantime, you can build the whole project and then reference it from your module by adding the following line to your package.json:

````JSON
"dependencies": {
    "recognizers-text": "file:[PATH_TO_RECOGNIZERS_TEXT_JAVASCRIPT_FOLDER]"
}
````

**Comment by johnataylor** [comment]
OK sounds good. But I don't think we should have the Readme be so out of sync with the state of the repo and the publication. Basically just don't put the link in the Readme until we've done the work.

Maybe we should consider Lerna. It manages the npm links for you. At which point we don't need to have these file: dependencies around.

**Comment by tellarin** [comment]
Closing this issue as the npm packages are now available in npmjs.com (in @preview though).
