### ISSUE TITLE
[PT DateTimeV2] The datetimeV2 prebuilt entity does not recognize "terça" weekday.

### ISSUE THREAD

**Issue by pferreiraa** [microsoft/Recognizers-Text#1768]
**Describe the bug**
The datetimeV2 prebuilt entity regonizes all portuguese weekdays except for "terça" or "terça-feira" (portuguese for tuesday).

It recognizes: "segunda", "quarta", "quinta", "sexta", "sábado", "domingo".
Does not recognize: "terça".

Could it be somehow related with the "ç" character?

**Platform:**
 - Environment: LUIS

**Comment by tellarin** [comment]
Thanks for reporting this. There was a typo in pattern code. A fix is one its way.
