### ISSUE TITLE
[.NET] Fail to build on Ubuntu Linux

### ISSUE THREAD

**Issue by combacsa** [microsoft/Recognizers-Text#1778]
**Describe the bug**
I've set `alias nuget='mono /usr/local/bin/nuget.exe'` and `command -v nuget` does not fail on my bash shell. But when I run `build.sh`, it fails with `NuGet not found. Make sure it's installed and included in PATH. Aborting.` message.

**To Reproduce**
1. Go to '.NET'
2. Type './build.sh'
3. ....
4. See error like this.

```
$ ./build.sh 
// Building .NET platform
NuGet not found. Make sure it's installed and included in PATH. Aborting.
```

**Expected behavior**
setting `alias nuget='mono /usr/local/bin/nuget.exe'` is the only way recommend by [MS help page](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools). 

When I type `nuget`, I got this:

```
$ nuget
NuGet Version: 5.1.0.6013
usage: NuGet <command> [args] [options] 
Type 'NuGet help <command>' for help on a specific command.

Available commands:

 add               Adds the given package to a hierarchical source. http sources are not supported. For more info, goto https://docs.nuget.org/consume/command-line-reference#add-command.

 config            Gets or sets NuGet config values.

 delete            Deletes a package from the server.

 help (?)          Displays general help information and help information about other commands.

 init              Adds all the packages from the <srcPackageSourcePath> to the hierarchical <destPackageSourcePath>. http feeds are not supported. For more info, goto https://docs.nuget.org/consume/command-line-reference#in
it-command.

 install           Installs a package using the specified sources. If no sources are specified, all sources defined in the NuGet configuration file are used. If the configuration file specifies no sources, uses the default N
uGet feed.

 list              Displays a list of packages from a given source. If no sources are specified, all sources defined in %AppData%\NuGet\NuGet.config are used. If NuGet.config specifies no sources, uses the default NuGet feed
.

 locals            Clears or lists local NuGet resources such as http requests cache, temp cache or machine-wide global packages folder.

 pack              Creates a NuGet package based on the specified nuspec or project file.

 push              Pushes a package to the server and publishes it.
NuGet's default configuration is obtained by loading %AppData%\NuGet\NuGet.config, then loading any nuget.config or .nuget\nuget.config starting from root of drive and ending in current directory.

 restore           Restores NuGet packages.

 setApiKey         Saves an API key for a given server URL. When no URL is provided API key is saved for the NuGet gallery.

 sign              Signs a NuGet package with the specified certificate.

 sources           Provides the ability to manage list of sources located in %AppData%\NuGet\NuGet.config

 spec              Generates a nuspec for a new package. If this command is run in the same folder as a project file (.csproj, .vbproj, .fsproj), it will create a tokenized nuspec file.

 trusted-signers   Provides the ability to manage the list of trusted signers.

 update            Update packages to latest available versions. This command also updates NuGet.exe itself.

 verify            Verifies a signed NuGet package.

For more information, visit https://docs.nuget.org/docs/reference/command-line-reference
```

It's very strange why `build.sh` does not work as intended.

**Platform (please complete the following information):**
 - Platform: [.NET]
 - Environment: [NuGet Version: 5.1.0.6013]
 - Version of package [master]

**Additional context**
I'm using Ubuntu 18.04.2 LTS.

**Comment by tellarin** [comment]
@luizcavalcanti it builds OK for you on the Mac, right? If you have some free time, can you look into it?

**Comment by iMicknl** [comment]
I just gave it a try on my Mac and it builds without issues. My preference would be to have `nuget` as a required dependency and not set the alias in the build script.

@combacsa have you tried adding the alias to your ~/.bash_aliases or ~/.bash_profile as described on [the link you mentioned](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux).

**Comment by combacsa** [comment]
@iMicknl Of course, as I mentioned at the top of this issue, my `~/.bashrc`, `~/.bash_profile`, `~/.bash_aliases`, `~/.profile` all have that line.

So in my terminal, `nuget` just works, but `./build.sh` doesn't work. Very strange...

I'll try to execute each line of `build.sh` and will update the result.

**Comment by iMicknl** [comment]
@combacsa I understood that you set the alias, but thought you just put it in your terminal and not in your bash profile. I will also have a deeper look.
Which shell are you using in Linux? Are you using bash or zsh?

**Comment by combacsa** [comment]
@iMicknl I'm using `bash`. Now I'm seeing `Test run in progress..` and `Test Run Successful`.

**Comment by combacsa** [comment]
Just wrote a pull request #1780 which works on my Ubuntu machine. It would be appreciated if it also works on the Mac.
