### ISSUE TITLE
[CN DateTimeV2|Python] Datetime recognizer hangs for '一二三四五六七二二三四五六七三二三四五六七'

### ISSUE THREAD

**Issue by jiali-ms** [microsoft/Recognizers-Text#1783]
**Describe the bug**
call python datetime recognizer, for some case, it will hang.

**To Reproduce**

DateTimeRecognizer(Culture.Chinese).get_datetime_model().parse('一二三四五六七二二三四五六七三二三四五六七')

**Expected behavior**
'一二三四五六七二二三四五六七三二三四五六七' returned instantly

**Comment by tellarin** [comment]
This was not exactly a hang, but a perf issue that made it take a long time to process. The refactor done in PR #1815 solved this as a side-effect.
