### ISSUE TITLE
[Java] isRestrictedJavaVersion() returns wrong value

### ISSUE THREAD

**Issue by combacsa** [microsoft/Recognizers-Text#1786]
**Describe the bug**
[isRestrictedJavaVersion](https://github.com/microsoft/Recognizers-Text/blob/b211ef589d40a99bbf445858d4c76641b0bbe52c/Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/utilities/RegExpUtility.java#L399) check if `specVersion` (version on local) **is greater than or equal to** `targetVersion` (version required to Recognizers-Text), if I understood [Java API BigDecimal](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html) correctly.

As a result, even if Java >= 11 is installed, `result` variable always get `true`, and it will print out warning message, and fallback method will always be applied.

**To Reproduce**
0. Be sure that your local machine runs with Java version > 8
1. Go to 'Java/samples/simple-console'
2. Type 'mvn exec:java'
3. Type anything
4. See 'WARN: Look-behind groups with no maximum length not supported. Java version <= 8.'

**Expected behavior**
Not seeing such warning message

**Sample input/output**
(Described above)

**Platform (please complete the following information):**
 - Platform: [Java]
 - Environment: [OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)]
 - Version of package [master branch]

**Additional context**
I'm digging with the issue #1775 and if I fix the problem described above then more tests fails on `Zulu 11 SDK`. Strange. However, if I understand correctly, then current behavior of isRestrictedJavaVersion() is somewhat misleading.

**Comment by tellarin** [comment]
I'm a little confused here. It seem the problem is related to how OpenJDK handles regexes with groups or some other cause. 
Even if the fallback method to make pre-8 regexes safe is always used, this should not cause any test case failures.

**Comment by Batta32** [comment]
Hi @combacsa, sorry for the delay. We created the PR #2439 updating the `isRestrictedJavaVersion` method in order to validate if the used Java version is lower or equal than Java 8 (target version) in order to execute the fallback `bindLookbehinds` method.

Feel free to add your feedback in the PR 😊!
