### ISSUE TITLE
[DE DateTimeV2] The datetimeV2 prebuilt entity recognizes the utterance "Montag" as "diese Montag".

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#1787]
**Is your feature request related to a problem? Please describe.**
For example, if the utterance is "Wie ist das Wetter Montag/am Montag", the user means definitely next Monday but we get the Monday in the current week. This makes a problem when we are in a day after Monday.

**Describe the solution you'd like**
The solution can be to return both this Monday and next Monday. This happens already in the other case "am 23.7" when no year is specified. In this case, LUIS will return both the date of this year and next year (23.7.2019 and 23.7.2020).

**Describe alternatives you've considered**

**Additional context**

**Comment by tellarin** [comment]
This is a bug. "Montag" should return both a past and future resolutions. As in English, for example.

**Comment by tellarin** [comment]
Sorry. Actually this is already solved in the latest code.
