### ISSUE TITLE
personName only picked up the first name in one utterance

### ISSUE THREAD

**Issue by KayMKM** [microsoft/Recognizers-Text#1804]
**Describe the bug**
personName in luis only picked up the first name in one utterance, like "Create a meeting with John and Ben", it will only labelled "John" as an entity.

**To Reproduce**
1. create a luis model
2. add personName prebuilt entity
3. add an utterance with multiple person name like "Create a meeting with John and Ben"

**Expected behavior**
"John" and "Ben" will be labelled as personName

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.
input: create a meeting with john and ben
output:
```
{
  "query": "create a meeting with john and ben",
  "topScoringIntent": {
    "intent": "CreateCalendarEntry",
    "score": 0.9798931
  },
  "intents": [
    ...
  ],
  "entities": [
    {
      "entity": "john",
      "type": "builtin.personName",
      "startIndex": 22,
      "endIndex": 25
    }
  ]
}
```

**Platform (please complete the following information):**
 - Platform: 
 - Environment: LUIS
 - Version of package 

**Additional context**

**Comment by tellarin** [comment]
@KayMKM, Recognizers-Text doesn't support a Person type. The Person model in LUIS uses different tech, so this repo is not the right place for feedback on it.
I'll close this issue here. I'll update the comments if I find a better place for such feedback.

**Comment by KayMKM** [comment]
@tellarin Thanks for your reply! I will move this issue when you find the better place.
