### ISSUE TITLE
[CN DateTimeV2] Incorrect extracting "今日" from "今日头条" and "明日" from "网易手游《明日之后》" (filter?)

### ISSUE THREAD

**Issue by lan2720** [microsoft/Recognizers-Text#1823]
hi, how to fix this issue?

**Comment by lan2720** [comment]
Is there any way to load user-defined dict first and do some block for these NER?

**Comment by tellarin** [comment]
@lan2720, when reporting issues, please follow the template to clarify what the error is and what the desired output is OK? Can you add more details to these two issues you've opened?
Regarding the dictionary question, this is not currently supported. Can you give more details of how you'd like to use it? We may be able to enable it, depending on what exactly is needed.
Thanks.

**Comment by tellarin** [comment]
@lan2720 We'll break this into two separate items. PR #1833 will add a filter to remove these two examples. And I'll create an issue to add support for users to specify their own filter items.

**Comment by tellarin** [comment]
#1834 will represent this new feature.

**Comment by lan2720** [comment]
@tellarin Thank you! That's awesome!

**Comment by lan2720** [comment]
@tellarin  Hope the support for users to specify their own filter items will come soon.
