### ISSUE TITLE
[CN DateTimeV2] Incorrect "start" and "end" time for "上半年"and "下半年" 

### ISSUE THREAD

**Issue by lan2720** [microsoft/Recognizers-Text#1824]
```
上半年 {'values': [{'timex': '(2019-08-26,2019-08-26,P0Y)', 'type': 'daterange', 'start': '2019-08-26', 'end': '2019-08-26'}]}
下半年 {'values': [{'timex': '(2019-08-27,2019-08-27,P0Y)', 'type': 'daterange', 'start': '2019-08-27', 'end': '2019-08-27'}]}
```
Why did the start and end time is the same here? Note: my reference day here is 2019-08-26.

**Comment by tellarin** [comment]
I assume this are for halves of the year? Can you give an example of the full sentence and also what the current response you see is?
Thanks.

**Comment by tellarin** [comment]
@lan2720, can you give some examples of full sentences in Chinese with these entities so we add to the test set? Also, which platform are you using? .NET or JavaScript?
Thanks.
