### ISSUE TITLE
[HI Numbers] Consonant Unicode characters are not matching test cases

### ISSUE THREAD

**Issue by Chandan-Baba** [microsoft/Recognizers-Text#1841]
Hi Team,

I am trying to match consonent characters to match some test cases for cardinal number of Devnagri (Hindi). But they are failing always. Could anyone point me to some docs for unicode char or point what i'm missing here.
Below is the code from  yaml file: 

**ZeroToNineIntegerRegex: !simpleRegex**
  `def: (सात|आठ|चार|पाँच|शून्य|नौ|एक|दो|छह|(\u0924\u0940\u0928))`
**TwoToNineIntegerRegex: !simpleRegex**
  `def: (तीन|सात|आठ|चार|पाँच|नौ|दो|छह)`

CardinalNumberMap: !dictionary
  types: [ string, long ]
  entries:
    शून्य: 0
    एक: 1  
    दो: 2
    तीन: 3  

This is the json test case: 
{
    "Input": "तीन",
    "NotSupportedByDesign": "javascript,python,java",
    "Results": [
      {
        "Text": "तीन",
        "TypeName": "Number",
        "Resolution": {
          "subtype": "integer",
          "value": "3"
        },
        "Start": 0,
        "End": 4
      }
    ]
  }

The fail message : Assert.AreEqual failed. Expected<1>. Actual <0>

**Comment by tellarin** [comment]
@Chandan-Baba, in your example, 3 (तीन) is not in ZeroToNineIntegerRegex. If you add it there it still doesn't work?
Also, is there any specific reason that the values in the regex are not in their numerical order? Keeping them in the numerical order greatly helps reviewing and understanding patterns.

**Comment by tellarin** [comment]
I'll close this one for now. Please comment here if it still doesn't work and we can re-open it.

**Comment by Chandan-Baba** [comment]
> @Chandan-Baba, in your example, 3 (तीन) is not in ZeroToNineIntegerRegex in the same encoding as the others. If you add it there it still doesn't work?
**Instead of writing तीन in devnagari I thought to use unicode character. It was more like understanding the working or extractor. Also, one question is what if we write words in devenagari code only and not in unicode, will that affect?**
> Also, is there any specific reason that the values in the regex are not in their numerical order? Keeping them in the numerical order greatly helps reviewing and understanding patterns.
**Yes, They will come in numerical order once I do final push**
> And why only use 3 in that unicode encoding?
**I was testing with number 3, if it  is working or not with given unicode character.**
> Also, please make sure all your pattern/code/resources/specs files are encoded in UTF-8 for consistency.
**Sure.**

Update: I found that there are some errors in newly generated extractor file, which i corrected and it worked.

**Comment by tellarin** [comment]
@Chandan-Baba both devnagari and their unicode encoding work. .NET regexes, string comparisons, and dictionaries handle both correctly (if the encoding for the devnagari chars is one supported like UTF-8 or UTF-16). 
We suggest using the devnagari chars where possible to make it easier to read/understand the code, patterns, and specs. Unicode \u encoding should only be used if there's no default rendering of the char on browsers and in VS, or if there are multiple visually-similar chars and we want to make sure all are supported.
If all files are correctly encoded in UTF-8, there should be no issues.
