### ISSUE TITLE
[* Currency] Currency not recognized when used before value... eg.  USD 200

### ISSUE THREAD

**Issue by antonn** [microsoft/Recognizers-Text#1850]
**Describe the bug**
200 USD --> Gets recognized as Money with both isoCurrency and Value.
USD 200 --> here only 200 is getting recognized as Number. 

**To Reproduce**
1. Create prebuilt entities Money and Number
2. Type 200 USD in the Test interface. -> It works fine as Money gets recognized
3. Type USD 200 --> In this case only number. USD is not getting identified anywhere

**Expected behavior**
USD 200  should be recognized as Money with value 200 and isoCurrency USD

**Sample input/output**
I would like to buy this item for USD 200

**Platform (please complete the following information):**
 - LUIS English
 

**Additional context**

**Comment by antonn** [comment]
Any update on when this will be fixed ?

**Comment by tellarin** [comment]
Hi @antonn, it should come out in vNext+1. Tentatively planned for early next month.

**Comment by antonn** [comment]
Hi tellarin

Any update on the date of fix to luis.ai for this issue reported?

**Comment by antonn** [comment]
Any further update on this?

**Comment by tellarin** [comment]
Hi @antonn,
this is in the near-term plans, but there is no ETA yet.
