### ISSUE TITLE
[HI Numbers] How does Recognizer engine support Hindi double digit numbers?

### ISSUE THREAD

**Issue by Chandan-Baba** [microsoft/Recognizers-Text#1851]
Hi Team,

I want to know how the recognizer engine support Hindi double digit numbers? For example take an example of इक्कीस (21). In English, it is basically a merged number 20+1(Twenty+One). But Hindi doesn't support the same logic.

For example, below one is not recognizing expected <एक सौ सोलह> actual <सत्रह> :

TenToNineteenIntegerRegex: !simpleRegex
  def: (?:सत्रह|तेरह|चौदह|अठारह|उन्नीस|पंद्रह|सोलह|ग्यारह|बारह|दस)
ZeroToNineIntegerRegex: !simpleRegex
  def: (?:सात|आठ|चार|पाँच|शून्य|नौ|एक|दो|छह|तीन)
RoundNumberIntegerRegex: !simpleRegex
  def: (?:सौ|हजार|लाख|दस लाख|अरब|खरब|करोड़|दस करोड़|दस अरब)

AllHundredRegex: !nestedRegex
  def: **((?<=\b)({ZeroToNineIntegerRegex}(\s){RoundNumberIntegerRegex}(\s){TenToNineteenIntegerRegex})(?=\b))**
  references: **[ZeroToNineIntegerRegex, RoundNumberIntegerRegex, TenToNineteenIntegerRegex]**

Test Json :
{
    "Input": "एक सौ सोलह",
    "NotSupportedByDesign": "javascript,python,java",
    "Results": [
      {
        "Text": "एक सौ सोलह",
        "TypeName": "number",
        "Resolution": {
          "subtype": "integer",
          "value": "116"
        },
        "Start": 0,
        "End": 9
      }
    ]
  }

**Comment by tellarin** [comment]
@Chandan-Baba my understanding is that in Hindi the base number are from 0 to 99. It's not like in English where you have 0-9, then some special cases in the 10s and a fixed pattern from 20 to 99.
If this assumption is true, you need to change SeparaIntRegex and AllIntRegex (for example) to use a newly declared 0-99 or 1-99 regex to compose numbers. 
RoundNumberIntegerRegex would basically stay as a "direct" translation of English + lakh and crore (but parsing code would need to change to handle these two new terms).
I think opening an issue is not the best option for such questions. You can open a PR with some basic changes to use as example of what you're trying to do and folks can comment on the actual code with pointers.

**Comment by tellarin** [comment]
I'll close this issue now, ok?

**Comment by Chandan-Baba** [comment]
> @Chandan-Baba my understanding is that in Hindi the base numbers (in written form, i.e., non-numerical) are from 0 to 99. It's not like in English where you have 0-9, then some special cases in the 10s, and a fixed pattern from 20 to 99.
> If this assumption is true, you need to change SeparaIntRegex and AllIntRegex (for example) to use a newly declared 0-99 or 1-99 regex to compose numbers.
> RoundNumberIntegerRegex would basically stay as a "direct" translation of English + lakh and crore (but parsing code would need to change to handle these two new terms).
> I think opening an issue is not the best option for such questions. You can open a PR with some basic changes to use as example of what you're trying to do and folks can comment on the actual code with pointers.

Yes, You guessed this correct. I am making the changes based on the same.
