### ISSUE TITLE
[DE DateTimeV2] The expressions like "in den nächsten beiden Tage" is not recognized

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#1856]
**Describe the bug**
 The expressions like "in den nächsten beiden Tage" is recognized just as "den tag". A complete utterance can be "Was wird das wetter in den nächsten beiden Tage?". The closest english translation would be "How is the weather in the next two days?"

**To Reproduce**
1. Go to LUIS
2. Type 'Was wird das wetter in den nächsten beiden Tage?'

**Expected behavior**
The result should contain two  consecutive days in the time of spoken utterance.  

**Sample input/output**
The expressions like "in den nächsten beiden Tage" is recognized just as "den tag".

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: LUIS
 - Version of package: Last version

**Additional context**

**Comment by tellarin** [comment]
@rostam, when you open issues, can you please also provide a full sentence that includes the example entity, along with what exact response and resolution you'd expect? This will greatly help make sure we have high quality regression tests.
Thanks.

**Comment by rostam** [comment]
@tellarin sorry, I will do it in the future. I updated the description with an example and expected response.

**Comment by tellarin** [comment]
@rostam Sorry, could you also add the closest possible English translation for the sentence? That's also useful. I should have mentioned it in the previous comment too. :-(

**Comment by rostam** [comment]
@tellarin done!
