### ISSUE TITLE
datetime recognizer inconsistent with LUIS

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#187]
When I give LUIS the string "in 5 minutes" it resolves that to a datetime "2017-11-13T21:39:41"

However, when I use the local JavaScript recognizer is just recognizes the "5 minutes" and produces a duration "PT5M"

The local JavaScript recognizer should have found the datetime.

**Comment by tellarin** [comment]
@pcostantini, can you guys take a look at this one?

**Comment by pcostantini** [comment]
Only occurs when the sentence starts with the "in" connector.

Issue is this line:
https://github.com/Microsoft/Recognizers-Text/blob/b891ad519ac0a4c1002caad3ce49fac9524da7bf/JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts#L89

C# version works Ok
https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Utilities/AgoLaterUtil.cs#L37

**Comment by tellarin** [comment]
Issue has been fixed.
