### ISSUE TITLE
Handling of dateranges has changed in latest release

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/Recognizers-Text#1878]
After updating to the latest release 1.2.7, a couple of my regression tests just failed for these strings....

"from midday 1st jun 2000 for 48 hours"
"from 1st jun 2000 for 3 days"

This appears to be because the DateRange that is now being emitted doesn't contain an "end" entry in the ModelResult resolution.

**Comment by NeilMacMullen** [comment]
In 1.2.6.1
> 
> Input:'from 1st jun 2000 for 3 days'
>  ModelResult values
>    timex=2000-06-01 type=date value=2000-06-01
>  ModelResult values
>    timex=P3D type=duration value=259200

In 1.2.7

> Input:'from 1st jun 2000 for 3 days'
>  ModelResult values
>   timex=2000-06-01 Mod=since type=daterange sourceEntity=datetimepoint start=2000-06-01
>  ModelResult values
>    timex=P3D type=duration value=259200

**Comment by tellarin** [comment]
Hi @NeilMacMullen,
this is not a change in how **daterange** is handled per-se. This is more a case of a model refinement for consistency.
"1st jun 2000" by itself is a **date**, but "from 1st jun 2000" in this case should have the same meaning as "starting from 1st jun 2000".
As "starting from 1st jun 2000" represents a **daterange** starting on "1st jun 2000" with no defined end, the behaviour of the two sentences is now consistent.
I'll close this issue for now, but feel free to reply if you'd like to discuss it further.

**Comment by NeilMacMullen** [comment]
@tellarin Thanks - I'm all for consistency! :-) I'm still a little confused by why the parser doesn't then go on to treat the **for 3 days** fragment as an end date but I appreciate the ModelResult is a fairly 'raw' representation of the parse process.  My client application is a library that tries to turn the various combinations of ModelResult values into a simple pair of DateTimes representing start and end of a span of time. Is there any documentation for the intended interpretation of the various types that are emitted in the Resolution?
