### ISSUE TITLE
[EN DateTimeV2] Dates in format "2019-Aug-01" not recognized

### ISSUE THREAD

**Issue by dmvtech** [microsoft/Recognizers-Text#1894]
**Describe the bug**
Use datetime recognizers and the phrase "2019-Aug-01 to today". This returns a date instead of a range.

**To Reproduce**

1. Use datetime recognizers and the phrase "2019-Aug-01 to today"
2. See that it returns something like:
```
		"timex": "2019-10-01",
		"type": "date",
		"value": "2019-10-01"
```

**Expected behavior**
Expect a daterange similar to how the utterance "August 1st 2019 to today" will return:
```
		"timex": "(2019-08-01,2019-10-01,P61D)",
		"type": "daterange",
		"start": "2019-08-01",
		"end": "2019-10-01"
```

**Additional context**
Bit more info [here](https://github.com/microsoft/botbuilder-dotnet/issues/2629).

**Comment by tellarin** [comment]
Similar problem for "2019/Aug/01".
