### ISSUE TITLE
CommonDefinitions.ttinclude file missing

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/Recognizers-Text#1921]
**CommonDefinitions.ttinclude file missing**
I was trying to generate the numbers defenition to add a new language. The link given for the CommonDefinitions.ttinclude in the documentation is [here](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Definitions/CommonDefinitions.ttinclude) which is missing. Can you please provide the actual file or else provide a link for the actual file.

**To Reproduce**
1. Go to 'https://blog.botframework.com/2018/01/24/contributing-luis-microsoft-recognizers-text-part-1/'
2.  Go to the section- Generating platform-specific definitions – .NET
 
There the link provided for the file is broken. 
![image](https://user-images.githubusercontent.com/31855189/68046925-1de84000-fd03-11e9-85c1-fcdb952a0a3a.png)

![image](https://user-images.githubusercontent.com/31855189/68046951-33f60080-fd03-11e9-979a-2d289d801451.png)

**Comment by tellarin** [comment]
It seems the path in that article is incomplete (missing a piece of the namespace). The file exists on git under https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Definitions.Common/CommonDefinitions.ttinclude
