### ISSUE TITLE
[ES DateTimeV2] DateRange incorrectly detected instead of single DateTime

### ISSUE THREAD

**Issue by frasparacio** [microsoft/Recognizers-Text#1958]
When I write my sentence with a datetimeV2 and the word **_una_** it recognizes that there is a datetimeV2 but detect the entity as a **datetimerange** taking the entity from the word una

- organizame **una** reunion con Francesco Sparacio **mañana a las 12** 
- organizame **una** reunion **el 27/11 a las 24**

I think this might be related to the fact that the article “una” is also meaning an hour in Spanish (1 o clock) but the resulting detected entity is wrong making inusable the DateTimeV2 recognition

**Comment by iMicknl** [comment]
I just faced the same issue in a workshop. Using the following sentence `Tengo una reunión el viernes en londres`, it will set the time to 1, which is not correct. 
When a time is added (a las 5), it will be a DateTimeRange from 1 to 5.

Using `una` is quite common in Spanish and also ambiguous.
