### ISSUE TITLE
Issue in adding new Language

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/Recognizers-Text#1959]
I was trying to a vernacular Indian language to the recognizer repo. When I'm trying to convert the .tt file using the T4 template, I'm getting the following reference error messages even though the the new cs file is getting created in the same project. Also the other existing tt files are getting compiled succesfully. 

**Error Messages:**  
1. Compiling transformation: The type or namespace name 'YamlParser' could not be found (are you missing a using directive or an assembly reference?)
2. Compiling transformation: foreach statement cannot operate on variables of type '?' because '?' does not contain a public instance definition for 'GetEnumerator'	Microsoft.Recognizers.Definitions.Common	PathCommonDefinitions.ttinclude
3. Compiling transformation: The type or namespace name 'SimpleRegex' could not be found (are you missing a using directive or an assembly reference?)
4. Compiling transformation: The type or namespace name 'NestedRegex' could not be found (are you missing a using directive or an assembly reference?)
5. Compiling transformation: The type or namespace name 'ParamsRegex' could not be found (are you missing a using directive or an assembly reference?)

Assuming the error occured because of the mistake in my tt file/yaml file, I tried to run the T4 template using the existing yaml and tt files. But still it threw the same errors.

When I'm removing the text template reference, the solution is building and running without any errors. 
Can  you please help out with the errors mentioned. 

**Platform:**
 - Platform: .NET
![image](https://user-images.githubusercontent.com/31855189/69810258-81399500-1211-11ea-86aa-5d46857e20eb.png)

![image](https://user-images.githubusercontent.com/31855189/69810304-96162880-1211-11ea-85b0-ef0385bced73.png)

**Comment by tellarin** [comment]
@Aliandi, could you folks help track this? We've started seeing it more too and you probably have more experience with it. Let us know if there is no bandwidth. Thanks!

**Comment by tellarin** [comment]
@vidyakdil which version of VS ad .NET framework are you in? Maybe be relevant.

**Comment by Aliandi** [comment]
@vidyakdil this probably has to do with the T4 template. Could you share what yours looks like?

**Comment by tellarin** [comment]
Closing this as it hasn't been updated in a while and we haven't got similar reports.

**Comment by felaray** [comment]
I have the same issus. Just clone the project and added the new T4 file.

![image](https://user-images.githubusercontent.com/5403865/171786468-73437f59-1a18-490b-9148-f443140d7cf8.png)

IDE:
VS2019 
![image](https://user-images.githubusercontent.com/5403865/171786512-a47f2a86-0c7a-4cf1-9467-ad39211dc950.png)

VS2022
![image](https://user-images.githubusercontent.com/5403865/171786691-35653978-c946-4e74-9644-4f7755cb1ff7.png)

OS: Win10 10.0.19043
![image](https://user-images.githubusercontent.com/5403865/171786812-7a401c1b-a994-4722-b480-f3487e38dcb4.png)
