### ISSUE TITLE
Add support for Romanian

### ISSUE THREAD

**Issue by aparatfoto** [microsoft/Recognizers-Text#2021]
Please consider to add support for romanian language.

**Comment by tellarin** [comment]
@aparatfoto, we'd love to add Romanian support, but it's currently not in the immediate plan.
Would you be willing to contribute with spec translations and/or help in implementation?

**Comment by aparatfoto** [comment]
Yes, I want to contribute and help.

**Comment by tellarin** [comment]
@aparatfoto, that's great to hear!

One very useful way to start is to translate the Spec cases for each type from English (located in the /Specs directory) into the target language. This "test set" can then be used to validate quality and coverage of support in the new language. We suggest starting with the Number (and subtypes) json specs (located in /Specs/Number/English; you can skip the filenames that end in "Mode" initially).

These links also provide more detail about the process to contribute to a new language (but may be a little outdated):
* [Overview and language resources](https://blog.botframework.com/2018/01/24/contributing-luis-microsoft-recognizers-text-part-1/)
* [Implementing language specific behaviour](https://blog.botframework.com/2018/02/01/contributing-luis-microsoft-recognizers-text-part-2/)
* [Test specs and testing in general](https://blog.botframework.com/2018/02/12/contributing-luis-microsoft-recognizers-text-part-3/)

Please let us know what you'd like to start with and if you have any questions.

**Comment by tellarin** [comment]
Closing this issue as it's not currently in the pipeline.
Feel free to discuss here if anyone is interested in contributing support.
