### ISSUE TITLE
[EN DateTimeV2] "Incomplete" recognition of recurring times as sub duration

### ISSUE THREAD

**Issue by yuvalkirstain** [microsoft/Recognizers-Text#2031]
**Describe the bug**
expressions like 'once a day' are specifying a frequency. The DateTimeRecognizer will catch the sub-expression 'a day' as a datetimeV2.duration rather than what it should have done, which is to catch the entire expression and label it as a datetimeV2.frequency or sometihng of that sort.

**To Reproduce**
to reproduce the behavior:
feed the DateTimeRecognizer model parser with the expression 'once a day'.

**Comment by tellarin** [comment]
Issue originally reported in Python, to be tested across platforms.

**Comment by LionbridgeCSII** [comment]
@tellarin, expressions like 'once a day', 'once a week', etc. now seem to be correctly parsed as Set in .NET and Python.
