### ISSUE TITLE
[Python | * Number] Number parser reduces the global precision of decimals 

### ISSUE THREAD

**Issue by ufukhurriyetoglu** [microsoft/Recognizers-Text#2035]
**Describe the bug**
recognizers-number reduces the global precision of decimals and this causes sporadic failures in codebase. 

**Expected behavior**
Decimals precision should not mess up with global settings.

**Platform (please complete the following information):**
 - Platform: Python
 - Environment: pip package
 - Version of package: 1.0.0a3

**Additional context**
instead of https://github.com/microsoft/Recognizers-Text/blob/2a09c82f82a290b6051fd784d717ca40cfc28a9a/Python/libraries/recognizers-number/recognizers_number/number/parsers.py#L11
please make use of `decimal.localcontext()`

**Comment by tellarin** [comment]
@ufukhurriyetoglu, can you provide a couple sentence examples where you see the problem?
Thanks.

**Comment by ufukhurriyetoglu** [comment]
we encounter its' side-effects only.
