### ISSUE TITLE
[DE DateTimeV2] Enable recognition of dialectal clock expressions

### ISSUE THREAD

**Issue by Ablesius** [microsoft/Recognizers-Text#2036]
**Is your feature request related to a problem? Please describe.**
In German it is possible not only to relate to time with prepositional expressions ("Viertel nach"/"Viertel vor" (quarter past, quarter to)) but also without prepositions:

- "Viertel 6" = "05:15"
- "Halb 6" = "05:30" (cp. English "half six")
- "Dreiviertel 6" = 05:45

It would be really nice if the recognition for these expressions could be enabled. Shouldn't be too hard since it's really just these three expressions ("Halb" already works); other expressions aren't possible to resolve to these times.

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
No alternatives, as the only other solution - not implementing the recognition - is already in place.

**Additional context**
None

**Comment by tellarin** [comment]
@LionbridgeCSII, can you take a look at this one?

**Comment by Ablesius** [comment]
@LionbridgeCSII if you have a PR ready, I might be able to contribute there, too :)

**Comment by Ablesius** [comment]
Thanks for enabling this! :1st_place_medal:
