### ISSUE TITLE
[PT DateTimeV2] Incorrect timex for week days and broken resolution

### ISSUE THREAD

**Issue by daelsala** [microsoft/Recognizers-Text#2076]
Customer verbatim with issue example
https://eastus.api.cognitive.microsoft.com/luis/v2.0/apps/xxx-subscription-key-info-xxx
Returns: ( trucated )
 'entities': [
    {
      'entity': 'sexta-feira.',
      'type': 'builtin.datetimeV2.date',
      'startIndex': 60,
      'endIndex': 71,
      'resolution': {
        'values': [
          {
            'timex': '2020-04-38',
            'type': 'date',
            'value': 'not resolved'
          }
        ]
      }
    },

It appears there is a bug with the timex date received by LUIS
             'timex': '2020-04-38'

I already brought this issue up with the LUIS product group who pointed me here.

**Comment by tellarin** [comment]
@daelsala, thanks for reporting. This was triaged as a high-priority issue.

**Comment by daelsala** [comment]
Latest from customer:
I found a workaround. This issues hapens only when there is a period of sentence after weekday.
This happens in portugueese, I have not tested in other languages.
Removing the last period, we get a correct TIMEX resolution. If there is a last period, TIMEX resolution Bugs.
Example:

https://eastus.api.cognitive.microsoft.com/luis/v2.0/apps/XXXX_XXXX_XXXX_XXXX?verbose=true&timezoneOffset=0&subscription-key=xxxxxxxxxxxxxxxxxxxxx&q=quero%20comprar%20sms%20me%20manda%20um%20boleto%20para%20sexta%20feira.

date in portugues: sexta feira. ( with period )
Timex resolution:     
        "values": [
          {
            "timex": "2020-04-38",
            "type": "date",
            "value": "not resolved"
          }

https://eastus.api.cognitive.microsoft.com/luis/v2.0/apps/XXXX_XXXX_XXXX_XXX?verbose=true&timezoneOffset=0&subscription-key=XXXXXXXXXXXXXXXXX&q=quero%20comprar%20sms%20me%20manda%20um%20boleto%20para%20sexta%20feira

( same as before, just removed last period )

date in porguues: sexta feira ( without las period )
Timex resolution: 
        "values": [
          {
            "timex": "XXXX-WXX-5",
            "type": "date",
            "value": "2020-04-24"
          },


Summary Workaround: Remove period after day of week.

**Comment by daelsala** [comment]
It seems the removal of the "." period in the end of the request resolved the issue for the customer

**Comment by tellarin** [comment]
Thanks for the update, @daelsala. This will greatly help tracking the cause of the issue.
