### ISSUE TITLE
[EN Unit Dimension] Include recognition of sub-types of dimension unit, such as weight, distance, volume

### ISSUE THREAD

**Issue by ashly1yeo** [microsoft/Recognizers-Text#2097]
**Is your feature request related to a problem? Please describe.**
Not a problem but it provides better definition of the Unit Dimension type to have the Weight, Distance, Speed, Volume and Length.

**Describe the solution you'd like**
Instead of recognizing "100 lbs" as Unit-Dimensions, it will be typed as Unit-Weight just like "36.4°C" is recognized as Unit-Temperature. 

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by tellarin** [comment]
Modifying the type would be considered a breaking change.
Would it be reasonable to return an extra attribute with the Dimension sub-type? This schema is already used for numbers. E.g.,

`
"TypeName": "number",
"Resolution": {
    "subtype": "fraction",
     ...
}
`

**Comment by ashly1yeo** [comment]
Yes that is what I am proposing, sorry it is not clear.  

Unit-Weight is TypeName: Unit, Subtype: Weight

**Comment by tellarin** [comment]
@joaopsousa FYI and tracking.
