### ISSUE TITLE
[EN Number] Add support for Indian numbering system (lakh, crore,...)

### ISSUE THREAD

**Issue by LionbridgeCSII** [microsoft/Recognizers-Text#2112]
Indian numbering system is not currently supported in English, so the following examples are not correctly handled by the Text Recognizers:

"There are 1 crore boxes in this container"
"The submarine mein weigh 25 lakh tonnes"
"Am I eligible for a lone of 35 lakh rupees"

**Expected behavior**
numbers containing "lakh", "crore",... should be correctly extracted and parsed in English.

**Comment by tellarin** [comment]
I'm not very familiar with usage in written form, but would people also write in the digit form like "5,00,000"? If so, the implementation of this functionality should also cover support for such cases.
