### ISSUE TITLE
[* Phonenumber] Phone number recognition does not validate US phone numbers

### ISSUE THREAD

**Issue by xtianus79** [microsoft/Recognizers-Text#2114]
**Describe the bug**
Is this supposed to take other numbers than US phone numbers? it gives positive results for numbers that are clearly not us phone numbers.

I added this to the validation to further verify the phone number. 

```javascript 

    private static async validatePhoneNumber(promptContext: PromptValidatorContext<string>): Promise<boolean> {
        const phoneResponse = await promptContext.recognized.value;
        let phoneValidation: ModelResult[];
        phoneValidation = phoneModel.parse(phoneResponse);
        console.log('phoneValidation ', phoneValidation);
        if (phoneValidation.length > 0) {
            const phoneNumber: string = phoneValidation[0].resolution['value'];
            const phoneResolved = phoneNumber.replace(/[()+-\s]+/g, '');
            const phoneResolvedScore: number = parseFloat(phoneValidation[0].resolution['score']);
            console.log('phoneResolved', phoneResolved.length);
            console.log('phoneResolvedScore', phoneResolvedScore);
            if (phoneResolved.length >= 10 && phoneResolved.length <= 11 && phoneResolvedScore >= .5) {
                console.log('phone verified');
                return true;
            }
           
        }
        return false;
    }
```

**Comment by tellarin** [comment]
@xtianus79, the phone number recognizer is supposed to recognize any mention that looks like a "generic" phone number, so it is not US-focused. The current design also doesn't validate numbers for any country. 
We can consider exposing separate functionality to allow choosing to trigger validation and to choose target countries. Would you be able to contribute to the implementation? We can start with US validation and expand later.
Let us know if you'd like to propose a design.

**Comment by tellarin** [comment]
@xtianus79, I'll close this for now as it's not currently in the short-term plan for support.
Feel free to comment here and we can reopen in the future.
Thanks!
