### ISSUE TITLE
US Phone number not recognized within Spanish text

### ISSUE THREAD

**Issue by HanLiMS** [microsoft/Recognizers-Text#2117]
Issue
US Phone number not recognized within Spanish text

Sample Input
"Llámame al (206)555-1212 cuando puedas si no puedes contactarme al 10.0.0.111"

Response:
 (206)555-1212 --> not detected as Phone Number.

**Comment by tellarin** [comment]
This works correctly in /master. The next release of the packages will include the fix.
Thanks.
