### ISSUE TITLE
French AGE entities incorrectly recognized as DateTime-Duration

### ISSUE THREAD

**Issue by HanLiMS** [microsoft/Recognizers-Text#2118]
Issue
French AGE entities incorrectly recognized as DateTime-Duration

Sample Input
"M. Jim Kramer, de la station 6, a 64 ans et a demandé l'annulation immédiate de son compte bancaire"

Response:
Wrong detection of "64 ans" as "DateTime-Duration".

**Comment by tellarin** [comment]
From the Recognizers points of view, "64 ans" is both a duration and an age, and it returns both as expected.
