### ISSUE TITLE
[DE DateTimeV2] Incorrect extraction of "dienstag 11:00 uhr" drops time component

### ISSUE THREAD

**Issue by rhurey** [microsoft/Recognizers-Text#2123]
**Describe the bug**

**To Reproduce**
Run "dienstag 11:00 uhr" as a LUIS query
Get 
"entity": "dienstag 11",
"type": "builtin.datetimeV2.date",
as the result      

**Expected behavior**
Dropping the :00 uhr changes the meaning of the result from Tuesday 11 oclock to Tuesday 11 and isn't what was expected.

**Sample input/output**
```
{
  "query": "dienstag 11:00 uhr",
  "topScoringIntent": {
    "intent": "None",
    "score": 0.296005666
  },
  "entities": [
    {
      "entity": "dienstag 11",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 10,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-WXX-2",
            "type": "date",
            "value": "2020-02-11"
          },
          {
            "timex": "XXXX-WXX-2",
            "type": "date",
           "value": "2020-08-11"
          }
        ]

```
**Platform (please complete the following information):**
 - Environment: LUIS
 
**Additional context**
Started out as a Speech Services issue @ https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/546

**Comment by tellarin** [comment]
@rhurey, thanks for reporting. The fix is in and it will be out in the next update.

**Comment by SOliasS** [comment]
![image](https://user-images.githubusercontent.com/14180046/87801354-e8af5e00-c84f-11ea-9ee6-b9f5c762f3d4.png)

**Comment by tellarin** [comment]
Hi @SOliasS, both the original reported sentence and yours produce the correct output in the latest NuGet package.
Perhaps for some reason LUIS is not yet consuming it. You can also see the current behaviour in the /master branch by using the sample console app in .NET/Samples/SimpleConsole.

**Comment by SOliasS** [comment]
@tellarin i tried it in the luis console and it also did the same thing.
In the app i'm using version 1.12.1.
Do you have any idea where the problem could be?
![image](https://user-images.githubusercontent.com/14180046/87936559-54cdd400-ca93-11ea-8921-e98b84579924.png)

**Comment by tellarin** [comment]
@SOliasS, it seems LUIS is not yet using the latest release. I meant the console project that exists here in the GitHub repo. That one can be used to test the current behaviour and validate such cases are now supported.
I've pinged the LUIS team to check their updates.

**Comment by SOliasS** [comment]
@tellarin it would be nice if you let me know when it's finally activated/updated.

**Comment by tellarin** [comment]
> I thought you meant when the next luis nuget update hits.
> @tellarin it would be nice if you let me know when it's finally activated/updated.

We don't directly work on LUIS, but I'll post here if I hear back.

**Comment by SOliasS** [comment]
Any news reguarding when this will be integrated in luis?
