### ISSUE TITLE
[FR DataTimeV2] "été" means "summer" or "been" depending of the context (+ minor bug)

### ISSUE THREAD

**Issue by Oursse** [microsoft/Recognizers-Text#2153]
**Describe the bug**
Currently, "été" is recognized at anytime as a DateTimeV2.
In french, "été" means "been" most of the time. It only means "summer" when it's preceed by : "l'", "cet" and "en" (I can't think of anything else right now).
Also, making a sample for this bug report, I found that "mer." is also recognized as a DateTimeV2 in  the sentence bellow.

**To Reproduce**
Parse "Durant l'été, cet été, j'ai été à la mer." in the recognizer.
It returns :
```
{
  "Text": "été",
  "Start": 9,
  "End": 11,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "SU",
        "type": "daterange",
        "value": "not resolved"
      }
    ]
  }
}
{
  "Text": "été",
  "Start": 18,
  "End": 20,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "SU",
        "type": "daterange",
        "value": "not resolved"
      }
    ]
  }
}
{
  "Text": "été",
  "Start": 28,
  "End": 30,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "SU",
        "type": "daterange",
        "value": "not resolved"
      }
    ]
  }
}
{
  "Text": "mer.",
  "Start": 37,
  "End": 40,
  "TypeName": "datetimeV2.date",
  "Resolution": null
}
```

**Expected behavior**
It should return :
```
{
  "Text": "été",
  "Start": 9,
  "End": 11,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "SU",
        "type": "daterange",
        "value": "not resolved"
      }
    ]
  }
}
{
  "Text": "été",
  "Start": 18,
  "End": 20,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "SU",
        "type": "daterange",
        "value": "not resolved"
      }
    ]
  }
}
```

**Platform:**
 - Platform: [.NET]
 - Environment: [console app]
 - Version of package [v1.3.2]

**Question**
I also wanted to ask when will the 1.3.3 (or 1.4.X) will be released on .NET and the other platforms and if it would integrate this bug patch ?

**Comment by tellarin** [comment]
A fix for this is ongoing and will be out shortly. Thanks for reporting, @Oursse!

**Comment by Oursse** [comment]
Hi,
after rereading my post, I realized that "mer." is just a shortened Wednesday (Mercredi) writing. So it's kind of not a bug, in french "mer" means "sea". So maybe a way to recognize only the shortened Wednesday writing is to search for "mer." but only followed by a date number. This way, even if mer is in the end of a sentence, it won't be recognized as a date.

What should I do ? Open another issue ? Modify this one ?

**Comment by tellarin** [comment]
I think this is also already solved along with the "été" issue. Merging soon. No need to open a new issue.

**Comment by tellarin** [comment]
Can you give sentences examples of a proper and an informal use of "mer." in date/time sentences?
This will help coverage of our specs.

**Comment by Oursse** [comment]
> @Oursse, can you give sentences examples of a proper and an informal use of "mer." in date/time sentences? This will help improve spec coverage.

I think I've never heard "mer." orally and it's rarelly written by french native speaker. It's mostly used formally on flyers or websites. Here's some examples from events websites :
"Quand ? mer. 10 juin 2020. Horaires : de 14h à 16h."
"Exposition d'art contemporain le mer. 24 juin 2020."
"Mer. 6 Mai 2020 à 18h"

> BTW, does use of the abbreviation always has the "." at the end, of may people skip it? What about usage of "Me" as abbreviation for "Mercredi"?

Concerning the dot, the good use is "mer."
Eventually, it can be changed to "Mer." if starting the sentence.
I can't tell the frequency of the use of "mer" (without the dot) but I bet it's pretty low.
Lastly, concerning "Me", I've never used nor see it in any circumstances.
