### ISSUE TITLE
[ES DateTimeV2] Complex range incorrectly interpreted

### ISSUE THREAD

**Issue by tellarin** [microsoft/Recognizers-Text#2213]
"después del 1 de enero de 2007 y no más tarde que el 1 de enero de 2010" -> one joint interval (ideal, but OK to return two ranges.)
"desde el 1 de enero de 2010 o no más tarde que el 1 de enero de 2007" -> two ranges

**Comment by LionbridgeCSII** [comment]
@tellarin, it seems that in English both cases return two separate ranges.
Should we modify the general behaviour of the Extractor to return a single joint interval in the first case? 
Or only conform the Spanish behaviour to the English one? (now in Spanish 3 ranges are returned instead of 2)

**Comment by tellarin** [comment]
@LionbridgeCSII, I think making Spanish conform to English is enough in this case. Thanks for the details.
