### ISSUE TITLE
[IT Number] String "tr" recognized as number zero

### ISSUE THREAD

**Issue by MaxiPigna** [microsoft/Recognizers-Text#2226]
If you execute the instruction `NumberRecognizer.RecognizeNumber("tr", Culture.Italian)` you expect no result since "tr" doesn't resemble any number. Instead, it returns zero as result.

The same it happens also on LUIS, where "tr" is recognized as a number entity.
![image](https://user-images.githubusercontent.com/33937977/89120103-d0784980-d4b3-11ea-8b10-a396c2abe527.png)

**To Reproduce**
NumberRecognizer.RecognizeNumber("tr", Culture.Italian)[0].Resolution.First().Value
"0"

**Expected behavior**
NumberRecognizer.RecognizeNumber("tr", Culture.Italian).Any()
false

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package, LUIS
 - Version of package v1.4.0

**Comment by tellarin** [comment]
Thanks for the catch. A fix is on its way.

**Comment by MaxiPigna** [comment]
Great, thanks! When you will release the new nuget package version, is the update immediately published also on LUIS?

**Comment by tellarin** [comment]
@MaxiPigna, not automatically. But the fix is merged and the next package release should enter the LUIS pipeline soon.
Thanks for the bug report.
