### ISSUE TITLE
[* URL] Invoke GetURLModel without culture param crashes library

### ISSUE THREAD

**Issue by 7i77an** [microsoft/Recognizers-Text#2237]
**Describe the bug**
Missing check null culture:

if (culture != null && .....

**Platform (please complete the following information):**
 - Platform: [ .NET]
 - Environment: [nuget package]
 - Version of package [e.g. v1.4.0]

**Comment by tellarin** [comment]
Thanks for catching this, @7i77an. Would you be able to create a PR?

**Comment by 7i77an** [comment]
Added PR #2239
