### ISSUE TITLE
[DE DateTimeV2] The time expressions like "anderthalb", "einundhalb", und "zweieinhalb" are not recognized.

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#2271]
**Describe the bug**
The time expressions like "anderthalb", "einundhalb", und "zweieinhalb" are not recognized in LUIS.

**To Reproduce**
1. Go to LUIS
2. Type 'Spule anderthalb Stunden vor '
3. See error

**Expected behavior**
The recognized times should be: 
- anderthalb Stunden = one and a half Hours (= 90 Minutes) 
- zweieinhalb Stunden = two and a half hours 

**Sample input/output**
In the following examples, 
- Spule anderthalb Stunden vor 
- Spring zweieinhalb Stunden nach vorne 

The recognized times should be as mentioned: 
- anderthalb Stunden = one and a half Hours (= 90 Minutes) 
- zweieinhalb Stunden = two and a half hours 

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: LUIS
 - Version of package: the last version

**Additional context**

**Comment by tellarin** [comment]
@LionbridgeCSII, can you take a look? Thanks.
