### ISSUE TITLE
[EN DateTimeV2] Inconsistency between English and Spanish in handling "from" and issue with list

### ISSUE THREAD

**Issue by tellarin** [microsoft/Recognizers-Text#2287]
Currently there is an inconsistency between English and Spanish in handling cases like "from 2015".

Spanish correctly handles it as range if in Experimental mode (#2230), however English is always treating it as such. This behaviour should be changed to match the one for Spanish.

Also, even if under Experimental mode, in cases like "from 2015 and 2016" the recognizers should return only two range years "2015" and "2016", which currently fails.

**Comment by tellarin** [comment]
@LionbridgeCSII, can you fix this after completing #2283 or in parallel to it? This is a new blocking issue for some consumers of the packages.

**Comment by LionbridgeCSII** [comment]
@tellarin, only the pattern 'from' + [year] should be handled in Experimental mode, right? 
While other expressions like 'from' + [date|dateperiod] (e.g. 'from today', 'from october', 'from the end of 1989') should continue to be supported in standard mode.

**Comment by tellarin** [comment]
This can get tricky. In Spanish any case of "de <datetimeV2>" is only treated as "since" under Experimental mode, right? If so, then English should behave the same.

**Comment by LionbridgeCSII** [comment]
> This can get tricky. In Spanish any case of "de " is only treated as "since" under Experimental mode, right? If so, then English should behave the same.

ok, then I will follow the Spanish implementation.
And for the affected cases in the model, I will modify their expected results ( and move the originals to the experimental model).

**Comment by tellarin** [comment]
> And for the affected cases in the model, I will modify their expected results ( and move the originals to the experimental model).

Please do, and keep the "non-range" version of the results in the original Model specs file. I.e. each sentence in both files, showing the difference in extraction/resolution.

Thanks!
