### ISSUE TITLE
[EN NumberRange] Parsing exception in sentence with multiple range mentions

### ISSUE THREAD

**Issue by tellarin** [microsoft/Recognizers-Text#2289]
The sentence "find sales greater than 30 and less than or equal to 40 and greater than or equal to 50" causes an exception during extraction. The expected results would be the extraction on the different ranges.

Each of the three mentions is extracted correctly if in a sentence by themselves.

**Comment by tellarin** [comment]
"greater than 30 and less than or equal to 40" by itself works correctly and returns a single range too.
"less than or equal to 40 and greater than or equal to 50" by itself is incorrectly interpreted. It should return two disjoint ranges.

**Comment by tellarin** [comment]
@LionbridgeCSII, can you take a look if this still happens?

**Comment by LionbridgeCSII** [comment]
> @LionbridgeCSII, can you take a look if this still happens?

yes, it does. I started looking into this issue yesterday.
