### ISSUE TITLE
[DE DateTimeV2] The time expressions like "in 3 Wochen" and "in 1 Woche" do not work although "in drei Wochen" and "in eine Woche" work."

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#2291]
**Describe the bug**

**To Reproduce**
1. Go to 'LUIS'
2. Type 'Was kommt in 3 Wochen auf ARD'

**Expected behavior**
Luis is not able to resolve "Was kommt in X Wochen" correctly, if "X" is given as a number such as "Was kommt in 2 Wochen". If "X" is a word such was "Was kommt in zwei Wochen" in works.

**Sample input/output**
If the utterance "Was kommt in 3 Wochen auf ARD", LUIS will recognize the wrong entities as follows,
```
    "entities": {
      "datetimeV2": [
        {
          "type": "date",
          "values": [
            {
              "timex": "XXXX-00-00",
              "resolution": [
                {
                  "value": "not resolved"
                }
              ]
            }
          ]
        }
      ],
```
but if you enter "Was kommt in drei Wochen auf ARD", the following correct results are given:
```
"entities": {
      "datetimeV2": [
        {
          "type": "date",
          "values": [
            {
              "timex": "2020-10-14",
              "resolution": [
                {
                  "value": "2020-10-14"
                }
              ]
            }
          ]
        }
```

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: LUIS
 - Version of package: Last version

**Additional context**

**Comment by tellarin** [comment]
@LionbridgeCSII, can you take a look? It would also be nice to check other languages for similar faults.
Thanks.

**Comment by tellarin** [comment]
@rostam, thanks for reporting. Would it be possible to use the SimpleConsole project in the repository to test/show the examples in future issues?
LUIS output is schema is different from the recognizers and it may be out-of-sync with the latest recognizers (momentarily), so using the SimpleConsole would help speedup the process.

**Comment by rostam** [comment]
@tellarin Sure, I will use the SimpleConsole project in future.
