### ISSUE TITLE
[DE DateTimeV2] Holidays + time in German not properly extracted and parsed

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#2313]
**Describe the bug**
Although the word "ostermontag" alone is recognized, LUIS can not recognize the date time in "Was läuft am ostermontag um 10:30 uhr?"

**To Reproduce**
1. Go to LUIS
2. Type 'Was läuft am ostermontag um 10:30 uhr?'

**Expected behavior**
The expected behavior is to recognize the two dates of "ostermontag" and 10:30.

**Sample input/output**
The sample input is:
Was läuft am ostermontag um 10:30 uhr?

No entities other than numbers are recognized.

**Platform (please complete the following information):**
 - Platform: .Net
 - Environment: LUIS
 - Version of package: Last version

**Additional context**

**Comment by tellarin** [comment]
"welche filme laufen an heiligabend um 18 uhr?" is another example of failing case for the same base scenario

**Comment by tellarin** [comment]
@Lionbri
