### ISSUE TITLE
[DE DateTimeV2] The expression "welche filme laufen an heiligabend um 18 uhr?" does not work.

### ISSUE THREAD

**Issue by rostam** [microsoft/Recognizers-Text#2314]
**Describe the bug**
LUIS can not recognize the date time in "welche filme laufen an heiligabend um 18 uhr?".

**To Reproduce**
1. Go to LUIS
2. Type "welche filme laufen an heiligabend um 18 uhr?:

**Expected behavior**
The date and time in "welche filme laufen an heiligabend um 18 uhr?" can be recognized.

**Sample input/output**
The sample input is "welche filme laufen an heiligabend um 18 uhr?" and no date or time entities are recognized

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: LUIS
 - Version of package: Last version

**Additional context**

**Comment by tellarin** [comment]
Merging this with #2313 as they both refer to Holidays.
