### ISSUE TITLE
[DE DateTimeV2] "<date> auf <Uhrzeit>" incorrectly recognizes date and time separately

### ISSUE THREAD

**Issue by mujdricza** [microsoft/Recognizers-Text#2336]
**Describe the bug**
If someone refers to a date and additionally a time with the preposition "auf", LUIS does not recognize a datetime entity, but a date and a time entity separately.

**To Reproduce**
1. Make a LUIS model with prebuilt entity "datetimeV2"
2. Type e.g. 'Stelle Wecker am 27. Oktober auf 9:00 Uhr' (CET)
3. See error as in "Sample output for the input above"

**Expected behavior for the input above**
```
"entities": {
                "date": [
                  {
                    "value": "2019-10-27T08:00:00Z",
                    "literal": "27.Oktober um 9:00 Uhr"
                  },
                  {
                    "value": "2020-10-27T08:00:00Z",
                    "literal": "27.Oktober um 9:00 Uhr"
                  },
                  {
                    "value": "2019-10-27T20:00:00Z",
                    "literal": "27.Oktober um 9:00 Uhr"
                  },
                  {
                    "value": "2020-10-27T20:00:00Z",
                    "literal": "27.Oktober um 9:00 Uhr"
                  }
                ],
```

**Sample output for the input above**
```
            "entities": {
              "date": [
                {
                  "value": "2019-10-27",
                  "literal": "27.Oktober"
                },
                {
                  "value": "2020-10-27",
                  "literal": "27.Oktober"
                },
                {
                  "value": "T08:00:00Z",
                  "literal": "9:00 Uhr"
                },
                {
                  "value": "T20:00:00Z",
                  "literal": "9:00 Uhr"
                }
              ],
```

**Platform (please complete the following information):**
 - Platform: [e.g. .NET, JavaScript, Python, Java]
 - Environment: LUIS
 - Version of package [e.g. v1.0.8.1]

**Comment by tellarin** [comment]
Hi @mujdricza, 

this behaviour is already currently supported in the recognizers. Sometimes there is a gap between implementation of specific features and the time LUIS updates the model. Model update on the LUIS side is underway, but we don't have visibility on the ETA.

For any issues, you can validate them with the code in the repository by running the SimpleConsole project and setting the language to the desired target language. This way we can pinpoint if there's indeed a bug or a gap in consumption.

Thanks!

**Comment by mujdricza** [comment]
Hi @tellarin,
thank you for the reply, and for the hint on SimpleConsole.

Best regards
mujdricza
