### ISSUE TITLE
Schema doesn't match LUIS

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/Recognizers-Text#234]
The schema returned by the recognizers is close to the LUIS schema for Entities but not exactly the same. It should be exactly the same.  For example the number recognizer returns "start", "end", and "text" fields. These are "startIndex", "endIndex", and "entity" fields in LUIS.  

A developer should be able to work with an entity the same way, regardless of whether it came from a call to LUIS or a call to a recognizer. The schemas need to be identical for that to be true.

**Comment by tellarin** [comment]
Closing this as the schema gap was reduced with time and there are no immediate plans to make additional changes.
