### ISSUE TITLE
[Python | ZH DateTimeV2] Relative holidays like ＂今年圣诞节＂ not properly recognized

### ISSUE THREAD

**Issue by Tao2301230** [microsoft/Recognizers-Text#2350]
**Describe the bug**

**To Reproduce**
t = '今年圣诞节'
print(''.join([str(i.__dict__) for i in Recognizers.recognize_datetime(t, Culture.Chinese)]))
return:［］

**Expected behavior**
[{'start': 0, 'end': 3, 'resolution': {'values': [{'timex': '2020-12-25', 'type': 'date', 'value': '2020-12-25'}]}, 'text': '今年圣诞节', 'type_name': 'datetimeV2.date'}]

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.

**Platform (please complete the following information):**
 - Platform: [e.g.  Python]
 - Environment: [e.g. console app]
 - Version of package [e.g. v1.0.2a2]

**Additional context**

**Comment by Tao2301230** [comment]
chinese/holiday_parser
line 208: year += self.config.get_swift_year(reference.year)
should be
year += self.config.get_swift_year(year_relative)

and 
chinese/holiday_parser_config
function get_swift_year should be 
    def get_swift_year(self, text: str) -> int:
        trimmed_text = text.strip().lower()
        swift = 0
        if trimmed_text.startswith('明'):
            swift = 1
        if trimmed_text.startswith('去'):
            swift = -1
        if trimmed_text.startswith('今'):
            swift = 0
        return swift

**Comment by tellarin** [comment]
Hi @Tao2301230, thanks for reporting this issues in Python.

For future issues, would it be possible to also check if they work in .NET and mention the behaviour in both platforms when opening an issue? That greatly helps us to triage problems.

Also, as you seem to have identified the fix (as in #2348), could you create PRs for them? That would also speedup integrating the fix. When creating a PR, please add the relevant test cases to the specs to show that the fix works and causes no side effects.

Thanks again!

**Comment by Tao2301230** [comment]
Hi @tellarin, Thank you for your response,
I will learn to use .NET and try if it works in .NET version.
It's my first time to report this in github, not sure the right process. I will add related examples to #2348.  Er, but not sure about PR, what is PR mean?

**Comment by Tao2301230** [comment]
I saw in the contribute.md. ok

**Comment by tellarin** [comment]
Hi @Tao2301230,

your issue reports are already very useful. 

A PR is a "Pull Request". It's how people typically contribute code changes. 

For example, this PR fixes another issue in Chinese: https://github.com/microsoft/Recognizers-Text/pull/2352/files

To also test in .NET, you can run the SimpleConsole project (after changing the language there to Chinese).

Thanks!
