### ISSUE TITLE
[EN DateTimeV2] "end of" by itself incorrectly extracted as entity

### ISSUE THREAD

**Issue by tellarin** [microsoft/Recognizers-Text#2367]
Cases like "We've reached the end of the line" lead to incorrect output tagging "end of" as a datetime entity.
This should be fixed, along with an analysis of similar situations.

**Comment by LionbridgeCSII** [comment]
@tellarin, I am unable to reproduce this issue (neither in visual studio nor in simple console).

**Comment by tellarin** [comment]
Interesting. Some recent commit may have partially addressed some cases. But if the input is just "end of" I still see it happening in the current /master.

**Comment by LionbridgeCSII** [comment]
> Interesting. Some recent commit may have partially addressed some cases. But if the input is just "end of" or "end of the" I still see it happening in the current /master.

ah yes, it is true. I will check it after finishing #2371.

**Comment by tellarin** [comment]
Please also add the 3 cases listed here as new specs, just to avoid regressions later. Thanks.
