### ISSUE TITLE
[* Unit] Currency recognizer doesn't recognizer compound structures in words   

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#237]
The currency recognizer will find $3.50 in the following:

"it only cost $3.50"

but finds _two entities_ when this same is expressed in words:

"it only cost 3 dollars 50 cents."

**Comment by tellarin** [comment]
These cases should also work:
"thirteen dollars and  forty-five cents"
"thirteen dollars forty-five cents" 
"thirteen dollars forty five"
