### ISSUE TITLE
[*] Offset mismatch with special Unicode characters

### ISSUE THREAD

**Issue by HanLiMS** [microsoft/Recognizers-Text#2376]
Issue:
The offset returns different values for the similar input with different positions of special characters:

"[0xFFFC] it will rain Wednesday will be sunny" outputs "Wednesday" with offset=16
"it will rain [0xFFFC] Wednesday will be sunny" outputs "Wednesday" with offset=15 (expected)

Please find the Unicode char (0xFFFC) online (I cannot copy it here for the raw format). 
https://unicodemap.org/details/0xFFFC/index.html

**Comment by LionbridgeCSII** [comment]
@tellarin, I am unable to reproduce this one.

**Comment by tellarin** [comment]
@HanLiMS, I'm also unable to reproduce this one.
