### ISSUE TITLE
Number entity in French doesn't recognize decimals

### ISSUE THREAD

**Issue by Basma-Emara** [microsoft/Recognizers-Text#2389]
**Describe the bug**
The number recognizer in french culture returns bad resolutions for decimals

**To Reproduce**
1. Go to "www.luis.ai"
2. Create an app with "French" culture and add number entity
3. Publish the app
4. Hit the endpoint with text "6,12" in French culture "number entity"
5. Check the resolution of the output
3. The resolution returned is "612"

**Expected behavior**
The resolution should be "6.12"

**Sample input/output**
Input: "6,12"/ Output: "612"/ Expected Output: "6.12"
Input: "5.45"/ Output: "545"/ Expected Output: "5.45"

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package/LUIS
 - Version of package: 1.4.0

**Comment by tellarin** [comment]
@Basma-Emara, we can't replicate this problem in the Recognizers. The output is correct. It seems to be a LUIS-specific issue.
 Tagging @hazemelh.
