### ISSUE TITLE
Bug handling "week of September 30th" as a range

### ISSUE THREAD

**Issue by tellarin** [Microsoft/Recognizers-Text#24]
Currently recognizing only "September 30". "date": "XXXX-09-30"

Should be:
{ "entity": "september 30th", "type": "builtin.datetimeV2.date", "resolution": { "values": [{ "timex": "XXXX-09-30", "type": "date", "value": "2016-09-30" },{"timex": "XXXX-09-30","type": "date", "value": "2017-09-30" }]} }

**Comment by rubio41** [comment]
already checked in
