### ISSUE TITLE
[DE DateTimeV2] Implement support for German DateTimes

### ISSUE THREAD

**Issue by tellarin** [Microsoft/Recognizers-Text#240]

**Comment by tellarin** [comment]
@flo-zuewi has an initial PR for it.

**Comment by Michaelvsk** [comment]
What's the progress here? datetimev2 is still not supported by LUIS and the old datetime entity type is practically unusable for german language (way too many false positives and other bugs).

**Comment by pke** [comment]
Is there some way I can help here? When will the partial DateTime made available in LUIS? @tellarin

**Comment by tellarin** [comment]
Hi @pke,
you can start taking a look at the Spec json files for DateTime that are marked as "NotSupported": "dotnet". Some of them also have "Comment" tags that may give more details on the current issues.
We suggest focusing on the .NET plat first and then we can port to JS. 
Writing additional specs to make sure coverage is good are also very valuable. 
Unfortunately the German DateTime quality doesn't meet our bar to ship yet. :-(
Any help is greatly appreciated!

**Comment by tellarin** [comment]
Closing this as support is now available. Thanks @n01d, @miserale, and everyone else!

**Comment by pke** [comment]
Cool! Which PR brought this in?

**Comment by tellarin** [comment]
It was not a specific PR, but release dotnet-v1.1.5 made it "official".
