### ISSUE TITLE
[.NET] Recognizers mishandle illegal Unicode characters

### ISSUE THREAD

**Issue by assafi** [microsoft/Recognizers-Text#2426]
**Describe the bug**
When presented with some illegal Unicode character such as an orphaned surrogate pair returned offsets are off considerably. 
Expectation would be that the recognizer would either ignore the illegal character or count it as a single character.

**To Reproduce**

Input: "\uDDDD1975"

**Expected behavior**
"1975" returned as a DateRange at either position 0 or 1. Instead returned at position 2.

**Sample input/output**

```csharp
        [TestMethod]
        [TestCategory("FunctionalTest")]
        [DataRow("1975", "1975", 0)]
        [DataRow(" 1975", "1975", 1)]
        [DataRow("🤣1975", "1975", 2)] // "🤣".Length == 2, so OK
        [DataRow("\uDDDD1975", "1975", 1)] // "\uDDDD".Length == 1, but returned offset is 2. <---- orphaned surrogate pair.
        [DataRow("\uFFFF1975", "1975", 1)] // "\uFFFF".Length == 1, so OK.
        [DataRow("\u08881975", "1975", 1)] // "\u0888".Length == 1, so OK.
        public void TextRecognizers_DateRange(string text, string expectedValue, int expectedOffset)
        {
            var results = DateTimeRecognizer.RecognizeDateTime(text, Culture.English);

            Assert.AreEqual(1, results.Count);
            Assert.AreEqual(expectedValue, results.First().Text);
            Assert.AreEqual(expectedOffset, results.First().Start);
            Assert.AreEqual("datetimeV2.daterange", results.First().TypeName);
        }
```

**Platform (please complete the following information):**
 - Platform: .NET462
 - Environment: nuget
 - Version of package v1.4.2

**Additional context**

**Comment by tellarin** [comment]
The recognizers seem to behave correctly for input "\uDDDD1975". It seems there's some artifact when running the unit test code.
When feeding "\uDDDD1975" directly to the recognizers, the input string length is 5, and the returned entity start index is 1, as expected. 
But when running the unit test above, there's some econding issue happening somewhere and the string length as given to the recognizers is 6, not 5. "\uDDDD" is replaced by two chars. You can see it by debugging the test run.
