### ISSUE TITLE
[* Sequence] Recognizers don't extract email address with * or capital letters in the suffix by default

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/Recognizers-Text#2427]
**Describe the bug**

Not able to find the email address, if the sentence end with the text.

**To Reproduce**
use the API : SequenceRecognizer.RecognizeEmail  , 
Pass the sentence end with text  and  api returns as NULL 
Input  :   my email address is vin*****@Live.com and you need my mobile number?

**Expected behavior**
output  :  **vin*****@Live.com**

**Platform (please complete the following information):**
 - Platform:  NET 
 - Environment:  nuget package
 - Version of package 1.4.2.

**Comment by tellarin** [comment]
Hi @rvinothrajendran,
this behaviour is by default as the recognizers perform validation of potential e-mails before output. In your example, the capital 'L' in the domain part of the e-mail is not supported. 
You can disable strict validation by enabling the `SequenceOptions.Relaxed` flag when creating/utilizing an instance of the sequence recognizer.
`    SequenceRecognizer.RecognizeEmail(query, culture, SequenceOptions.Relaxed)`
