### ISSUE TITLE
[Python | ZH Unit] Wrong for sentence like "50千米每小时"

### ISSUE THREAD

**Issue by xunzhide** [microsoft/Recognizers-Text#2433]
**Describe the bug**
It does not work when the sentence contains "千米每小时".

**To Reproduce**
recognize_dimension("50千米每小时", Culture.Chinese)
recognize_number("50千米每小时", Culture.Chinese)

**Expected behavior**
dimension: 50千米每小时  
number: 50

**Platform (please complete the following information)**
Platform: python3.6
Version 1.0.2a2

**Comment by ChopperMan33** [comment]
Hi, @xunzhide 
I found that the Python code works correctly in /master for "50千米每小时".
You can package it by manual complicating. 
```json
{
  "Text": "50",
  "Start": 0,
  "End": 1,
  "TypeName": "number",
  "Resolution": {
    "value": "50"
  }
}
{
  "Text": "50千米每小时",
  "Start": 0,
  "End": 6,
  "TypeName": "dimension",
  "Resolution": {
    "unit": "Kilometer per hour",
    "value": "50"
  }
}
```

**Comment by tellarin** [comment]
You can also use the SampleConsole provided in the repo to test. We'll plan a new alpha release of the Python packages soon.
