### ISSUE TITLE
[EN | JavaScript DateTimeV2] Two-digit years in Date resolve to 2020 and 2021

### ISSUE THREAD

**Issue by apolya01** [microsoft/Recognizers-Text#2436]
**Describe the bug**
Dates with a two digit year <70 resolve to 2020 and 2021.

**To Reproduce**
- Call `Recognizers.recognizeDateTime("12/26/45", Recognizers.Culture.English)`
- Observe that `results[0].resolution.values[0]` has 'value' field of "2020-12-26"
- Observe that `results[0].resolution.values[1]` has 'value' field of "2021-12-26
- Call `Recognizers.recognizeDateTime("12/26/1945", Recognizers.Culture.English)`
- Observe that `results[0].resolution.values[0]` has 'value' field of "1945-12-26"

**Expected behavior**
Dates with two digit years should resolve to appropriate year (e.g. '45' -> 1945 and maybe 2045)

**Sample input/output**
 `Recognizers.recognizeDateTime("12/26/45", Recognizers.Culture.English)`

```
[
  {
    timex: "XXXX-12-26",
    type: "date",
    value: "2020-12-26",
  },
  {
    timex: "XXXX-12-26",
    type: "date",
    value: "2021-12-26",
  },
]
```

**Platform (please complete the following information):**
 - Platform: Javascript
 - Environment: npm package
 - Version of package 1.3.0

**Comment by tellarin** [comment]
This issue cannot be reproduced in the code on /master. We'll plan a new package release soon.
You can test the current code using the SampleConsole project in the repo.
