### ISSUE TITLE
[* Unit] Units should not be lumped together into Volume unit and Weight unit

### ISSUE THREAD

**Issue by chrimc62** [microsoft/Recognizers-Text#2445]
**Describe the bug**
The definition of a number of units are lumped together into a generic class like "Volume unit" or "Weight unit".  There is no reason to lump these units together.  I suspect it is because the definition of some of the units depend on country or context, but that is not a concern of the NLU layer.

**To Reproduce**
1. Add dimension entity to LUIS
2. Try an utterance like "2 quarts".  

Actual: Units resolution is "Volume unit" 
Expected: Units resolution is "Quart"

**Expected behavior and proposal**
Change https://github.com/Microsoft/Recognizers-Text/blob/master/Patterns/English/English-NumbersWithUnit.yaml#L3 as below.

Remove and change Volume unit.
```
    Volume unit: fluid dram|gill|quart|minim|cord|peck|bushel|hogshead|barrels|barrel|bbl
```
```
Dram: fluid dram
Gill: gill
Quart: quart
Minim: minim
Cord: cord
Peck: peck
Bushel: bushel
Hogshead: hogshead
Barrel: barrel, bbl, barrels
```

Remove and change Weight unit.
```
Weight unit: pennyweight\|grain\|british   long ton\|us short hundredweight\|stone\|dram
```
```
Pennyweight: pennyweight
British long ton: british long ton
US short ton: us short ton
US short hundredweight: us short hundredweight
Stone: stone
Dram: dram
```

**Comment by tellarin** [comment]
It looks like this is an artifact of an old design decision and is no longer needed. We'll try to include the change in the next package release.
