### ISSUE TITLE
[Java] Validate correctly the entire structure of specs for each Model type

### ISSUE THREAD

**Issue by Batta32** [microsoft/Recognizers-Text#2464]
**Describe the bug**
The current unit tests of Java doesn't validate correctly the spec structure for each model type. For example the [DateParser.json](https://github.com/microsoft/Recognizers-Text/blob/master/Specs/DateTime/English/DateParser.json) specs, contains `start` property which is not validated in the [DateTimeTest.java](https://github.com/microsoft/Recognizers-Text/blob/master/Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java) causing false positives.

**To Reproduce**
1. Go to [DateTimeTest](https://github.com/microsoft/Recognizers-Text/blob/master/Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java)
2. See the structure that validates the [assertResultsDateTime](https://github.com/microsoft/Recognizers-Text/blob/master/Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java#L47) method
3. Compare the validated structure with the [DateParser.json](https://github.com/microsoft/Recognizers-Text/blob/master/Specs/DateTime/English/DateParser.json) specs
4. See that not all the properties are validated

**Expected behavior**
All the models should be correctly validated, checking the correct properties against to the specs.

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.
\- 

**Platform (please complete the following information):**
 - Platform: Java

**Additional context**
See discussion of the PR #2461 as the `NumberTest` was updated to cover the `end` and `start` properties.

**Comment by tellarin** [comment]
@Batta32, could you folks prioritize this one?

**Comment by Batta32** [comment]
Hi @tellarin, we will be discussing with @tracyboehrer in order to tackle this issue as soon as we can.

We will let you know any update 😊.

**Comment by Batta32** [comment]
@tellarin, after discussing with @tracyboehrer, we will tackle this issue when we re-prioritize our work after the next release 😊.

**Comment by tellarin** [comment]
@Batta32, any updates on this?

**Comment by Batta32** [comment]
Hi @tellarin, we didn't start to tackle this issue as we are doing the migration of the Java components for the [botbuilder-java](https://github.com/microsoft/botbuilder-java) repository.

We will let you know as soon as we start working on this issue 😊.

**Comment by Batta32** [comment]
Hi @tellarin, we want to let you know that this issue we will be tackle the next iterations 😊. We will let you know the updates here.
