### ISSUE TITLE
Time does not take into consideration timezones or refDateTime

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2467]
I have the following text "After 14:00 UTC" or "After 14:00 EST" while it just returns a time type with 14:00:00 which is correct but then the timezone piece is completely missing.
What I would like to do is if i pass any of those strings, I would like to get a DateTimeOffset returned with the refDateTime  plus the time and timezone info in the DateTimeOffset
so if i pass that string with new DateTime(2020, 9, 1)

I expect 
20-09-01 14:00 -5:00 (for EST)
20-09-01 14:00 0:00 (for UTC)

**Comment by tellarin** [comment]
@zoinkydoink, which version of the libraries are you using? .NET has TimeZone support, but it’s not enabled by default. You need to use the DateTimeOptions.EnablePreview flag.
