### ISSUE TITLE
[ES DateTimeV2] Issues with time of day modifiers in Spanish like "de la mañana" vs. "am"

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2477]
8 menos cuarto de la mañana  Returns T0745
8 menos cuarto am  Returns 8

8pm menos cuarto Returns T19:45
8 pm menos cuarto Returns T20
8 menos cuarto pm Returns 8 

The last one is not common and may not be supported.

**Comment by LionbridgeCSII** [comment]
I started looking into this one (of the mentioned cases only "8 pm menos cuarto" still fails)
