### ISSUE TITLE
[* Currency] Support for compound Currency entities in languages other than English

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2479]
"15 dollars and 15 cents" is a single currency entity in EN, but the PT and ES counterparts are captured as a pair of currency entities.
EN: 15 dollars and 15 cents  Returns 15.15 Dollar
PT: 15 dólares e 15 centavos  Returns 15 Dólar, 15 Centavo
ES: 15 dólares y 15 centavos  Returns 15 Dólar, 15 Centavo
DE: "25 Dollar 50" => 25 "Dollar"

**Comment by tellarin** [comment]
Currently only English recognizes compound Currency entities. All other languages recognize two entities.
This is not considered a bug, but an extension, which can be implemented after higher priority bugs are fixed.

**Comment by cahann** [comment]
@tellarin how do we track the enhancements? Should i create other tasks?

**Comment by tellarin** [comment]
We can track it here. But currently most enhancements have low priority due to resource limitations.

**Comment by LionbridgeCSII** [comment]
looking into this
