### ISSUE TITLE
Currency with conjunctions in PT

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2480]
"15 dollars and 15 cents" is a single currency entity in EN, but the PT and ES counterparts are captured as a pair of currency entities.
EN: 15 dollars and 15 cents  Returns 15.15 Dollar
PT: 15 dólares e 15 centavos  Returns 15 Dólar, 15 Centavo
ES: 15 dólares y 15 centavos  Returns 15 Dólar, 15 Centavo

**Comment by tellarin** [comment]
Merged with #2479.
