### ISSUE TITLE
Weird behavior for European decimals in PT

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2484]
PT: Seu total é de $24,50  Returns 245 Dólar, which doesn't fit whether the comma is being used for digit-grouping or as a decimal.

**Comment by tellarin** [comment]
We cannot replicate this. Recognition and parsing behave as expected.

**Comment by srandal** [comment]
Sorry for the long delay. I'm still seeing the same behavior with a pt-br app:
For "Seu total é de $24,50" it identifies the builtin.currency string, but resolves it to:
number: 245
units: Dólar
Here's the URI for my app's endpoints to reproduce it:
https://banking-expanded-bot.cognitiveservices.azure.com/luis/prediction/v3.0/apps/b2166977-10e1-42dd-9c5c-f181eb4392b9/slots/production/predict?subscription-key=decf48fb56d44a34b621d3d6b564f348&verbose=true&show-all-intents=true&log=true&query=Seu total é de $24,50
