### ISSUE TITLE
[FR DateTimeV2] Datetime recognized separately in French, which is inconsistent with English

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2486]
For this weekday + time construction, only the weekday value is returned in FR. Both are returned in EN:
•	FR: "9h le Mardi" returns T09/T21 and XXXX-WXX-2 separately
•	EN: "9 a.m. on Tuesday" returns XXXX-WXX-2T09

**Comment by LionbridgeCSII** [comment]
looking into this one
