### ISSUE TITLE
"ago" construction treated as an absolute time instead of an offset from the current time (FR)

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2487]
In FR, the offset number in this construction is evaluated as a time itself, instead of being subtracted from the current time. It's handled correctly in EN.
•	FR: "Je l'ai commandé il y a 24 heures" ("I ordered it 24 hours ago") returns T00 regardless of the current time

**Comment by tellarin** [comment]
Merged with #2478.
