### ISSUE TITLE
[* DateTimeV2] Resolving 2-digit year mentions

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2493]
When faced with a 2-digit year, LUIS returns a timex with a century value of 20 if year is less than 30, 19 if the year is greater than 30, and it omits the year entirely if it's in the 30s.
input    =>  date string  => timex
12/12/29 => 12/12/29 => 2029-12-12
12/12/30 => 12/12      => XXXX-12-12
12/12/39 => 12/12      => XXXX-12-12
12/12/40 => 12/12/40 => 1940-12-12
Presumably this threshold will change over time.
We're wondering why the year is thrown out entirely (instead of returning both 1930-12-12 and 2030-12-12)

**Comment by tellarin** [comment]
This is due to an old design decision. The goal is to allow users to specifify the thresholds if they want to override the default and to also return the alternatives. But this is currently a breaking change.
The 30s case seems to be a bug though. We'll double check.

**Comment by LionbridgeCSII** [comment]
checking this
