### ISSUE TITLE
Not recognizing rupees as a currency unit (DE)

### ISSUE THREAD

**Issue by cahann** [microsoft/Recognizers-Text#2496]
DE ignore rupees but other languages include it:
•	DE: "10000 Rupien" returns only a number
•	FR: "10000 roupies" returns only a number
•	ES: "10000 rupias" returns 10000, "Rupia" as currency
•	PT: "10.000 rúpias" returns 10000, "Rupia" as currency

**Comment by tellarin** [comment]
Merged with #2495.
