### ISSUE TITLE
[JavaScript | * DateTimeV2] Add missing filter methods

### ISSUE THREAD

**Issue by LionbridgeCSII** [microsoft/Recognizers-Text#2509]
**Is your feature request related to a problem? Please describe.**

Javascript is missing the implementation of some filter methods. 
In particular: FilterAmbiguity in MergedExtractor and ValidateMatch in DateExtractor.
This causes issues with certain patterns, for example:
- the Spanish input "Mi temperatura era 37.1 por la mañana" returns the wrong extraction "Mi" (as abbreviation of "miercoles") because the result is not filtered by FilterAmbiguity.
- the input "Labs were notable for a BUN/Cr of 30/4.85, troponin 0.182" returns the wrong extraction "30/4.85" as date because the result is not excluded by ValidateMatch.

**Describe the solution you'd like**

Add the methods FilterAmbiguity and ValidateMatch in Javascript MergedExtractor and DateExtractor as implemented in the other platforms.

**Comment by LionbridgeCSII** [comment]
looking this one

**Comment by LionbridgeCSII** [comment]
@tellarin, has this issue been fixed?

**Comment by tellarin** [comment]
Thanks for the catch. Closed by mistake.
