### ISSUE TITLE
[EN DateTimeV2] Incorrect interpretation of ET timezone?

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2519]
I have the following text

> Participating in the @encodeclub hackathon? @danielgileshelm is leading an Intro to Skynet Workshop this Wednesday March 10th 12:30pm ET. Sign up!

which Generates the following data

```
 {
        "DateTime": "2021-03-10T12:30:00-05:00",
        "UtcOffsetMinutes": -240,
        "Timezone": "UTC-04:00",
        "Text": "this wednesday march 10th 12:30pm et",
        "Timex": "XXXX-03-10T12:30"
      }
```

It clearly seems to be picking up -5GMT but the offset is -240 when I think it should be -300 to make it a 5hour difference. also it clearly says its -5 but the timezone it picked up was UTC-04:00"

**Comment by tellarin** [comment]
Offset was incorrect in the data file for 'ET'. A fix will be merged soon. Thanks for reporting.
