### ISSUE TITLE
[ZH NumberRange] Some ranges are not recognized correctly 

### ISSUE THREAD

**Issue by substill** [microsoft/Recognizers-Text#2526]
2票房占比过20的影片有几部？  --  cannot recognize "过20" as ">20"

哪些影投公司2019第2周的电影周票房就已经超过了500万的呀，还有20万人次以上来观影的呀？   --  cannot recognize "20万人次以上" as ">200000"

我问你啊就是那个幕后之王收视率超过了百分之零点九，它是在哪个台播的呀  -- cannot recognize "超过了百分之零点九" as ">0.9%".

**Comment by tellarin** [comment]
First case is supported in the repo. It will be included in the next release (v.1.6.1).

The other two cases unfortunately hit an issue out of scope for the current desing. Number and range condition are separated by the "object" (people or percentage) and so are not recognized.

I'll close this issue as by-design. But we'll keep these cases in mind for a future new approach.
