### ISSUE TITLE
[AR Numbers] Arabic number recognizer not handling decimal numbers correctly

### ISSUE THREAD

**Issue by senthilchandramohan** [microsoft/Recognizers-Text#2545]
Arabic number extraction model is missing decimals while extracting numbers.

Examples for numbers not being extracted as expected:
Input: 25799‪,‪52  Output: 25799
Input: 26،013‪,94  Output: 26013
Input: 12،220,13  Output: 12220

**Comment by tellarin** [comment]
@LionbridgeCSII, could you take a look at this? I believe it should be a simple fix. Let us know otherwise.
