### ISSUE TITLE
[JavaScript | EN DateTimeV2] Phrases indicating the present moment are not consistently recognized as dates.

### ISSUE THREAD

**Issue by apolya01** [microsoft/Recognizers-Text#2563]
**Describe the bug**
Several English-language phrases indicating the present moment are not recognized as dates, others are.

**To Reproduce**
Examples (called with recognizeDateTime())
"Now" ('Can you meet now') -> recognized
"Right now" ('Let's go right now') -> recognized

"at the moment" ('Can you meet at the moment') -> not recognized
"at present" ('He's not here at present') -> not recognized
"at the present time" ('We're working on that at the present time') -> not recognized
"at this time" ('We're not open at this time')  -> not recognized

**Expected behavior**
All above phrases are recognized similarly to "now" and "right now"

**Sample input/output**
See above

**Platform (please complete the following information):**
 - Platform: JavaScript
 - Environment: npm package
 - Version of package 1.3.0

**Comment by tellarin** [comment]
@LionbridgeCSII, could you check these in both JS and .NET? Thanks.
