### ISSUE TITLE
[EN DateTimeV2] Not combining timezone resolution with daterange resolution 

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2571]
`6:00, 23 Apr - 22:00, 27 April (UTC+8)`

This might be fixed by this fix  https://github.com/microsoft/Recognizers-Text/issues/2552 but I cant test it as I dont have the latest package, When is the latest package with all the fixes coming? Is there a release schedule so we can see when each fix is to be released? thank you

**Comment by tellarin** [comment]
You can use the SimpleConsole in the project to test the current code. Unfortuantely the next release is currently delayed for one week.

**Comment by tellarin** [comment]
During triage we validated that this is current supported in the current repo code.
