### ISSUE TITLE
European language cultures fails to recognize floating point numbers with Number prebuilt entity

### ISSUE THREAD

**Issue by saroskarms** [microsoft/Recognizers-Text#2574]
**Describe the bug**
Number entity used in European cultured LUIS application does not recognize floating point numbers. For example, Italy supports comma as decimal separator so 2,5 should be interpreted as 2.5 rather than 25.0.
LUIS product team fixed this behavior for 4 European languages - Spanish, German, Dutch and Italian. This bug is for requesting Microsoft to run test for this scenario with all the languages/cultures LUIS supports.

**To Reproduce**
1. On LUIS portal, create LUIS app with Italian culture. 
2. Add  Number prebuilt entity to it. Train and  publish this app
3. Use sample here  https://github.com/Azure-Samples/cognitive-services-quickstart-code/tree/master/dotnet/LanguageUnderstanding/predict-with-sdk-3x
4. Update this sample for prediction key, prediction endpoint and query. Query could be "2,5"

**Expected behavior**
For Italian, 2,5 is recognized as 25.0 
(Italian is just one example. Would like to request testing for all languages so we as users don't have to report this behavior one by one for each language.)

**Sample input/output**
For Italian, 2,5 is recognized as 2.5 

**Platform (please complete the following information):**
 - Platform:  .NET
 - Environment: Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime
 - Version of package V3.0.0

**Additional context**
Have reported this problem for 4 languages so far with 2 separate support requests and 2 rounds of fixes have addressed this. We would like this scenario to be tested in all language cultures supported by LUIS

**Comment by tellarin** [comment]
@saroskarms, unfortunately this issue seems to happen outside of the Recognizers-Text scope. Numbers in those 4 languages are currently supported.
I'll close this issue for now. But feel free to comment here if there are additonal questions.
