### ISSUE TITLE
[PT, IT, es-mx, fr-ca DateTimeV2] Currency with a comma decimal is resolved incorrectly

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2598]
**Additional context**
This was described in a previous issue that was closed because it couldn't be reproduced:
https://github.com/microsoft/Recognizers-Text/issues/2484
I added a comment to the original one to include a screenshot from running it in-browser, but I'm also creating this one because I don't know if commenting on a closed issue automatically re-opens it.

**Describe the bug**
"Seu total é de $24,50"
returns these values:
number: 245
units: Dólar

**To Reproduce**
1. Create a pt-br, it-it, es-mx, or fr-ca app with builtin.currency
2. Test "Seu total é de $24,50"

**Expected behavior**
number: 24,5
units: Dólar

**Platform (please complete the following information):**
 - Platform: 
 - Environment: in browser
 - Version of package ?

**Comment by tellarin** [comment]
Hi @srandal,
as mentioned in the previous issue, this is currently supported correctly in the recognizers. It looks like LUIS does some post-processing after the recognizers output. For such issues, the LUIS team needs to be contacted directly.

**Comment by tellarin** [comment]
Please do not open new issues for issues marked as supported. If more discussion is necessary, please re-use the closed issue for discussion. If the discussion raises an unsuporte case, we can reopen the issue.
Thanks.

**Comment by srandal** [comment]
Good to know. We'll follow up with the LUIS team for this one, and from now on I'll just comment on the closed issue when I see one marked supported that still looks broken.
