### ISSUE TITLE
[PT, IT number] A number with a period decimal is resolved incorrectly

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2600]
**Describe the bug**
A number that uses a period for the decimal is resolved to 2 separate numbers

**To Reproduce**
1. Create a pt-br or it-it app
2. Add the built-in number entity type
3. Test "24.50"

**Expected behavior**
Similar to en-us, where 24.50 and 24,50 are both resolved as 24.5
If the European format is expected, a period should be treated as a digit separator only if it's followed by a 3 digit group.

**Sample input/output**
As applicable, add examples of text input and json output to help explain the problem.

**Platform (please complete the following information):**
 - Platform: 
 - Environment: in browser
 - Version of package: ?

**Comment by tellarin** [comment]
The current behaviour is correct according to the current module design. Numbers using dot as decimal separator are not valid numbers in Portuguese and Italian. These cultures use comma as decimal separator.
English and Spanish depending on variations would support either dot or comma, hence if a finer-grained locale is not specified, they try to support both formats.
You can find more info in this Discussion #2577.

**Comment by tellarin** [comment]
There are currently no plans to change the behaviour in languages that don't have variants with the different formats.
We can look into it and try to plan accordingly if needed. Please use this issue to discuss your scenario/requirements.
Thanks.
