### ISSUE TITLE
[PT DateTimeV2] 'dia' followed by digits is resolved incorrectly

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2601]
**Describe the bug**
In a construction like "dia 20 de junho", the resulting timex contains only the month.

**To Reproduce**
1. Create a pt-BR app and add a datetimeV2 entity type.
2. Test "Feche minha conta a partir do dia 20 de junho"
3. The resulting timex will be "XXXX-06" (missing the day)
4. Test the string with "dia" removed
5. The resulting timex will be "XXXX-06-20" (correct)

**Expected behavior**
The timex should include both the month and day: "XXXX-06-20"

**Platform (please complete the following information):**
 - Platform: 
 - Environment: in browser
 - Version of package: ?

**Comment by tellarin** [comment]
@LionbridgeCSII, can you take a look at this one?
