### ISSUE TITLE
[PT, FR DateTimeV2] Incorrectly splitting weekday from date

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2605]
**Describe the bug**
When a weekday and date appear together, they are returned as separate dates, e.g. "Mon prochain salaire sera le 25 Mardi"

**To Reproduce**
1. Create an FR or PT app with datetimeV2
2. Test "Mon prochain salaire sera le 25 Mardi" for FR or "meu próximo salário será terça-feira dia 25" for PT
3. The result will be two timex values: "XXXX-WXX-2" and "XXXX-XX-25"

**Expected behavior**
The result should be a single date timex (e.g. for ES, "el martes 25" returns the timex "XXXX-WXX-2" and it resolves to "2020-08-25" and "2021-05-25", which are both Tuesdays).

**Platform (please complete the following information):**
 - Platform: 
 - Environment: in browser
 - Version of package: ?

**Comment by tellarin** [comment]
"meu próximo salário será terça-feira 25" should also be supproted.

**Comment by srandal** [comment]
The test case above succeeds when September 2018 is set as the reference date, because in that month the 25th fell on a Tuesday. When the reference date is a month that doesn't contain the specified date/weekday combination, the weekday-date split still happens. A weekday-date combination that doesn't occur in the current month is somewhat of an edge case though.
