### ISSUE TITLE
[Java] Support for italian language 

### ISSUE THREAD

**Issue by mattiapoli-quix** [microsoft/Recognizers-Text#2630]
Hi,

is there a plan or roadmap when approximately the java package also supports the Italian culture?
Thanks!

**Comment by tellarin** [comment]
Hi @mattiapoli-quix,
unfortunately porting Italian support to Java is not yet in the roadmap due to limited resources. Would you be interested in contributing support for it?

I'll close this issue, but let's use it to further discuss this topic if you want.

**Comment by mattiapoli-quix** [comment]
hi @tellarin,
yes i'm interested in contributing . Can you give me some advice on how to start to implement this? 
Also how long would it take to do that?
