### ISSUE TITLE
[EN Number|DateTimeV2] Incorrect parsing of period mentions like 'last two quarters'

### ISSUE THREAD

**Issue by kashyap-aditya** [microsoft/Recognizers-Text#2656]
**Describe the bug**
"Last two quarters" is incorrectly parsed as 0.5.
"Last 2 quarters" works fine and gives a value of 2.

**To Reproduce**
import * as Recognizers from '@microsoft/recognizers-text-suite';
Recognizers.recognizeNumber('last two quarters', culture); -> bug
Recognizers.recognizeNumber('last 2 quarters', culture); -> works fine

**Expected behavior**

**Sample input/output**
Result should be 2

**Platform (please complete the following information):**
 - Platform: javascript 
 - Version: 1.3.0

**Comment by tellarin** [comment]
This problem goes beyond JavaScript and just Number. Number is over parsed incorrectly in "last two quarters", but both cases are also not properly recognized as DateTime ranges ("last quarter" behaves as expected).

**Comment by aitelint** [comment]
working on this
