### ISSUE TITLE
[ES Currency] Incorrect value returned for compound currency entity in ES-MX

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2670]
**Describe the bug**
For a compound currency entity, the entity and units are identified correctly, but the value is missing a decimal.

"15 dólares y 15 centavos" Returns units = "Dólar" but value = "1515" instead of "15.15"

**To Reproduce**
Create an es-mx LUIS app and test the above text.

**Expected behavior**
type: "money"
units: "Dólar"
value: "15.15"

**Sample input/output**
type: "money"
units: "Dólar"
value: "1515"

**Additional context**
This only affects es-mx. 
In es-es, the same example produces "15.15"

**Comment by tellarin** [comment]
We can't replicate this issue. The correct output is produced in both es-ES and es-Mx.
Where did you see this behaviour and in which version of the packages?
You can test the current behaviour using the SimpleConsole project in the repo.

**Comment by srandal** [comment]
I originally saw the behavior while testing a LUIS app in the Azure web interface.

To determine whether it was a Recognizers issue or related to LUIS post-processing, I tested es-ES in SimpleConsole and got the expected output, but I don't know how to test es-MX:
If I just set DEFAULT_CULTURE to 'es-mx' in sample.py, the behavior appears to default to en-US. (It recognizes '15 dollars' as a currency but not '15 dólares'.)

**Comment by tellarin** [comment]
@srandal, you should use the .NET version of SimpleConsole. LUIS utilizes the .NET packages.

**Comment by srandal** [comment]
Good to know -- thanks
