### ISSUE TITLE
Question about language detection

### ISSUE THREAD

**Issue by Mousaka** [microsoft/Recognizers-Text#2678]
### Question
Is there any function included in this project that can determine the "Culture"/language of a text?

I want to use this project to find dates in texts but I need to provide "Culture" which in my case is not known for the string since my texts are of mixed languages.

Cheers!

**Comment by tellarin** [comment]
@Mousaka, unfortunately that's outside the scope of this project. You'd have to call some service like Text Analytics (https://docs.microsoft.com/en-us/azure/cognitive-services/Text-Analytics/how-tos/text-analytics-how-to-language-detection) or another open source library that implements language detection.

**Comment by Mousaka** [comment]
I was suspecting that answer. This project is still doing so much awesome stuff. I will probably try out the text-analytics service for my project.
@tellarin Thanks a lot for answering! :)

**Comment by tellarin** [comment]
@Mousaka Feel free to "star" the project, fi you haven't yet. :-)
And please report any issues you find. Thanks.
