### ISSUE TITLE
[EN Number] Support written negative numbers

### ISSUE THREAD

**Issue by tellarin** [Microsoft/Recognizers-Text#269]
negative one
minus thirty-two
"minus three point five"

In English and Chinese.

**Comment by STayinloves** [comment]
It seems that Chinese already has its negative numbers("负三十二“ etc) in its own [parser](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.Number/Chinese/Parsers/ChineseNumberParser.cs#L419). But the English use the `BaseNumberParse` and doesn't have a negative numbers implement.
So should we implement this by creating a specific `EnglishNumberParser` for English or in the `BaseNumberParse`?

**Comment by tellarin** [comment]
Edited the title as support for Chinese is already there.

**Comment by tellarin** [comment]
Reopening as the original implementation had to be reverted due to perf reasons (https://github.com/Microsoft/Recognizers-Text/pull/368).

**Comment by tellarin** [comment]
Perf of latest PR is much better.
