### ISSUE TITLE
[* Number|Unit] Tokenization of elements in the middle of digit/character sequence is not correct

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2692]
**Describe the bug**
having a sequene like 24703L202 the toeknization detects 24703 L as an extraction of Liters which is not correct since the sequence shouldn't be divided

**Expected behavior**
Nothing should be detected

**Comment by nawanas** [comment]
this also applies to USD115 where it should recognize this as a currency despite missing the space

**Comment by aitelint** [comment]
working on this
