### ISSUE TITLE
[FR DateTimeV2] Misses dates that are surrounded by specific words.

### ISSUE THREAD

**Issue by Mousaka** [microsoft/Recognizers-Text#2708]
**Describe the bug**
Some combinations of dates with words such as "avant", "et", "maintnent" makes RecognizeDateTime miss some results.

**To Reproduce**
1. Call `DateTimeRecognizer.RecognizeDateTime("Avant. JEUDI 3 JUIN 12h55. LUNDI 14 JUIN. Et. Maintenant.", "French")`.
2. There is no trace of any dates for "14 JUIN" in the result.

**Expected behavior**
Expect to find dates "XXXX-06-03T12:55" and "XXXX-06-14" among the results.

**Sample input/output**
Input: `"Avant. JEUDI 3 JUIN 12h55. LUNDI 14 JUIN. Et. Maintenant."`

Output:
```F#
  seq
    [Microsoft.Recognizers.Text.ModelResult
       {End = 55;
        Resolution = dict
                       [("values",
                         seq
                           [dict
                              [("timex",
                                "(XXXX-06-03T12:55,PRESENT_REF,PT2043H)");
                               ("type", "datetimerange");
                               ("start", "2021-06-03 12:55:00");
                               ("end", "2021-08-27 16:06:55")]])];
        Start = 0;
        Text = "avant. jeudi 3 juin 12h55. lundi 14 juin. et. maintenant";
        TypeName = "datetimeV2.datetimerange";}]
 ```

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: nuget package
 - Version of package:  "Microsoft.Recognizers.Text.DateTime" Version="1.8.0"

**Additional context**

Small modifications to the input like removing "maintenent" or "avant" gets you to expected behaviour.

The example text comes from a text in a flight info email where all the words from the example input exist but are part of a bigger text with information about check-in baggage, flight dates, and things such as "...before your departure...".
The same problem occurs when using the full text.

### Bonus
A code test in F# that is not passing

```F#
test """
          Given a message in french that includes a dateTime and a date
          And the words 'Avant' (before), 'Et' (and), 'Maintenant' (now)
          When processed
          Then we should get both the dateTime and date
          """ {
              let longerVersion =
                  "Nous vous recommandons de bien vérifier les formalités obligatoires avant votre départ. JEUDI 3 JUIN 12h55. LUNDI 14 JUIN. Nombre estimé de Miles et de XP liés à votre billet et aux options éventuellement achetées. Réservez en ligne dès maintenant et bénéficiez de réductions."

              let shortVersion =
                  "Avant. JEUDI 3 JUIN 12h55. LUNDI 14 JUIN. Et. Maintenant."

              DateTimeRecognizer.RecognizeDateTime(shortVersion, "French")
              |> List.ofSeq
              |> List.collect
                  (fun (modelResult: ModelResult) ->

                      (if modelResult.Resolution <> null then
                           modelResult.Resolution.["values"]
                           :?> seq<System.Collections.Generic.Dictionary<string, string>>
                       else
                           seq [])

                      |> Seq.toList
                      |> List.map (fun valueDict -> valueDict.Item "timex"))
              |> Expect.containsAll "" [ "XXXX-06-03T12:55"; "XXXX-06-14" ]
          }
 ```

**Comment by nawanas** [comment]
this is specific to Avant, actually other words including Avante do work and resolve all the dates

**Comment by tellarin** [comment]
@aitelint, let's add this one to the stack.

**Comment by aitelint** [comment]
working on this
