### ISSUE TITLE
[DE Number]  'fünfzehn' missing in german text-number extractor

### ISSUE THREAD

**Issue by skyw4lker** [microsoft/Recognizers-Text#2710]
Class GermanNumeric.java is missing 'fünfzehn' with an umlaut in addition to 'fuenfzehn' in static member TenToNineteenIntegerRegex. 

Expected response would be:
"start":0,"typeName":"number","end":7,"text":"fünfzehn","resolution":"15"

Actual result:
empty

Run a query
NumberRecognizer.recognizeNumber("fünfzehn", "de-de"); 

 - Platform: Java

**Comment by nawanas** [comment]
the term for fifteen, including fifteen hundred are not detected (actually fifteen hundred is detected as a datetime)
