### ISSUE TITLE
[* Currency] Recognition of currency value when using [currencyname]$ (e.g. USD$) 

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2711]
USD$ 115 is detected as currency but the value is returned as Null, where it should return the value of 115.  

the value is detected with USD 115 and $ 115

**Comment by nawanas** [comment]
Adding MXN$ to this issue specifically and generalizing to all Dollar currencies

**Comment by tellarin** [comment]
Workaround merged. But I'd leave this issue open, as a proper fix is needed.

**Comment by LionbridgeCSII** [comment]
looking into this

**Comment by nawanas** [comment]
> looking into this

this has already been fixed

**Comment by tellarin** [comment]
> > looking into this
> 
> this has already been fixed

Not really. There is a mitigation in place for a couple case, but we need a more general soluton an many currency codes can appear alongisde $, like BRL$. 

The positioning of the space is also a potential issue (BRL$20 vs BRL$ 20 vs BRL $20), though I think this is secondary and should only be addressed if there's a solution that doesn't negatively impact perf.
