### ISSUE TITLE
[DE DateTimeV2] nächstem Jahr/letztem Jahr

### ISSUE THREAD

**Issue by jinjoo-ha** [microsoft/Recognizers-Text#2718]
**nächstem Jahr** should return next year and **letztem Jahr** should return last year.

![image](https://user-images.githubusercontent.com/76481987/134304139-c60efe34-f59a-4d16-841b-d87fa0e00348.png)
![image](https://user-images.githubusercontent.com/76481987/134302894-51a84d3f-f018-457e-a777-59046767d9ea.png)

I had a look at the German-DateTime.yaml file, and it seems 'm' is missing in the optional character for Next/Previous Prefix.

I would appreciate if you could have a look and fix this.

Thank you.

Best Regards,
Jinjoo

**Comment by tellarin** [comment]
@jinjoo-ha Thanks for the feedback and the ping. 
I'm able to help from time to time and I'm pushing a fix for this one right now. But @nawanas is the person responsible for the team working on feedback/bug-fixing.
Please also tag him in future issues, ok?
