### ISSUE TITLE
[DE DateTimeV2] am 2. Weihnachtsfeiertag

### ISSUE THREAD

**Issue by jinjoo-ha** [microsoft/Recognizers-Text#2719]
**am 2. Weihnachtsfeiertag** should return 26th December, but it returns 2nd day of current month and next month, and 25th December.

Could you please fix it so that this only returns 26th December?

Thank you in advance.

Best Regards,
Jinjoo

**Comment by tellarin** [comment]
@nawanas, can you prioritize this?

**Comment by tellarin** [comment]
There was actually a simple change missing in the Holiday regex. Pushing the change soon.
