### ISSUE TITLE
Support for angles of rotation

### ISSUE THREAD

**Issue by tomconte** [microsoft/Recognizers-Text#2722]
**Is your feature request related to a problem? Please describe.**

We are using LUIS to implement voice commands for robot control. We would like to be able to understand sentences like "rotate 90 degrees" or "turn left 45 degrees". 

**Describe the solution you'd like**

Ideally the angle of rotation would be recognised and returned as a dimension, like length units. For our use case we probably only need to support degrees, but another useful unit would be a "turn", as in "make a half-turn" or "rotate half a turn"... Other applications might want to support radians.

**Describe alternatives you've considered**

We are currently getting the angle of rotation from a number entity, with no indication of the unit. We just assume that the angle is expressed in degrees.

**Comment by aitelint** [comment]
working on this
