### ISSUE TITLE
[ZH Number] When the number string is long the extraction take a long time

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2747]
**Describe the bug**
When trying a long string of number, "发议时，订单号 A202107211321363588510367 可用作" the extraction takes a long time, the longer the number the longer the time. 

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: Console app
 - Version of package v1.8

**Comment by AhmedLeithy** [comment]
Investigated this issue in more details and found the following pieces of information:

- I've tested similar input in different languages including German, Arabic, Korean, and Japanese. No other languages experience similar slowdowns with long numbers. 

- This issue persists even if the digits are in Chinese.

- The slowdown depends on the length of the number part of the query. The longer the number (bigger), the slower our recognizers are. This applies in the cases for both Chinese digits and English digits within a Chinese sentence. The slowdown is unaffected by the length of the irrelevant parts of the query.

- For English digits within a Chinese sentence (like the example in the issue), changing the `NumberExtractor's` number mode in [ChineseNumberWithUnitExtractor Configuration](https://github.com/microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Extractors/ChineseNumberWithUnitExtractorConfiguration.cs) to `CJKNumberExtractorMode.Default` solves the slow down issues. Currently this mode is set to `CJKNumberExtractorMode.ExtractAll`, which results in a single match for each digit within the number; which I hypothesized is the reason for the slow down.
  - The two recognizers that caused this slowdown for the example provided in the issue (english digits) are the `DateTimeRecognizer `and the `NumberWithUnitRecognizer.RecognizeCurrency`
  
  - The `CJKNumberExtractorMode.Default` change has no effect when the digits in the query are in Chinese. The slow down persists.
  
  - Unsurprisingly, there is a regression for the Numbers with Unit tests when the  ChineseNumberWithUnitExtractor configuration is changed to use a the CJKNumberExtractorMode.Default number mode. This is the only recognizer with regressions.

The following remain to be investigated:

- Which recognizers cause the slowdown when the numbers are in chinese? (it is not the same as when the characters are in English)
- What is the behavior of the regex matching in the Chinese numbers case? Does it also match each digit into its own regex match? Is this the reason for the slowdown?

**Comment by aitelint** [comment]
working on this
