### ISSUE TITLE
[ES DatetimeV2] Numeric month not recognized

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2749]
**Describe the bug**
One fairly common way to express a date in spoken Spanish is "\<day number\> de \<month number\> de \<year\>".
Recognizers fails to recognize the month portion of that transcribed speech.

**To Reproduce**
1. Run SimpleConsole for es-es
2. Type '9 de 8 de 1971'
3. The only datetimeV2 returned will be a daterange representing the year 1971. The month and day numbers are only returned as integer entities.

**Expected behavior**
Return the date "1971-09-08"

**Sample input/output**
9 de 8 de 1971

I found the following entities (4):
{
  "Text": "9",
  "Start": 0,
  "End": 0,
  "TypeName": "number",
  "Resolution": {
    "subtype": "integer",
    "value": "9"
  }
}
{
  "Text": "8",
  "Start": 5,
  "End": 5,
  "TypeName": "number",
  "Resolution": {
    "subtype": "integer",
    "value": "8"
  }
}
{
  "Text": "1971",
  "Start": 10,
  "End": 13,
  "TypeName": "number",
  "Resolution": {
    "subtype": "integer",
    "value": "1971"
  }
}
{
  "Text": "1971",
  "Start": 10,
  "End": 13,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "1971",
        "type": "daterange",
        "start": "1971-01-01",
        "end": "1972-01-01"
      }
    ]
  }
}

**Platform (please complete the following information):**

- Platform: .NET
- Environment: console app
- Version of package: 1.7.0

**Comment by aitelint** [comment]
working on this

**Comment by tellarin** [comment]
Please also add the equivalent support in PT.
