### ISSUE TITLE
[FR DatetimeV2] Year not recognized when month is spelled-out and "de" precedes the year

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2771]
**Describe the bug**
In a date expression where the month is spelled-out and "de" appears between the month and the year, the hypothesized timex excludes the year.

Note: French speakers tell us that this pattern is natural, although it's more common not to include "de".

**To Reproduce**
1. Run SimpleConsole for fr-fr
2. Type "Je suis né le 23 novembre de 1987"
3. The hypothesized timex will be "XXXX-11-23"

**Expected behavior**
The timex should be "1987-11-23"

**Sample input/output**
Je suis né le 23 novembre de 1987

I found the following entities (3):
{
  "Text": "23",
  "Start": 14,
  "End": 15,
  "TypeName": "number",
  "Resolution": {
    "value": "23"
  }
}
{
  "Text": "1987",
  "Start": 29,
  "End": 32,
  "TypeName": "number",
  "Resolution": {
    "value": "1987"
  }
}
{
  "Text": "23 novembre",
  "Start": 14,
  "End": 24,
  "TypeName": "datetimeV2.date",
  "Resolution": {
    "values": [
      {
        "timex": "XXXX-11-23",
        "type": "date",
        "value": "2020-11-23"
      },
      {
        "timex": "XXXX-11-23",
        "type": "date",
        "value": "2021-11-23"
      }
    ]
  }
}

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: console app
 - Version of package: 1.7.0

**Comment by tellarin** [comment]
@aitelint Can you take a look at this? Should be similar to a past fix.
