### ISSUE TITLE
[ES Number] Large number expressed as a fraction not recognized correctly

### ISSUE THREAD

**Issue by srandal** [microsoft/Recognizers-Text#2786]
**Describe the bug**
When a large number is expressed as a fraction, e.g. "1 millón y medio", only the first part is recognized as a number.

**To Reproduce**
1. Run SimpleConsole for es-us
2. Type "1 millón y medio"
3. The hypothesized number will have a value of "1000000" (ignoring "y medio")

**Expected behavior**
The hypothesized number should be "1500000"

**Sample input/output**
1 millón y medio

I found the following entities (1):
{
  "Text": "1 millón",
  "Start": 0,
  "End": 7,
  "TypeName": "number",
  "Resolution": {
    "subtype": "integer",
    "value": "1000000"
  }
}

**Platform (please complete the following information):**
- Platform: .NET
- Environment: console app
- Version of package: 1.7.0

**Comment by aitelint** [comment]
working on this
