### ISSUE TITLE
recognize such phrase  every July 4th 15:00 as a repetitive datetime as a repetitive reminds

### ISSUE THREAD

**Issue by helperAI** [microsoft/Recognizers-Text#2794]
Keyword "every" is not recogized as a repetitive datetime results.
If I want to build a remind recognizer, how can I solve this problem with the package. 
thanks.

**Comment by nawanas** [comment]
the repetition is captured as a set, and is left not resolved unless it is defined by the statement. Specifically your example would produce the following output
{
  "Text": "every july 4th at 3pm",
  "Start": 0,
  "End": 20,
  "TypeName": "datetimeV2.set",
  "Resolution": {
    "values": [
      {
        "timex": "XXXX-07-04T15",
        "type": "set",
        "value": "not resolved"
      }
    ]
  }
}

indicating that this is the 4 july at T = 15:00 and is a set (so it is more than one value. The actual resolution of this to a specific starting date is left to the use case that you are implementing
