### ISSUE TITLE
[EN DateTimeV2] "AMA tomorrow at 4pm CST. Join our Telegram for details!" causes a offset of -10000 which is not valid and more than 

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2795]
pretty much the issue is in the title, it should not be -10000

**Comment by tellarin** [comment]
This behaviour is by design. CST is an ambiguous timezone abbreviation (Central Standard Time or China Standard Time) and for such cases the recognizers don't have context to give a resolution. As such, the timezone offsets are XX:XX and -1000, meaning it can't be resolved directly.

**Comment by tellarin** [comment]
There's an item on the backlog to return multiple alternatives, but this currently has low priority.
