### ISSUE TITLE
[EN DateTimeV2] Incorrect daterange resolution

### ISSUE THREAD

**Issue by stevengum97** [Microsoft/Recognizers-Text#280]
This is a two-part (three-part?) issue; a user indicated via this [**post**](https://stackoverflow.com/questions/48325506/luis-prebuilt-entity-datetimev2-resolves-wrongly-date-range) on StackOverflow that they were getting an incorrect resolution from LUIS for the utterance, `"From Friday the 26th until Tuesday the 30"`.  The result from LUIS is the following:

```js
"entities": [
{
  "entity": "from friday the 26th until tuesday",
  "type": "builtin.datetimeV2.daterange",
  "startIndex": 0,
  "endIndex": 33,
  "resolution": {
    "values": [
      {
        "timex": "(2018-01-26,XXXX-WXX-2,P-2.33532467143519D)",
        "type": "daterange",
        "start": "2018-01-26",
        "end": "2018-01-23"
      }
    ]
  }
}
]
```

1. The entire utterance was not extracted, `"the 30th"` was not included in the entity.
2. LUIS should have defaulted to a Tuesday past the identified start date as opposed to defaulting to a Tuesday closer to present day.

___

Lastly, there was the peculiarity of the period returned which was not returned in a whole number. I was able to reproduce the above result with the exception of the period which changed to -2.003699744125 with `timezoneOffset=0`. 

Testing the utterance `"from Jan 23 to Jan 26"` had a period resolution of 3 days. Which seems to be a more logical format considering the comparison of days.

```js
{
  "entity": "from jan 23 to jan 26",
  "type": "builtin.datetimeV2.daterange",
  "startIndex": 0,
  "endIndex": 20,
  "resolution": {
    "values": [
      {
          "timex": "(XXXX-01-23,XXXX-01-26,P3D)",
          "type": "daterange",
          "start": "2017-01-23",
          "end": "2017-01-26"
      },
      {
          "timex": "(XXXX-01-23,XXXX-01-26,P3D)",
          "type": "daterange",
          "start": "2018-01-23",
          "end": "2018-01-26"
        }
      ]
    }
  }
```

**Comment by tellarin** [comment]
Thanks for the detailed report, @stevengum97! 
Can you add the SO link here for extra context too?

**Comment by stevengum97** [comment]
No problem! I've edited the original post to include the link, and the link can be found **[here](https://stackoverflow.com/questions/48325506/luis-prebuilt-entity-datetimev2-resolves-wrongly-date-range)** as well.

**Comment by tellarin** [comment]
@stevengum97, this has been fixed now and is on the pipeline for release. Closing the issue.
Thanks!
