### ISSUE TITLE
[* DateTimeV2] Dec 22 20:00 UTC+8 does not resolve the date part, only time

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2812]
Dec 22 20:00 UTC+8 will only create time piece and not the date part

**Comment by nawanas** [comment]
{
  "Text": "dec 22 20:00",
  "Start": 0,
  "End": 11,
  "TypeName": "datetimeV2.datetime",
  "Resolution": {
    "values": [
      {
        "timex": "XXXX-12-22T20:00",
        "type": "datetime",
        "value": "2020-12-22 20:00:00"
      },
      {
        "timex": "XXXX-12-22T20:00",
        "type": "datetime",
        "value": "2021-12-22 20:00:00"
      }
    ]
  }
}

this is the response that comes back, it does bring both the date and time

**Comment by tellarin** [comment]
@zoinkydoink Where do you see this issue? I just tried it in different configs and it is processed correctly.
@nawanas had not enabled Timezone in his test.

**Comment by tellarin** [comment]
"Resolution": {
    "values": [
      {
        "timex": "XXXX-12-22T20:00",
        "type": "datetime",
        "timezone": "UTC+08:00",
        "timezoneText": "utc+8",
        "utcOffsetMins": "480",
        "value": "2021-12-22 20:00:00"
      },
      {
        "timex": "XXXX-12-22T20:00",
        "type": "datetime",
        "timezone": "UTC+08:00",
        "timezoneText": "utc+8",
        "utcOffsetMins": "480",
        "value": "2022-12-22 20:00:00"
      }
    ]
  }

**Comment by zoinkydoink** [comment]
I must have made a mistake in my testing, because i tested it again and it seems to work as you have pointed out.

**Comment by zoinkydoink** [comment]
False alarm, ran my tests multiple time again and it seems to work as  you say, apologies

**Comment by tellarin** [comment]
No worries. Thanks for double checking.

**Comment by J053Fabi0** [comment]
Excuse me, but how can I enable Timezone?

Here is my code

```ts
const m = new DateTimeRecognizers.DateTimeRecognizer(Recognizers.Culture.Spanish).getDateTimeModel();

console.log(m.parse("hoy UTC+8")[0]?.resolution?.values[0].value);
console.log(m.parse("este jueves UTC+8")[0]?.resolution?.values[0].value);
```

It is not taking in mind the UTC+8 part, it's getting the timezone from my current machine.
