### ISSUE TITLE
[EN Number] "a current" or similar phrases determined as ordinal detected as a number fraction 

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2826]
**Describe the bug**
The phrase "'I was a current student last semester" would detected current and last as ordinals, as well as "a current" as a number fraction. (The same would apply if a precedes "last" This is not a correct resolution to this term. This applies to all languages with RelativeOrdinalRegex defined 

 - Version of package v1..8.2]

**Comment by tellarin** [comment]
Seems similar to #2690
