### ISSUE TITLE
[* Number] Relative Ordinal not complete across languages

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2827]
RelativeOrdinal has discrepancies across the different languages that needs to be unified. It is fully defined in EN, and partially defined, but not matching all the items in IT, JP,  DE, HI, KO, SW, TR. It is totally missing in the remaining supported languages.

**Comment by aitelint** [comment]
working on this

**Comment by tellarin** [comment]
@aitelint reopening issue as @nawanas mentioned some partial coverage in the other languages, but I'm not sure of the details.

**Comment by tellarin** [comment]
@nawanas, can we close this now?

**Comment by nawanas** [comment]
yes it could be closed
