### ISSUE TITLE
[DE DateTimeV2] Test case "Tag der Arbeit, ersten Weihnachtsfeiertag, zweiten Weihnachtstag" not correctly recognized

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2829]
The test case "Tag der Arbeit, ersten Weihnachtsfeiertag, zweiten Weihnachtstag" is not recognized correctly with the addition or relative ordinal in DE

the test case is missing 
{
  "Text": "ersten",
  "Start": 16,
  "End": 21,
  "TypeName": "ordinal",
  "Resolution": {
    "offset": "1",
    "relativeTo": "start",
    "value": "1"
  }
}
{
  "Text": "zweiten",
  "Start": 43,
  "End": 49,
  "TypeName": "ordinal",
  "Resolution": {
    "offset": "2",
    "relativeTo": "start",
    "value": "2"
  }
}

it needs to be added and consistent

**Comment by tellarin** [comment]
@nawanas Where do you see the datetime error? All three holidays work correctly in the recognizers.
Relative ordinal doesn't exist in German per se, as in the other issue you've opened.

**Comment by nawanas** [comment]
it seems to be blocking the build on many occasions, i guess to your point the datetime recognition is correct but for some reason it fails in build every second time
