### ISSUE TITLE
[* DateTimeV2] "HH h MM" or "HHhMM" time format not extracted

### ISSUE THREAD

**Issue by stevengum97** [Microsoft/Recognizers-Text#284]
A customer reports that the format "HH h MM" or "HHhMM" is not being properly extracted. An example of this format would be `"14h05"` which is 14:05 or 2:05 PM.

Reference Links:
- [The LEAF Project: L'Heure Officielle](http://www.leaflanguages.org/french-vocabulary-telling-time-the-24-hour-clock-lheure-officielle/)
- [Wikipedia: Date and time notation in France](https://en.wikipedia.org/wiki/Date_and_time_notation_in_France) (Stub Article)

**Comment by stevengum97** [comment]
@matthewshim-ms, can you take a look at this?

**Comment by stevengum97** [comment]
@tellarin, this might not be a French specific issue, but I'm having a difficult time finding a Microsoft stance on this format. I've found a [reference](https://www.ibm.com/support/knowledgecenter/en/SSHEB3_3.4.1/com.ibm.tap.doc/loc_topics/c_custom_date_formats.html) for IBM that does list this format (table 2, row four).

**Comment by tellarin** [comment]
@stevengum97 You're right, this is not French-specific. We can add support for this format across languages. I've edited the title and we'll plan it.

**Comment by stevengum97** [comment]
Thanks @tellarin!
