### ISSUE TITLE
[EN DateTimeRange] "Rating where year is greater than 2015" doesn't recognize a ">2015" DateTimeRange

### ISSUE THREAD

**Issue by gooooloo** [microsoft/Recognizers-Text#2840]
**Describe the bug**
"Rating where year is greater than 2015" doesn't recognize a ">2015" DateTimeRange.
While "Rating where year greater than 2015" (**without** the "is" word) does, and "Rating where year is after 2015" also does.

**Expected behavior**
"Rating where year is greater than 2015" should recognize a ">2015" DateTimeRange.

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: source code, commit fdee90fae3ceac501a11b13650a3da472bc9e53a

**Additional context**
It is because the regex in https://github.com/microsoft/Recognizers-Text/blob/1c72c994fafd6e8ab77576861dd6608772c187d0/.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs#L250 does recognize "year greater than 2015" and "after 2015", but doesn't recognize "year is greater than 2015".

**Comment by tellarin** [comment]
@aitelint Can you take a look?
