### ISSUE TITLE
The Korean parser uses Simplified Chinese. Why?

### ISSUE THREAD

**Issue by nameofSEOKWONHONG** [microsoft/Recognizers-Text#2862]
**Describe the bug**
[.NET]
The Korean parser uses Simplified Chinese. Why?

**To Reproduce**
/Microsoft.Recognizers.Text.DateTime/Korean/Parsers)/KoreanDateTimeParserConfiguration.cs
KoreanHolidayParserConfiguration.cs 
etc...
write datetime parser and check is chinese... why???
2. Type '....'
3. ....

**Expected behavior**
don't recognize korean text.

**Sample input/output**
[Korean]
오늘 내일

I found the following entities (1):
{
  "Text": "일",
  "Start": 4,
  "End": 4,
  "TypeName": "number",
  "Resolution": {
    "subtype": "integer",
    "value": "1"
  }
}

**Platform (please complete the following information):**
 - Platform:  .NET
 - Environment:  nuget package, console app
 - Version of package v1.8.2

**Comment by tellarin** [comment]
Korean DateTime is not yet available (you can see the supported types in the table in the main README in the repo). Some of the codebase is shared for CJK languages, but that Korean code path has not been finalized and is not currently enabled either. 
Korean DateTime support is currently planned tentatively to come out in the next 6 months. Any contribution is very welcome!
