### ISSUE TITLE
[PT Unit|Currency] Bugs reported from Speech 

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2882]
The following patterns are not working
1-	 Having the “Value Currency Multiplier” doesn’t work (e.g. 75 USD milhoes)
2-	Having “CurrencySuffixList” number (e.g. dólar 22,5 milhões, and dólar d 225000000) doesn’t match
3-	“um” is a pattern for micrometer, while it is also the number 1
4-	Currency fractions (e.g. 15 USD 50) doesn’t match to $15.50 while “15 dólares 50” does

these are required to comprehensively match combinations of expressing currency

**Comment by aitelint** [comment]
working on this
