### ISSUE TITLE
[PT Units] A few missing patterns are not supported

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2884]
Weight: Abbreviation of “toneladas” to “t” is not matching “1.450.000 toneladas de julio” “1.450.000 t de julio”
Area : Abbrevation of toneladas in “toneladas métricas” to “t métricas”
Distance: 4 polegadas recognized but 4 in is not
Speed: Abbreviation of milhas por hora to mi por hora (e.g. 188 mi por hora)
Age: 28 años not recognized as age (28 anos is correctly recognized)
Temperature: Space separating ° f doesn’t match

**Comment by tellarin** [comment]
"años" is not used in Portuguese, so this is not a valid issue.
The Farenheit case is already supported in the latest code in the repo.
The other issues should be easy to address.

**Comment by aitelint** [comment]
working on this
