### ISSUE TITLE
[PT DateTimeV2] Multiple issues coming from speech of datetime combinations not being properly interpreted

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2887]
1- expression “voltarei na segunda-feira 12/01/2016” extracts the date as well as the integers for segunda, while “Voltarei na segunda-feira 12 de janeiro de 2016” extracts is as one date (Monday Jan 12 2016)

2- expression [date] [hour] horas [am|pm] doesn’t recognize the hours “vou voltar em 14 de outubro 8 horas am” as well as [hout] horas [date] “vou voltar 19 horas 2016 − 12 – 22”. This also applies to daterange when you add horas after a lead or end time it doesn’t detect it “estarei fora de 4 horas a 5 pm 5 de maio 2018” only detects 5/5/2018 17:00 and not 5/5/2018 – 16:00-17:00

3- Days of the week not separated by commas are not detected “vamos nos encontrar na terça qua qui ou sexta” only identifies tues and wed, while “vamos nos encontrar na terça, qua, qui, ou sexta” identifies tues – Friday

4- Day of the month in text after a day is not detected “meu próximo salário será terça-feira dia vinte e cinco” does’t detect the day 25, while “meu próximo salário será terça-feira dia 25” detects this on the 25th 

5- Relative time to the hour, like “vou voltar as 15 para as 8 de amanhã” doesn’t produce a correct time (gets 20:00, and not 19:45), also “vou voltar amanhã 8 horas am” doesn’t detect the time. Also the expression “[time] e meia” doesn’t get recognized if time includes a space “8 pm” and not “8pm” or “8”. Also if time and relative time are not in the same form (text or numerials) it doesn’t fire, so “Voltarei as sete e trinta pm” works but “Voltarei as 7 e trinta pm” doesn’t  and “Voltarei as 7 e 30 pm” does

6- “vou voltar 8 pm da tarde um jan” typing the day ahead of the month doesn’t get recognized

**Comment by aitelint** [comment]
working on this
