### ISSUE TITLE
[ES Number] Missing support for a few units and abbreviations

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2888]
1-	docenas abbreviated to dz isn’t recognized as 10s
2-	mitad not recognized as half
3-	100 billonesimo, both 100 and 100 billion are recognized this applies to million 
4-	millón not recognized as million, plurals such as millonesimos, billionesimos etc. are both not recognized

**Comment by aitelint** [comment]
working on this
