### ISSUE TITLE
[ES DateTimeV2] Misc bugs generated from Speech

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2890]
1-	Pattern “week [number] of [year]” is not captured, such as “Estaré afuera en semana 3 de dos mil veintisiete” or “Estaré afuera en semana 3 de 2027”
2-	The pattern for hour being represented as 3:00 h is not recognized
3-	año hasta la fecha not detected as a year
4-	decade (decenios, / décadas) not detected
5-	quarterly (trimestral) not detected, 
6-	esta [year-type] ano is not detected, examples are “este escolar año” or “este calendario año”
7-	in the phrase “Voy a volver 7 del próximo domingo a la tarde: the extraction of the time doesn’t extend to the hour, unless the time is expressed as 7:00/7am or 7pm  (this also doesn’t resolve if the time is represented as 7 horas, or 7h 
8-	the holiday international workers day is not recognized
9-	expression “dos días después de hoy?” not identified as a relative time

**Comment by aitelint** [comment]
working on this
