### ISSUE TITLE
[NL Number] een misrepresented as 1 in different contexts

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2897]
“een” in the statement “Een verouderde benaming is voor nanometer is millimicron” is recognize as a number with value 1 while it isn’t a number it is the equivalent of a

**Comment by tellarin** [comment]
This is by design and considered not an issue. The same happens in multiple languages where the same word is used for "one" and "a". It's also ambiguous leveraging only sentence conrext and technically inerpreting as 1 is not really incorrect.
