### ISSUE TITLE
[NL DateTimeV2] Multiple issues from speech across date/time sub-types

### ISSUE THREAD

**Issue by nawanas** [microsoft/Recognizers-Text#2898]
1-	Space between the day and rd/th like “Ik ga 20 ste van de volgende maand terug” isn’t recognized as a date
2-	The expression “Ik ga terug vier dagen gerekend vanaf gisteren” is resolved as four days from today, but replacing the text with the digit four is not detected “Ik ga terug 4 dagen gerekend vanaf gisteren”.
3-	“Het zal 3 dagen vanaf dinsdag gebeuren”, “Het zal 3 dagen na de 12e januari gebeuren” not resolved correctly
4-	Replacing 1 with een in “week 1” is not detected, also the expression “Het gebeurde door een tijdsverschil van een seconde” both “eens” are resolves to the number 1 while only the latter is a number.
5-	Jan-feb detected as a range but not jan feb in the example  “APEC zal in Korea plaatsvinden jan-feb 2017”
6-	This afternoon not recognized, such as the statement “laten we koffie gaan drinken op gebouw 4 deze middag” 
7-	The pattern [dayoftheweek][relativeweek] is not captured, like “We ontmoetten elkaar op dinsdag van vorige week” resolves last week and Tuesday and not 
8-	Seconde is not captured in time, “Het gebeurde door een tijdsverschil van een seconde” doesn’t extract “een seconde” 
9-	Meals in the day not recognized “laten we rond het avondeten afspreken” “laten we na het ontbijt afspreken” or “laten we voor de lunch afspreken”
10-	Repeat cycles such as “Om de week vrijdag” “plan alsjeblieft een meeting voor de week beginnend op 4 feb” not captured, also muiltiples in the monthly cycle is not captured like “Plan een halfjaarlijkse vergadering in” and “Plan alsjeblieft een meeting halfjaarlijks in”, “Laten we ervoor zorgen dat dat elke weekdag gebeurt”
11-	Christmas not captured in the statement “welke beschikbare tijd dan ook om vandaag tijdens lunchtijd boodschappen te doen” , “welke films spelen er op Kerstavond om 18.00?”
12-	“Boek iets van de 26e juni van 2020 tot de 28e juni van 2020” not captured as a range (but captured as individual dates and the later is with a modifier (before)
13-	Relative time in the year not captured, like [beginning|late|middle] [Year] e.g. “Dit bedrijf werd gestart aan het begin van 2000”
14-	Holidays like labor day not captured in the example “Laten we de Dag van de Arbeid vieren”, Juneteenth “Juneteenth, wat ook bekendstaat als Vrijheidsdag en Jubilee Day, dateert terug tot 1865 en valt elk jaar op 19 juni”
15-	Weekend not captured at a datetime “Doe je dat elk weekend?”
16-	[Next] Easter is not captured in the phrase “Wanneer was de eropvolgende Pasen” while it is when using volgende
17-	Wrong range in the statements “Ik zal voor het einde van december teruggaan”, “ Ik zal teruggaan tegen het eind van deze maand”, and “Ik zal teruggaan voor het eind van dit jaar”, “De reeks is van 2007 tot het einde van 2008”, “Het is gesloten van april tot het einde van juni”
18-	Working week in “Het zal deze werkweek gebeuren” not resolved

**Comment by aitelint** [comment]
working on this
