### ISSUE TITLE
[* DateTimeV2] Time resolution not consistent across cultures.

### ISSUE THREAD

**Issue by aitelint** [microsoft/Recognizers-Text#2936]
Time resolution of certain time expressions in CJK implementation is not always consistent with standard implementation.

For example in DateTimePeriod: "今日の午後4時から明日の午後5時まで" (from 4pm today to 5pm tomorrow) resolves to "(2016-11-07T16:00:00,2016-11-08T17:00:00,PT25H)" while in standard implementation the resolution is "(2016-11-07T16,2016-11-08T17,PT25H)"

CJK should be made consistent with standard implementation.

**Comment by aitelint** [comment]
@tellarin, in standard DateTimePeriod when both sides contain a date the duration is rounded to the hour, e.g.
"between jan 12 at 4pm and jan 12 at 5.30pm" -> (XXXX-01-12T16,XXXX-01-12T17:30,PT2H).
Instead when only one date is present the duration is not rounded, e.g.
"jan 12 between 4pm and 5.30pm" -> (XXXX-01-12T16,XXXX-01-12T17:30,PT1H30M).

Should we fix this discrepancy or is it so by design?

**Comment by tellarin** [comment]
@aitelint This is indeed a bug. The non-rounded resolution is the correct one. Thanks for tracking it.
