### ISSUE TITLE
Supported Windows versions for the C#/.NET implementation?

### ISSUE THREAD

**Issue by jefgen** [microsoft/Recognizers-Text#2940]
I couldn't seem to find an easy answer to this, so filing an issue. :)

Is there a list of supported Windows versions for the C#/.NET implementation?
In other words, how far down-level does it work? Windows 7, 8, etc.?

Or is the intent to have the library be entirely self-contained -- and not call any platform APIs -- so it shouldn't really matter what Windows version as long as it has the .NET runtime.

Thanks!

**Comment by tellarin** [comment]
There are no platform-specific dependencies. For the .NET version, the min requirement is a OS that runs 4.6.2, as listed under targets for the NuGet packages (https://www.nuget.org/profiles/Recognizers.Text).
The min supported version may move up when v2.0 is released. Probably 4.7.*.

**Comment by jefgen** [comment]
Thanks for the reply!

For the second point: 
> is the intent to have the library be entirely self-contained -- and not call any platform APIs ?

Would there be any opposition to adding calls to platform specific APIs? (ex: platform APIs that might exist only on Win10 and above). Or is the intent of the library to be mostly self-contained and provide the same results everywhere?

**Comment by tellarin** [comment]
Ideally we'd like to have the recognizers be fully platform independent. But if there is significant value in some platform-specific approach, we can look into how to incorporate it as flexibly as possible.
