### ISSUE TITLE
[* DateTimeV2] Support for locale specific formats?

### ISSUE THREAD

**Issue by jefgen** [microsoft/Recognizers-Text#2941]
Currently support for Date/Time entity extraction seems to be on a *per-language* basis, rather than a *per-locale* basis.

Is there any way to add support for individual locales as well?
Or is this something that isn't supported (yet)?

I think it would work best in a hierarchical approach: in other words, first try a specific locale's model first, and then fallback to the parent language, if that didn't work and/or find anything.

The reason for this is that sometimes date/times are detected incorrectly depending on the locale.

For example, the locale `en-GB`, aka "English (United Kingdom)", uses date formats that follow the convention: `day / month / year`

However, if you try using the English culture with an input like "01 / 04 / 23" it will incorrectly detect this assuming an en-US style format of `month / day / year`.
(So it should be considered as "April 1, 2023", and not "January 4, 2023" for en-GB.)

Input: "01 / 04 / 23"
Output:
```
{
  "Text": "01 / 04 / 23",
  "Start": 0,
  "End": 11,
  "TypeName": "datetimeV2.date",
  "Resolution": {
    "values": [
      {
        "timex": "2023-01-04",
        "type": "date",
        "value": "2023-01-04"
      }
    ]
  }
}
```

Thanks!

**Comment by tellarin** [comment]
This is basically how the system works. You can see it in .NET. You pass it a culture and it will try to return a model that matches it the closest. If the direct match fails, it fallsback to the general language one, that tries to captures variances too, but has to prioritize a specific locale in ambiguous cases.

**Comment by jefgen** [comment]
Thank you for the reply and the information!

So in principal, would it be possible to add something like en-GB, in way that it would be applied "*on top of*" the general language model? (Mostly just to change some locale specific formats).

Or would the en-GB model need to be fully "complete" (ie: copy/replicate data from the general model into the specific) in order to work fully?

I'm mostly just trying to better understand if we'd be able to use this library, and how much work it would take to add support for several different locales.

**Comment by tellarin** [comment]
Yes, locale-specific changes are customizations on the base language model. Plus a set of specs to show the difference in behaviour and avoid future regressions.

**Comment by tellarin** [comment]
Please report any locale-specific issues you have seen or any other bugs or missing support. Thanks.
