### ISSUE TITLE
[* DateTimeV2] I case of YYYY entry presence in the parsed text the recognizer sometimes outputs incorrect results

### ISSUE THREAD

**Issue by Kajman55** [microsoft/Recognizers-Text#2960]
**Bug description**
In case the parsed text contains year value in the form YYYY (perhaps this is not an ehaustive case), the recognizer output deviates from the expected one.

**To Reproduce**
1. Setup the following input string for the recognizer:
 
            string sourceText = "DateTime search phrase\n23.04.2022 14:55\n30.04.2022 12:04";

2. Execute datetime recognizer as below:

            var msRecognizerResult = DateTimeRecognizer.RecognizeDateTime(sourceText, "de-de").ToList();

            Console.WriteLine();
            foreach (var rr in msRecognizerResult)
            {
                Console.WriteLine(rr.Text);
            }

            Console.ReadKey();

3. The Console will output:

           23.04.2022 14:55 
           30.04.2022 12:04

4. Repeat the same procedure but with the following input text:

           string sourceText = "DateTime search phrase\n23.04.2022 14:55\n30.04.2022 12:04 some text 2020";

5. The Console will output:

           2020

**Expected behavior**
In the second case the output should be:

           23.04.2022 14:55 
           30.04.2022 12:04
           2020

**Platform:**
 - Platform: .NET Framework 4.7.2
 - Environment: nuget package Microsoft.Recognizers.Text.DateTime
 - Version of package:  ver 1.8.4

**Additional context**
The issue might be connected with the following code place:

Class:         Microsoft.Recognizers.Text.DateTime.BaseMergedDateTimeExtractor
Method:    List\<ExtractResult\> FilterAmbiguity(List<ExtractResult> extractResults, string text) line 290 

changed in the commit 927c06361764d485bdabd0e0eb47694a08e40567

The new code modifies the 'extractResults' collection during its iteration.

**Comment by aitelint** [comment]
working on this
