### ISSUE TITLE
[Infra] Description has more than 350 characters and cannot be forked

### ISSUE THREAD

**Issue by fredatgithub** [microsoft/Recognizers-Text#3030]
**Describe the bug**
The description has more than 350 characters and cannot be forked.

**To Reproduce**
1. Fork the repo
2. See error

**Expected behavior**
the repo Recognizers-Text should be able to be forked.

**Comment by tellarin** [comment]
Thanks for the feedback. Description updated.

**Comment by fredatgithub** [comment]
thanks
