### ISSUE TITLE
[.NET][Bug]System.ArgumentException : An item with the same key has already been added. Key: Microsoft.Recognizers.Text.DateTime.DateTimeRecognizer

### ISSUE THREAD

**Issue by EvaRichie** [microsoft/Recognizers-Text#3093]
**Describe the bug**
Just the basic usage in AzureDevOps YAML pipeline with test case. 
`var res = DateTimeRecognizer.RecognizeDateTime(input, Culture.English);`
with the Test Case like below string item as input.
 - **1 jan 2020 for 3 days**
 - **1 feb 2020 for 3 days**
 - **mar 2020 for 3 days**
It will through the exception **System.ArgumentException : An item with the same key has already been added. Key: Microsoft.Recognizers.Text.DateTime.DateTimeRecognizer**

**To Reproduce**
This bug is **NOT** 100% preproduce.

**Expected behavior**
It should not throw exception.

**Sample input/output**
 - **1 jan 2020 for 3 days**
 - **1 feb 2020 for 3 days**
 - **mar 2020 for 3 days**

**Platform (please complete the following information):**
 - Platform:  .NET 7
 - Environment: nuget package 
 - Version of package 1.8.7

**Additional context**
![image](https://user-images.githubusercontent.com/9699415/231519787-7e4d6472-8da1-4fae-8fe3-191871b6be5e.png)

**Comment by CDirkx** [comment]
I can confirm I have encountered the same problem with the number recognizer. 

```csharp
NumberRecognizer.RecognizeNumber("honderddertien", Culture.Dutch) // Exception: "An item with the same key has already been added. Key: Microsoft.Recognizers.Text.Number.NumberRecognizer"
```

I'm also not able to reproduce it reliably.

Platform: .NET 6
Package version: 1.8.7

**Comment by fxs130430** [comment]
@EvaRichie, are you calling these types in different threads? Trying to find out if this is a thread-safety issue.
