### ISSUE TITLE
[* NumberRange] Bug in handling ranges like "1995 - 01"

### ISSUE THREAD

**Issue by tellarin** [Microsoft/Recognizers-Text#316]
Resolution is currently the interval "[1,1995)". 
Wouldn't it make more sense to assume both ends are as either open or closed? 
Also, would it make more sense if the interval can only be specified in the right order? I.e. 1-1995 is an interval, but 1995-1 is not?

**Comment by lucinezhang** [comment]
I think in math, 1 - 1995 means [1,1995)
