### ISSUE TITLE
[* Sequence] Support for full US phone number extraction

### ISSUE THREAD

**Issue by tellarin** [Microsoft/Recognizers-Text#324]

**Comment by STayinloves** [comment]
Should we just support the regex `@"(\+1)?\s?\(?\d{3}\)?\s?-?\s?\d{3}\s?-?\s?\d{4}\b"` and avoid the invalid situation?

**Comment by tellarin** [comment]
Numbers should match in full, and only in full. Also, no leading/trailing whitespaces.
