### ISSUE TITLE
[EN DateTimeV2] Analyze the desired behaviour of "in 3 days"

### ISSUE THREAD

**Issue by guom08** [Microsoft/Recognizers-Text#341]
Should it be date or daterange?
Test cases located in DatePeriodExtractor and DateTimeExtractor also need to be modified accrodingly

**Comment by tellarin** [comment]
"within" should be daterange.

**Comment by tellarin** [comment]
@STayinloves, this is the same case as you brought up.

**Comment by tellarin** [comment]
Behaviour has been standardized by Mu recently.
@guom08, please write it into the specification. Thanks!
