### ISSUE TITLE
[IT *] Is there Italian language support?

### ISSUE THREAD

**Issue by biapar** [microsoft/Recognizers-Text#354]
Is there italian language support?

**Comment by matthewshim-ms** [comment]
Currently, no.

**Comment by tellarin** [comment]
Hi @biapar, 

currently Italian is not supported in Microsoft/Recognizers-Text. It's on our plans, but no ETA yet. If you're interested in helping out, contributions are very welcome.

You can take a look at https://blog.botframework.com/2018/01/24/contributing-luis-microsoft-recognizers-text-part-1/ for some more info on the project structure. @matthewshim-ms can also help you if you have questions.

Thanks!

**Comment by tellarin** [comment]
Hi @biapar, 
@maurobennici has started a contribution for it.

**Comment by tellarin** [comment]
PR #789 merges the localized Italian specs and the skeleton of support.

**Comment by tellarin** [comment]
Italian support for Number is now in WIP (#1604) other types coming soon.

**Comment by tellarin** [comment]
Italian is now fully supported. v1 of the last model (DateTime) is now merged! All support will be out in nuget package v1.2.6, to be released in the next couple days.
