### ISSUE TITLE
Javascript "suite" package should have fixed major and minor dependencies

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#383]
The recognizers-text-suite package has out going ^ style dependencies. This can cause an application (or another package) to accidentally move to a higher version of the dependencies. This can break applications as it leaves them no control.

The out-going dependencies from recognizers-text-suite specified in its package.json should be fixed. Or at least ~ which would allow patches.

**Comment by johnataylor** [comment]
One implication (of using the ~) is that whenever you rev one of the child packages (major or minor rev) then you manually also rev the suite package. Although that might cause more suite packages to be published it does leave the consumer with the control. Is that correct?

**Comment by tellarin** [comment]
Yep. That's the idea.
We can also go with strictly fixing the children. Let's wait for Steve's feedback.

**Comment by tellarin** [comment]
@Stevenic, do you think ~ is a reasonable compromise or should we really push for the suite package to have fixed dependencies?

**Comment by tellarin** [comment]
@pcostantini, thoughts?

**Comment by Stevenic** [comment]
@tellarin I think `~` is probably fine.

**Comment by tellarin** [comment]
This has been updated and we'll release a new version of the npm packages next week to include many small fixes.
