### ISSUE TITLE
[EN DateTimeV2] "Later in the year" should be recognized as Q3/Q4 of this year

### ISSUE THREAD

**Issue by yaronism** [Microsoft/Recognizers-Text#395]
Later in the year, Later this year should be recognized as someone in the 3rd of 4th quarter of this year.

**Comment by tellarin** [comment]
We don't think this should be the general behaviour. Other users may have a different interpretation of "later in the year". 
A more general solution that allows devs to choose how to interpret it would be to still tag year, and annotate the entity with a modifier for "later".
Similar to what happens in mid-week. @yaronism, would that work for you?

**Comment by yaronism** [comment]
Agree. Is it supported now as we are working through LUIS.ai?
