### ISSUE TITLE
Unable to compile TypeScript sub-project

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/Recognizers-Text#416]
I am following the [published guides](https://blog.botframework.com/2018/01/24/contributing-luis-microsoft-recognizers-text-part-1/) trying to add (basic) support for the Dutch language, however I am facing an error while building the resources.

I did check if the path `/Users/mick/Projects/ms-projects/Recognizers-Text/JavaScript/packages/resource-generator` exists, however I can just cd into it and it exists. 
Anyone had similar issues on MacOS while generating resources? My fork is published [here](https://github.com/iMicknl/Recognizers-Text).

```bash
Micks-MBP:recognizers-number mick$ npm run build-resources

> @microsoft/recognizers-text-number@1.0.0 build-resources /Users/mick/Projects/ms-projects/Recognizers-Text/JavaScript/packages/recognizers-number
> ts-node --project ../resource-generator/ ../resource-generator/ ../recognizers-number/resource-definitions.json


/Users/mick/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/src/index.ts:453
        throw new TSError([formatDiagnostic(result.error, cwd, ts, 0)])
              ^
TSError: ⨯ Unable to compile TypeScript
The specified path does not exist: '/Users/mick/Projects/ms-projects/Recognizers-Text/JavaScript/packages/resource-generator'. (5058)
    at readConfig (/Users/mick/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/src/index.ts:453:15)
    at Object.register (/Users/mick/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/src/index.ts:209:18)
    at Object.<anonymous> (/Users/mick/.nvm/versions/node/v8.5.0/lib/node_modules/ts-node/src/bin.ts:100:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
```

**Comment by STayinloves** [comment]
The build-resource script has little problem, you can modify the script by specific the configuration of typescript projects.

For example, ts-node --project ../resource-generator/**tsconfig.json** ../resource-generator/ ../recognizers-number/resource-definitions.json

**Comment by iMicknl** [comment]
Great, that works indeed. Thanks for the quick reply. 
Should we leave this open as bug report or do you want to close it?

**Comment by STayinloves** [comment]
In fact, this is a known issue, but we can leave it opened here for tracking the progress.
