### ISSUE TITLE
[Bug] Date range recognition error

### ISSUE THREAD

**Issue by fanidamj** [Microsoft/Recognizers-Text#435]
This utterance "I want a room from 02 to 07 April" detects a date range entity "start": "2017-04-02" and "end": "2017-04-07". But this utterance "I want a room from 02 to April 07", despite the same, return a date entity "value": "2017-04-07"

**Comment by tellarin** [comment]
Hi @fanidamj,
can you describe what you're doing that the same sentence gets different results? We couldn't replicate that.

**Comment by tellarin** [comment]
Replicated now.

**Comment by tellarin** [comment]
@fanidamj The bug has been fixed and the fix will enter the release pipeline soon.
Thanks.
