### ISSUE TITLE
[DE DateTime] Entity type builtin.datetime does not contain any resolution

### ISSUE THREAD

**Issue by fanidamj** [Microsoft/Recognizers-Text#444]
As mentioned in the [issue](https://github.com/Microsoft/BotBuilder/issues/4422), there is no resolution for the recognized JSON entities in German language.

**Comment by tellarin** [comment]
Hi @fanidamj,

unfortunately builtin.datetime is not provided by Recognizers-Text. 

We're working on datetimeV2 for German, but no ETA yet. Hopefully soon. :)

I'll close the issue here as  it can't be solved by this project, ok?
