### ISSUE TITLE
[FR DateTimeV2] Hours duration wrongly recognized

### ISSUE THREAD

**Issue by thomasryck** [microsoft/Recognizers-Text#445]
Ex:
If I say: " Quelles sont les salles disponibles aujourd'hui pendant 2 heures ?" LUIS returns that "pendant 2 heures" is a time whereas it is supposed to be a duration . This issue only appears when you say "during X hours". This issue does not exist with other time units as minutes, seconds, days, months ...

**Comment by tellarin** [comment]
@matthewshim-ms could you take a look at this?
