### ISSUE TITLE
is there persian lang support?

### ISSUE THREAD

**Issue by ghost1372** [Microsoft/Recognizers-Text#449]
hi is there persian lang support? if no, how i can help you?

**Comment by tellarin** [comment]
Hi @ghost1372, 

unfortunately we currently don't cover it.

The links below provide an overview on how to add a new language:
* [Overview and language resources](https://blog.botframework.com/2018/01/24/contributing-luis-microsoft-recognizers-text-part-1/)
* [Implementing language specific behaviour](https://blog.botframework.com/2018/02/01/contributing-luis-microsoft-recognizers-text-part-2/)
* [Test specs and testing in general](https://blog.botframework.com/2018/02/01/contributing-luis-microsoft-recognizers-text-part-3/)

Feel free to ask if you have any questions. Any contribution is very welcomed!

Thanks.

**Comment by tellarin** [comment]
@ghost1372, I'll close this issue for now, ok?
Feel free to create new ones for any specific issues you find.
Thanks!
