### ISSUE TITLE
[FR DateTimeV2] Can not get hours duration

### ISSUE THREAD

**Issue by thomasryck** [microsoft/Recognizers-Text#450]
I have tried different syntax in order to get a duration in hour and I never managed to get one. Each time I do a request with a duration in hour as " pour 3 heures ", "pour une durée de 3 heures", I get as a result of the parsing a time or, depending on the context, a datetime which contain the duration. This issue only exist with hours from the different tests I did. I also think that the issue on duration provokes issue on datetime since when I say "le 17 pour 3 heures", the parsed entity is "17 pour 3 heures".  And I think that the parsing sould return a date and a duration and not a datetime.

**Comment by tellarin** [comment]
@LionbridgeCSII, please take a look at this one and try to fix/implement similarly to English.
