### ISSUE TITLE
[ZH NumberRange] No resolution in number range

### ISSUE THREAD

**Issue by wgx998877** [Microsoft/Recognizers-Text#453]
Example: 给我三到五个苹果
  {
    "Text": "三到五",
    "Start": 2,
    "End": 4,
    "TypeName": "numberrange",
    "Resolution": {
      "value": ""
    }
  }

Not resolution value in it

**Comment by STayinloves** [comment]
There are some ambiguous cases in Chinese in which numbers act as the adverb, so we set a whitelist to enable some normal expression. But the word "到" doesn't upon the list. If we add it to the list, we'll extract some weird words from some sentence. For example, "一到五" will be extracted from "我一到五台山就下车".

**Comment by wgx998877** [comment]
@STayinloves I remember there are a allow list in Chinese Number recognizer to avoid extract number like “四川”,"三国". Maybe that can help you to resolve this.
