### ISSUE TITLE
[FR DateTimeV2] No resolution in DateTimeRange

### ISSUE THREAD

**Issue by thomasryck** [microsoft/Recognizers-Text#456]
I have an issue with datetimerange and while pursuing some tests I found that the comportment of this sub type is strange.
If I say "le 17 de 14h à 16h" I get a datetimerange with no resolution.
If I say "le 17 de 14 à 16" I get a datetimerange with no resolution.
If I say "le 17 entre 14 et 16" I get a datetimerange with no resolution.
If I say "le 17 entre 14h et 16h" I get a date and a daterange which are correct.

**Comment by tellarin** [comment]
Thanks for reporting this. We'll triage soon.

**Comment by tellarin** [comment]
In this case, the correct output should be only one entity, not two as in your last example.
datetimerange 17/XX/XXXX from 14:00 to 16:00 
We have a fix for the four cases with this same output in the pipeline.

**Comment by tellarin** [comment]
@LionbridgeCSII, please take a look at this one and try to fix/implement similarly to English.
