### ISSUE TITLE
[EN Number] "between" should include bounds

### ISSUE THREAD

**Issue by RomainWilbert** [Microsoft/Recognizers-Text#492]
"between four and seven" => "(4,7)" meaning 4 and 7 are not included.

My understanding of between is that bounds are included to the interval

**Comment by RomainWilbert** [comment]
Including boundaries should be the default behavior. A flexible option would be to support "exclusive" or "inclusive" suffix to remove any uncertainty.

**Comment by RomainWilbert** [comment]
Maybe "from ... to ..." ranges should include end bound as well.

**Comment by tellarin** [comment]
Hi @RomainWilbert, thanks for bringing this up. We're doing issue triage and I'll update this issue later.

**Comment by tellarin** [comment]
For consistency, all ranges include the start and don't include the end.  Additional modifiers (MOD attribute) currently give further insight on what extra interpretation should be applied to the provided resolutions. 

This makes sure the recognizers are backwards compatible, provides a stable platform, and also let's consumers decide how to interpret in their particular scenarios (devs have better domain knowledge of their usage cases and no solution fits all).

If you find cases that deviate from the design, please open issues for them. They'd be very helpful.

Thanks for all the feedback!
