### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by KarimJedda** [Microsoft/Recognizers-Text#5]
Is there any documentation available?

**Comment by chrimc62** [comment]
We don't have any yet--we are working to build more recognizers to add, but we do have some resources to add documentation.  Were you looking for documentation on how to write new ones or use the existing ones?

**Comment by SivilTaram** [comment]
You could look up the unit test files for how to use it.

**Comment by tellarin** [comment]
Hi @KarimJedda, 
are the unit tests as example enough for what you need? Or are you looking for documentation on how to add new features?
We'll publish a spec soon that will help in the later case.

**Comment by KarimJedda** [comment]
Hello,

I ended up reading the code and porting some of it to Python. :3 
Thanks for the help people <3

**Comment by tellarin** [comment]
OK. Closing this issue then.
Please share the link to your python code. :)
