### ISSUE TITLE
[EN DatetimeV2] 11.05.2018 recognized like 2 DatetimeV2

### ISSUE THREAD

**Issue by SvartAlfe** [Microsoft/Recognizers-Text#509]
The text "11.05.2018" is recognized like :
datetimeV2 --> "2018"

And the text "on 11.05.2018" is recognized like :
datetimeV2 --> "11 . 05" 
datetimeV2 --> "2018"

I am also interested by the support for English regional formats. Those interested can vote for it here:
https://cognitive.uservoice.com/forums/551524-language-understanding-luis/suggestions/31549864-luis-add-support-for-english-regional-formats

**Comment by tellarin** [comment]
Support for date formats in dot-syntax is being improved in PR https://github.com/Microsoft/Recognizers-Text/pull/511, it should be merged in soon.
I'll close this issue for now.
