### ISSUE TITLE
[FR DateTimeV2] 2-digits year not interpreted

### ISSUE THREAD

**Issue by VincentGuigui** [Microsoft/Recognizers-Text#546]
18/08/78 => date should return 1978-08-18 and not XXXX-08-18
17/05/09 => date is correct and returns 2009-05-17 
02/04/78 => date should return 1978-04-02 and not XXXX-02-04 (this one is tricky as it also includes another symptom DD/MM inversion)

**Comment by tellarin** [comment]
Hi @VincentGuigui, this issue should already be fixed in the current repository and is already part of the latest module to be deployed. 
Can you still make it happen using the SimpleConsole in the project set to French?

**Comment by VincentGuigui** [comment]
Indeed it seems to be working in SimpleConsole.

Do you have estimated deployment schedule for this ?

Thanks

**Comment by tellarin** [comment]
If not out yet, it should roll out on Monday.
There are frequent incremental releases, so it's not always possible to give a final ETA.

**Comment by VincentGuigui** [comment]
It's fixed on the repo and deployed

Thanks

**Comment by VincentGuigui** [comment]
I either tested it incorrectly yesterday or there is a regression on production (at least on https://westeurope.api.cognitive.microsoft.com/luis/v2.0/apps)

SimpleConsole is fine

The input 18/08/78 is returning XXXX-08-18 instead of 1978/08/18
```
 {
      "entity": "18/08",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 4,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-08-18",
            "type": "date",
            "value": "2017-08-18"
          },
          {
            "timex": "XXXX-08-18",
            "type": "date",
            "value": "2018-08-18"
          }
        ]
      }
    },
```

**Comment by VincentGuigui** [comment]
it seems to be fixed on eu.luis.ai.

Thanks

However: literal date like 11 aout 62 is returning a daterange... I am creating a new issue for that
