### ISSUE TITLE
[FR DateTimeV2] Handling space as date separator

### ISSUE THREAD

**Issue by VincentGuigui** [microsoft/Recognizers-Text#547]
Usually when spelling a Date orally, people are saying "18 08 78" or "18 08 1978" for august 18th, 1978.

Currently none of this format is recognized as date:

02 04 2009 => no date is found, it should return 2009-04-02
2 4 2009 => no date is found, it should return 2009-04-02
18 08 1978 => no date is found, it should return 1978-08-18
18 8 1978 => no date is found, it should return 1978-08-18
18 08 78 => no date is found, it should return 1978-08-18
18 8 78 => no date is found, it should return 1978-08-18

**Comment by tellarin** [comment]
@VincentGuigui, for this one we'll need further analysis. It may not be possible to cover it at the recognizers level without causing side effects in other types (number, phone number, etc.).
I'll update the issue here soon.
