### ISSUE TITLE
[FR DateTimeV2] Handling ordinal for 1st of the month

### ISSUE THREAD

**Issue by VincentGuigui** [Microsoft/Recognizers-Text#548]
Using ordinal for the 1st of the month is not recognized in query like "1er avril 2005" or "1er avril 78"

1er avril 2005 => date should return 2005-04-01 and not **timex:XXXX-00-00 / value:0000-02-01**
The current result is:
```
    {
      "entity": "1er avril 2005",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 13,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-00-00",
            "type": "date",
            "value": "0002-01-01"
          }
        ]
      }
```

1er avril 78 => date should return 1978-04-01 and not  **timex:XXXX-00-00 / value:0000-02-01** (warning there is also a [2-digits year issue](https://github.com/Microsoft/Recognizers-Text/issues/546))
```
  {
      "entity": "1er avril",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 8,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-00-00",
            "type": "date",
            "value": "0002-01-01"
          }
        ]
      }
    }
```

**Comment by tellarin** [comment]
@VincentGuigui, can you check that this has been fixed in the repo? This will be included in the next release (unfortunately not along with the other issue you reported, which was already in the release train).
Feel free to re-open if some case still fails.

**Comment by VincentGuigui** [comment]
It's fixed on the repo. Not deployed yet

Thanks

**Comment by VincentGuigui** [comment]
it's live on eu.Luis.ai

Thanks
