### ISSUE TITLE
[Infra] Bugs in JavaScript lookbehind implementation

### ISSUE THREAD

**Issue by STayinloves** [Microsoft/Recognizers-Text#549]
The implementation of TypeScript/JavaScript's lookbehind can't deal with some complex regexes.

Here is an example:

The regex for common number `(((?<!\d+\s*)-\s*)|(?<=\b))\d+(?!(\.\d+[a-zA-Z]))(?=\b)` extracts "123" and "123" and "0000" from utterance "123 00 and 123 and 0000" in JS which discards "00".

PR #539 #535 #487 #427 also have test cases being marked as not supported in JavaScript because of this issue.

**Comment by tellarin** [comment]
Fixed in #1069.
