### ISSUE TITLE
[EN DateTimeV2] Date dot separator not recognized

### ISSUE THREAD

**Issue by SvartAlfe** [Microsoft/Recognizers-Text#554]
If I enter "13/05/2018" or "13-05-2018", LUIS recognized it successfully as a DateTimeV2.
But if I enter "13.05.2018", then only "2018" is used :

Utterance   13.05.2018
Entities   datetimeV2 --> "2018"

I am working essentially with this date format : "DD.MM.YYYY". It would be great to support also english regional formats, not only "en-us".

**Comment by tellarin** [comment]
Hi @SvartAlfe,  

dot-syntax dates like "13.05.2018" are already supported. You can test it with the SimpleConsole project in the repository.

The latest recognizers release is in the process of being deployed to LUIS.

Regarding regional formats in English, multiple formats are supported, but in ambiguous cases, the default fallback is MDY. We plan to enable setting the default fallback, but there is no ETA yet. This is tracked in issue #212.

**Comment by SvartAlfe** [comment]
I tested it in a very simple application, please see the results below. The "." and "-" are not managed the same way. (I am working on **eu.luis.ai**)

![16-05-_2018_09-23-31](https://user-images.githubusercontent.com/35220922/40102702-7f3ae4d8-58eb-11e8-864e-c995645c691a.png)


![16-05-_2018_09-26-11](https://user-images.githubusercontent.com/35220922/40102708-8260a134-58eb-11e8-8240-a1a8bee57a6f.png)
