### ISSUE TITLE
[ES DateTimeV2] The entity "la semana pasada" not being detected 

### ISSUE THREAD

**Issue by fanidamj** [microsoft/Recognizers-Text#556]
The entity "la semana pasada" not being detected whereas the entity "esta semana" is recognized.

![spanishdatetimev2](https://user-images.githubusercontent.com/16520557/40131526-03e40e78-58ef-11e8-99fe-61cecae0e578.PNG)

**Comment by Grey0202** [comment]
PR #1818 fix most of the cases in this issue except for "inicio de mes". That will be fixed in coming PR with other improvements.

**Comment by tellarin** [comment]
Marking this as solved. Cases like "inicio de mes" --> start of month will be moved to a new issue.
