### ISSUE TITLE
[CN Number] Incorrect number extraction cases

### ISSUE THREAD

**Issue by linzijia07** [microsoft/Recognizers-Text#568]
"在下面的价格中选一个，$20，300美圆, ￥300, ok?"

It should be three numbers, i.e., "20", "300" and "300", while the recognizer gives me "20，300" and "300". Note that "，" in "20，300" is a Chinese comma.

**Comment by tellarin** [comment]
On triage, issue was marked as *very low priority* as it's an ambiguous corner case.
