### ISSUE TITLE
[CN NumberRange] Wrongly parse an extracted range

### ISSUE THREAD

**Issue by linzijia07** [microsoft/Recognizers-Text#584]
"找出销售额低于15且高于20的记录"
 The recognizer would extract "低于15且高于20" but parse it into (15, 20), which is wrong. The correct result is an empty range.

**Comment by STayinloves** [comment]
This incorrect behavior also exists in English when coming across invalid number range like "lower than 20 and higher than 30".

```json
{
  "Text": "lower than 20 and higher than 30",
  "Start": 0,
  "End": 31,
  "TypeName": "numberrange",
  "Resolution": {
    "value": "(20,30)"
  }
}
```

**Comment by tellarin** [comment]
This should be two ranges. This way consumers of the output can reason about it.
Empty range would loose information.

**Comment by guom08** [comment]
If we already extract this as a range, fix the resolution to empty range "()"

**Comment by LionbridgeCSII** [comment]
@tellarin, this issue appears to be solved already. 
Both Chinese and English examples return 2 ranges.

**Comment by tellarin** [comment]
Closing based on your feedback, @LionbridgeCSII. Thanks!
