### ISSUE TITLE
[EN DatetimeV2] Fix compound duration timex

### ISSUE THREAD

**Issue by guom08** [Microsoft/Recognizers-Text#639]
Cases like "PT1HT30M" should be "PT1H30M"
Example sentence: "The accidents last for 1 hour and 30 minutes"

**Comment by tellarin** [comment]
When address this, we should make sure DataTypes.TimexExpression can parse all timex expressions in specs.

**Comment by tellarin** [comment]
@guom08, hasn't this been fixed recently?
Next time, please add example input sentences that cause the issue in the description, to make it easier to test if it was fixed or not.
Thanks.

**Comment by sebastianzolg** [comment]
**Can we re-open?** 

I think this is not working as expected. Quickly wrote a test for my case and resolution returned 0 value. 

```
        [TestMethod]
        public void DataTypes_Resolver_Duration_1hour30minutes()
        {
            var resolution = TimexResolver.Resolve(new[] { "PT1H30M" });
            Assert.AreEqual(1, resolution.Values.Count);

            Assert.AreEqual("PT1H30M", resolution.Values[0].Timex);
            Assert.AreEqual("duration", resolution.Values[0].Type);
            Assert.AreEqual("5400", resolution.Values[0].Value);
            Assert.IsNull(resolution.Values[0].Start);
            Assert.IsNull(resolution.Values[0].End);
        }
```
