### ISSUE TITLE
C# test runners skip some specs properties

### ISSUE THREAD

**Issue by enzocanoo** [Microsoft/Recognizers-Text#659]
From [`public void TestDateTimeAlt()`](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs#L118-L119) in `TestBase.cs`

```C#
...
Assert.AreEqual(expected.TypeName, actual.TypeName, GetMessage(TestSpec));
Assert.AreEqual(expected.Text, actual.Text, GetMessage(TestSpec));
...
```

If the spec tested have `Start` or `End` properties, that properties are not being tested. For example, the `End` property does not match in some specs from `DateTimeModelCalendarMode`, `DateTimeModelExtendedTypes`, and `DateTimeModelComplexCalendar`.

![image](https://user-images.githubusercontent.com/12394167/41868599-e91663ee-788c-11e8-9e48-2a4c195caf6b.png)

**Comment by tellarin** [comment]
All specs were re-processed and the test code should now be checking those properties.
Thanks for reporting it!
