### ISSUE TITLE
[CN NumberRange] Cannot extract "100–200之间" in "找出100–200之间同时不包括 150的销售记录"

### ISSUE THREAD

**Issue by linzijia07** [Microsoft/Recognizers-Text#674]
"找出100–200之间同时不包括 150的销售记录"

Only "100–200" is extracted and parsed into [100,200), while the groundtruth should be "100–200之间" as (100,200)

**Comment by aanandr** [comment]
I dont understand the issue? Which area is this in? I think this is incorrectly assigned to me.

**Comment by tellarin** [comment]
@aanandr it seems it was a mistake. Please disregard it. @Sothan is responsible for the issue.

**Comment by Sothan** [comment]
"100–200之间" is the same as "between 100 and 200", and we parse them into [100, 200), so there is nothing to do in this issue.

**Comment by tellarin** [comment]
@linzijia07 and @guom08, can you confirm this works as intended?

**Comment by tellarin** [comment]
Confirmed to work now. Closing the issue.
