### ISSUE TITLE
LUIS prebuilt entity datetimeV2 cannot underestand "am" or "pm" properly

### ISSUE THREAD

**Issue by YutongTie-MSFT** [Microsoft/Recognizers-Text#690]
This is a issue from the prebuilt entity datetimeV2. If user sends sentence like "from today pm to tomorrow am". LUIS will only take "today" and "tomorrow am" as entities. However, if user sends "from today afternoon to tomorrow morning" LUIS will take the entities correctly as "today afternoon" and " tomorrow morning". The only difference between these two sentence is using a abbreviate form of the time. Is there any improvement on this or other solutions?

I have tried everything related to 'today', 'tomorrow', 'am', 'pm', just 'today pm' & 'tomorrow am' pair does not work, please see the pic.
![luis 1](https://user-images.githubusercontent.com/38084098/42239775-dbf6155a-7eb9-11e8-9588-2154ab51e317.PNG)

Thanks,
Yutong

**Comment by tellarin** [comment]
Using "am" and "pm" to represent morning and afternoon is not formally correct, but there is indeed a bug where behaviour should be consistent. We'll prioritize a fix in the next release.

**Comment by tellarin** [comment]
Fix is in. It will be in the release pipeline shortly.
