### ISSUE TITLE
Test specs and testing in general

### ISSUE THREAD

**Issue by jimongit** [Microsoft/Recognizers-Text#707]
Test specs and testing in general hyperlinked to https://blog.botframework.com/2018/02/01/contributing-luis-microsoft-recognizers-text-part-3/ is not working.

**Comment by tellarin** [comment]
@jimongit,it seems the link you shared is incorrect. The correct link is https://blog.botframework.com/2018/02/12/contributing-luis-microsoft-recognizers-text-part-3/

Where did you see the link you shared? Also, in the correct link all specs/URLs seem correct. Can you give more details about what you meant?

I'll close this issue for now, but please reply on it and we can re-open as needed.
