### ISSUE TITLE
[JP Number] Japanese Patterns Bugs in YAML Files

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/Recognizers-Text#708]
While developing the Java Numbers Recognizers for Japanese culture, we found several issues we could track down to the YAML files. This is affecting all platforms implementing Japanese Numbers (including C#)

In the C# implementation of the Japanese Numbers Definitions, we can see some "references" didn't get properly resolved (this should be performed within the Microsoft.Recognizers.Definitions\Japanese\NumbersDefinitions.tt T4 code)
![image](https://user-images.githubusercontent.com/805847/42533840-4da6e298-848b-11e8-9a1f-e34c53a489d8.png)

The root cause of this issues can be found in the [\Patterns\Japanese\Japanese-Numbers.yaml](https://github.com/Microsoft/Recognizers-Text/blob/master/Patterns/Japanese/Japanese-Numbers.yaml) file. We've found three types of errors, all of then related to "nestedRegex" types:
1. Missing elements that are referenced in a nestedRegex element.
2. Referenced keys not listed in the "references" element.
3. Typos in defining references (like a missing closing curly bracket char)

![image](https://user-images.githubusercontent.com/805847/42533949-9eec97d8-848b-11e8-800e-4409539d8b61.png)

However, they have no effect in the C# version of the Recognizers and all tests pass without issues. On the other hand, in more strict implementations of Regular Expressions like Java's Pattern class, this result in an exception:
![image](https://user-images.githubusercontent.com/805847/42533977-b762f690-848b-11e8-8473-0978f118a50c.png)

Moreover, trying to fix these issues in the YAML file and regenerating the Japanese Numeric Resources result in several broken unit tests:

**Comment by JuanAr** [comment]
@tellarin there was only one typo left. I fixed it, regenerated the definitions class and ran all tests. Fix in #729

**Comment by tellarin** [comment]
Thanks, @JuanAr. Merged in now.
