### ISSUE TITLE
[EN Choice] "disagree, it is not ok" interpreted as "true"

### ISSUE THREAD

**Issue by adamg777** [Microsoft/Recognizers-Text#737]
for input:

"disagree, it is not ok"

The Boolean model (ChoiceRecognizer - GetBooleanModel) returns a value of "true".

here is the returned object:

[{"Text":"ok","Start":20,"End":21,"TypeName":"boolean","Resolution":{"otherResults":[],"score":0.52,"value":true}}]

Tested with v1.0.9 (.NET)

**Comment by adamg777** [comment]
"not ok"

also returns a value of "true" :

[{"Text":"ok","Start":4,"End":5,"TypeName":"boolean","Resolution":{"otherResults":[],"score":0.7,"value":true}}]

**Comment by tellarin** [comment]
@enzocanoo/@pconstantini, could you guys take a look at this?

**Comment by enzocanoo** [comment]
@tellarin, issue fixed with #768

**Comment by tellarin** [comment]
Unfortunately it's not feasible to have an overly general solution. The goal of the current Boolean model is to cover basic replies only.
