### ISSUE TITLE
[CJK Number] Incorrect expected value in Korean, Japanese but test are passed

### ISSUE THREAD

**Issue by hongman** [Microsoft/Recognizers-Text#756]
CJK Use BaseCJKNumberParser instead of BaseNumberParser.

In BaseCJKNumberParser, 'GetIntValue' Method calculates Number's value. 

As in the examples below, you can see that the test does not pass(modifying Expected value).

1) there is no indication of RoundNumber between RoundNumbers input values.
(in CJK 105 caculated 100 + 5, so no indication of '十' or '십'(10) ) 
Chienese : 一百五 -> 105, in test Specs : 150 (line 1402 at Chinese/NumberModel.json)
Japanese : 二百五 -> 205, in test Specs : 250(line 658 at Japanese/NumberModel.json)
Korean : 일백육 -> 106, in test Specs : 160(line 240 at Korean/NumberModel.json)
![image](https://user-images.githubusercontent.com/8444994/43473899-4f77b5dc-952c-11e8-89eb-f61965411ba4.png)
![image](https://user-images.githubusercontent.com/8444994/43473935-674cd480-952c-11e8-89f1-78b06b65ddb3.png)
![image](https://user-images.githubusercontent.com/8444994/43473958-7251ab1c-952c-11e8-8238-2c4ff1512bea.png)

2) when there is no Integer indicating the size for each RoundNumber.
(in CJK 1515 caculated 1000 + 100x5 + 10 + 5, but no indication of '10', so code use previous digit(5), and actual result is 1000 + 100x5 + 10x5 + 5 = 1555)
Chienese : 一千五百十五 -> Expected : 1515, actual : 1555
Japanese : 一千五百十五 -> Expected : 1515, actual  : 1555
Korean : 일천오백십오 -> Expected : 1515, actual : 1555
![image](https://user-images.githubusercontent.com/8444994/43473707-df078282-952b-11e8-84bd-878af1565164.png)
![image](https://user-images.githubusercontent.com/8444994/43473723-e7f32888-952b-11e8-886b-75b02f0dc42b.png)
![image](https://user-images.githubusercontent.com/8444994/43473765-fdaf785c-952b-11e8-9ecc-f362b8357f02.png)

If the value is modified correctly, the CJK Number test will not pass. 

Collaboration with CJK seems necessary.

**Comment by AniChikage** [comment]
@hongman 

1. I notice that you modified the value,
        in Chinese, change from "150" to "105" for "一百五",
        in Japanese, change from "250" to "205" for "二百五",
        however, the original values are correct. If "일백육" means "106" in Korean, you may need to modify 
    the code to support that.

2. I didn't find the "一千五百十五" in Chinese and Japanese, is that new test case?

**Comment by hongman** [comment]
Thank you for your apply @AniChikage 

First of all, I did not know that "一百五" really means 150. 
If you read "一百五" in Korean, it is "일(一)백(百)오(五)", because it really means 105.

In this case, as you said, in the GetIntValue method(BaseCJKNumberParser.cs), I would have to add another condition for Korean

**Comment by Jaeuk-YOO** [comment]
In japanese also 250 is 二百五十. Actually japanese does not omit the letter 十 to represent 10. It is the same way as korean.

**Comment by AniChikage** [comment]
@hongman @Jaeuk-YOO Thanks for your reply.

1. If "二百五" is the same in Japanese and Korean, you may add a condition for, which could work for 
    both Korean and Japanese.

2. Welcome for more test cases.
    I don't think "一千五百十五" is a valid expression in Chinese. It's "一千五百零十五", "一千五百零一十 
    五" or "一千五百一十五" for "1515". We don't omit "零" and "一".

**Comment by hongman** [comment]
Okay.. I will add a condition for Japanese and Korean to BaseCJKNumberParser at GetIntValue. thank you.
