### ISSUE TITLE
[* Sequence] Add support for Dutch PhoneNumber format

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/Recognizers-Text#778]
At the moment the PhoneNumberModel doesn't support all variants which are used in the Netherlands yet. Should the emergency telephone number also be included? 112 in Europe, 911 in US.

PR with test specs: [coming soon] 

**Full list**
- 0AA-BBBBBBB
- 0AAA-BBBBBB
- 06-CBBBBBBB
- 0AAA-BBBB
- 0AAA-BBBBBBB

(The trunk prefix '0' is dropped when prefixed by the country code +31 or 0031)
- +31 AA BBBBBBBB
- _etc._

**Out of scope**
- 14 0AA
- 14 0AAA
- 112

The number can contain dashes (-) and the area code + trunk prefix is sometimes enclosed in parentheses.

**Reference:**
> Since 10 October 1995 (Operation Decibel) all telephone numbers in the Netherlands are 10 digits long (including the trunk prefix '0'). The area code ('A') is commonly separated with a dash ('-') and sometimes a space from the subscriber's number ('B'). Alternatively, the area code (including the trunk prefix) can be enclosed in parentheses.
> 
> The length of the area code for landlines is either 2 or 3 digits, depending on the population density of the area. This leaves 7 or 6 digits for the subscriber's number, resulting in a format of either 0AA-BBBBBBB or 0AAA-BBBBBB. Cellphone numbers are assigned the 1-digit area code 6, leaving 8 digits for the subscriber's number: 06-CBBBBBBB, where subscriber's number ('C') is neither 6 nor 7. Service numbers (area codes 800, 900, 906 and 909) have either 4 or 7 remaining digits, making them 8 or 11 digits in total: 0AAA-BBBB or 0AAA-BBBBBBB. The area code 14 has no trunk prefix and is used for government numbers, currently only for municipalities. The remaining digits represent the area code of the municipality. Therefore, the length 14 numbers total either 5 of 6 digits: 14 0AA or 14 0AAA
> 
> The trunk prefix '0' is dropped when prefixed by the country code: +31 AA BBBBBBBB, +31 6 CBBBBBBB, etcetera. Note that there is not a trunk prefix for the 14 series so the international number becomes +31 14 0AAA.
> 

_[Source: Wikipedia](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers#Netherlands)_

**Comment by tellarin** [comment]
Emergency numbers and the 14-class short numbers are out of scope for the recognizers.
