### ISSUE TITLE
[CN|DE|FR Choice] Boolean missing support for German, Chinese and French

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#796]
The ChoiceRecognizer RecognizeBoolean needs support for German, Chinese and French.
The priority is implementation in .NET and JavaScript.

**Comment by tellarin** [comment]
@matthewshim-ms, could you help with French?

**Comment by tellarin** [comment]
@johnataylor PR #812 merged in French support and I've added the missing German pieces. It would benefit from more tests, but I'll close this issue as done for now. :)
