### ISSUE TITLE
[EN Dimension] 500 MB / mB / mb isn't recognized correctly

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/Recognizers-Text#800]
While working on Dutch NumberWithUnits and creating more tests, I found out that Megabyte / Megabit isn't recognised correctly in all cultures. (and it doesn't have tests in English specs).

```json
{
  "Text": "500 mB",
  "Start": 0,
  "End": 5,
  "TypeName": "dimension",
  "Resolution": {
    "value": null
  }
}
```

```json
{
  "Text": "500 kB",
  "Start": 0,
  "End": 5,
  "TypeName": "dimension",
  "Resolution": {
    "unit": "Kilobit",
    "value": "500"
  }
}
```

**Comment by iMicknl** [comment]
@tellarin @STayinloves could this maybe be reopened? I just checked it and Megabit is indeed working now, however Megabyte isn't recognized.

Input: 500 mB, output should be 500 Megabyte according to the defined Pattern


```json
{
  "Text": "500 mB",
  "Start": 0,
  "End": 5,
  "TypeName": "dimension",
  "Resolution": {
    "unit": "Megabit",
    "value": "500"
  }
}
```

``` Megabyte: -megabyte|-megabytes|megabyte|mB|megabytes|mega byte|mega bytes|MByte```

Also, the symbol for [Megabyte](https://en.wikipedia.org/wiki/Megabyte) is MB and not mB. Should I do a PR to change this or is this something that could be fixed while fixing this issue?

**Comment by tellarin** [comment]
@iMicknl thanks for the catch. Should be covered now.
