### ISSUE TITLE
[FR Number] French numbers not recognized properly

### ISSUE THREAD

**Issue by jesus-seijas-sp** [Microsoft/Recognizers-Text#807]
**Describe the bug**
French numbers are not recognized properly. 
One example: "quatre-vingt -quinze" should be recognized as 95, because in the french system 80 is "quatre-vingt" and "quatre-vingt-quinze" is 80+15 = 95.

Other examples:
"quatre-vingt-dix-neuf" is recognized as 98 instead of 99
"quatre-vingt-dix neuf" is recognized as 43 instead of 99
"quatre vingt dix neuf" is recognized as 4 20 19 instead of 99.

Also, the specs seems to be modified to don't find this error. Example: in the Age specs there is this test in english: "Now, after ninety five years of age, perspectives change.". In all languages this is translated so always is 95, except in french, where the spec is modified to be 35:
https://github.com/Microsoft/Recognizers-Text/blob/master/Specs/NumberWithUnit/French/AgeModel.json

This error is also reproduced at LUIS.ai.

**To Reproduce**
```javascript
const Recognizers = require('@microsoft/recognizers-text-suite');

const text = 'neuf mille neuf cent quatre-vingt-dix neuf';

const result = Recognizers.recognizeAge(text, 'fr-FR');
console.log(JSON.stringify(result, null, 2));
```
This show in console:
```
[
  {
    "start": 0,
    "end": 41,
    "resolution": {
      "value": "9943"
    },
    "text": "neuf mille neuf cent quatre-vingt-dix neuf",
    "typeName": "number"
  }
]
[
  {
    "start": 31,
    "end": 40,
    "resolution": {
      "value": "15",
      "unit": "Ans"
    },
    "text": "quinze ans",
    "typeName": "age"
  }
]
```

**Expected behavior**
It's expected that french numbers are identified. The previous code example should return:
```
[
  {
    "start": 0,
    "end": 41,
    "resolution": {
      "value": "9943"
    },
    "text": "neuf mille neuf cent quatre-vingt-dix neuf",
    "typeName": "number"
  }
]
[
  {
    "start": 18,
    "end": 40,
    "resolution": {
      "value": "95",
      "unit": "Ans"
    },
    "text": "quatre vingt quinze ans",
    "typeName": "age"
  }
]
```

**Sample input/output**
N/A

**Platform (please complete the following information):**
 - Platform: [JavaScript]
 - Environment: [npm package, LUIS]
 - Version of package [e.g. v1.0.1]

**Additional context**
N/A

**Comment by tellarin** [comment]
Thanks for reporting this! PR #808 should address this and the new packages will enter the release pipeline soon.
