### ISSUE TITLE
Wrong label for Riyal saudi in french

### ISSUE THREAD

**Issue by jesus-seijas-sp** [Microsoft/Recognizers-Text#831]
**Describe the bug**

The label of the "Riyal Saudi" is written "Riayl saudi" for french at different parts of the code:

https://github.com/Microsoft/Recognizers-Text/blob/02bd15fd07cc6696b8b7c7e03d7f6e81eb22448d/Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/resources/french_numeric_with_unit.py#L113

https://github.com/Microsoft/Recognizers-Text/blob/02bd15fd07cc6696b8b7c7e03d7f6e81eb22448d/Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/resources/FrenchNumericWithUnit.java#L127

https://github.com/Microsoft/Recognizers-Text/blob/02bd15fd07cc6696b8b7c7e03d7f6e81eb22448d/JavaScript/packages/recognizers-number-with-unit/src/resources/frenchNumericWithUnit.ts#L13

https://github.com/Microsoft/Recognizers-Text/blob/02bd15fd07cc6696b8b7c7e03d7f6e81eb22448d/.NET/Microsoft.Recognizers.Definitions/French/NumbersWithUnitDefinitions.cs#L129

https://github.com/Microsoft/Recognizers-Text/blob/4b1ca7d44f89c2b75e9c7ce40dabf3a058a1898e/Patterns/French/French-NumbersWithUnit.yaml#L178

**Comment by tellarin** [comment]
Thanks for catching it! Issue was due to a type on the YAML file. 
I'm closing this issue as there is already an approved PR that solves it.
