### ISSUE TITLE
[CN Datetime2] Wrongly recognize cases like "2007年和2012年" as a daterange

### ISSUE THREAD

**Issue by guom08** [Microsoft/Recognizers-Text#856]
**Describe the bug**
Cases like "2007年和2012年" should be recognized as two separate years: "2007年", “2012年”
While the current output is a daterange, which means "from 2017 to 2012"

**To Reproduce**
福特在2005年之前、2007年和2012年的销量分别是多少？
This is recognized as "2005年之前"，"2007年和2012年”. The latter one is recognized wrongly as "from 2017 to 2012"

**Expected behavior**
福特在2005年之前、2007年和2012年的销量分别是多少？
This should be recognized as "2005年之前", "2007年", "2012年"

**Comment by tellarin** [comment]
Javascript pending.

**Comment by tellarin** [comment]
I'll close this as Javascript support will need a wider refactoring and will be included in a new issue.
