### ISSUE TITLE
Recognizers functions undefined in version 1.1.1

### ISSUE THREAD

**Issue by jesus-seijas-sp** [Microsoft/Recognizers-Text#869]
**Describe the bug**

At version 1.0.1 this code worked:

```javascript
const Recognizers = require('@microsoft/recognizers-text-suite');
const result = Recognizers.recognizeNumber("Twelve", Recognizers.Culture.English);
console.log(result);
```

At version 1.1.1 same code does not works because Recognizers.recognizeNumber is undefined.

Inspecting the object we see this:
![image](https://user-images.githubusercontent.com/15154218/45741765-b7848900-bbf8-11e8-863f-e59eb94e8e3b.png)

It seems that only recognizeDateTime function is defined.

**To Reproduce**

Execute this script:

```javascript
const Recognizers = require('@microsoft/recognizers-text-suite');
const result = Recognizers.recognizeNumber("Twelve", Recognizers.Culture.English);
console.log(result);
```

**Expected behavior**
Function is expected to be defined.

**Platform (please complete the following information):**
 - Platform: Node
 - Environment: npm package
 - Version of package v1.1.1

**Comment by tellarin** [comment]
@jesus-seijas-sp Thanks for reporting. We're aware of the issue and a fix will be out soon.

**Comment by tellarin** [comment]
@stevengum has just confirmed it works! :)
Thanks, folks!
