### ISSUE TITLE
[* DatetimeV2] The parsing results for "from March to May", "3月和5月之间" is not correct

### ISSUE THREAD

**Issue by guom08** [Microsoft/Recognizers-Text#875]
**Describe the bug**
For English version
"From March to May" can be parsed, but the timex for PastResolution is wrong.
For Chinese version
"3月和5月之间" can't be parsed for now

**Expected behavior**
The expected resolution should be like
"Resolution": {
      "values": [
        {
          "timex": "(2018-03-01,2018-05-01,P2M)",
          "type": "daterange",
          "start": "2018-03-01",
          "end": "2018-05-01"
        },
        {
          "timex": "(2019-03-01,2019-05-01,P2M)",
          "type": "daterange",
          "start": "2019-03-01",
          "end": "2019-05-01"
        }
      ]
    }

**Comment by tellarin** [comment]
I'll close this as Javascript support will need a wider refactoring and will be included in a new issue.
