### ISSUE TITLE
[Infra] .NET recognizers are influenced by region settings in Visual Studio

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/Recognizers-Text#885]
**Describe the bug**
Many tests for different models and languages are failing on my development machine (local). It appears that my local region settings influence the outcome of the Recognizers, which resolves in failing tests. My output is most of the time with a comma, instead of dot notation.

**To Reproduce**
1. Start -> `Region & Language settings`
2. Related Settings ->`Additional date, time and regional settings`
3. Region -> `Change date, time or number formats`
4. Format -> Change to `Dutch`
5. Run all tests in Visual Studio

**Expected behavior**
Local settings should not influence Recognizers since they are targeted on a specific culture already

**Sample input/output**
Just two examples of the failing testcases:

```
Message: Assert.AreEqual failed. Expected:<10.05>. Actual:<10,05>. Input: "10日元5日本銭"
```

```
Message: Assert.AreEqual failed. Expected:<0.8>. Actual:<0,8>. Input: "My phone number is (21) 996205563."
```

**Platform (please complete the following information):**
 - Platform: .NET
 - Environment: Visual Studio Community Edition
 - Version of package: latest

**Comment by tellarin** [comment]
To be handled together with #774.
