### ISSUE TITLE
[FR DateTimeV2] Regular expression causes node to crash

### ISSUE THREAD

**Issue by jesus-seijas-sp** [microsoft/Recognizers-Text#897]
**Describe the bug**
One regular expression causes an out of memory when extracting french dates, using windows 7/10. 
The behaviour is random, but can be reproduced using it from node VM, Jest or just running from debug using Visual Studio Code.
The regular expression causing the heap error is the attached one.
[regexp.txt](https://github.com/Microsoft/Recognizers-Text/files/2434713/regexp.txt)

**To Reproduce**
Try to extract date time in node from any kind of utterance (I reproduced using "où sont mes clés").

**Expected behavior**
Date time correctly extracted.

**Sample input/output**
N/A

**Platform (please complete the following information):**
 - Platform: JavaScript
 - Environment: npm package, node 10.5.0, windows 7/10 [testing with Jest, executing in VM or debugging with Visual Studio Code]
 - Version of package: 1.1.3

**Comment by tellarin** [comment]
Closing this as I can't replicate in the current code. NPM packages for v1.2.0 will be out soon.
