### ISSUE TITLE
[Infra] Any plans to support Python version<3.6?

### ISSUE THREAD

**Issue by combacsa** [Microsoft/Recognizers-Text#916]
**Is your feature request related to a problem? Please describe.**

Default python 3 version on Ubuntu 16.04 LTS is still below 3.6, which makes me not so easy to use Recognizers-Text on that environment with OS default setting.

**Describe the solution you'd like**

I'm wondering if there could be any plans on supporting version<3.6. Latest 3.5.x would be appreciated.

**Describe alternatives you've considered**

At least mentioning about python version requirements on README.

**Comment by tellarin** [comment]
Hi @combacsa, unfortunately currently we don't have plans for it.
Would you be able to help contribute support?

**Comment by tellarin** [comment]
I'll close this issue for now, as it's not currently planned.
Thanks.
