### ISSUE TITLE
List of issues to fix per language

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/Recognizers-Text#920]
**Is your feature request related to a problem? Please describe.**
The README says:

> Contributions are greatly welcome! Both for fixes and extensions in the currently supported languages and for expansion to new ones. Especially for Japanese, Italian, Korean, and Dutch.

However, for new contributors it is unclear what parts exactly are lacking or should be improved for those languages.

I do see a lot of issues in the Issues section, tagged with [EN] for example. But I do not see any bug or task for e.g. Dutch, while that is listed as "especially needing fixes and extensions".

I see that there are unit tests with language-specific parts, but not all languages have the same tests. For newcomers it is not immediately clear whether the goal is to implement all those tests first.

**Describe the solution you'd like**
A task list or a project in the [Projects section](https://github.com/Microsoft/Recognizers-Text/projects) with tasks showing the issues or lacking parts per language

**Comment by tellarin** [comment]
Hi @hansmbakker, 

thanks for the feedback.

I've edited the Contributing sub-section in the main README to give some examples of starting points. It also has links to some tutorials on the project structure. Hope it helps.

**Comment by tellarin** [comment]
Hi @hansmbakker, 

thanks for the feedback.

I've edited the Contributing sub-section in the main README to give some examples of starting points. It also has links to some tutorials on the project structure. 

Hope it helps.

I also like your suggestion of having more detailed tracking under /Projects. We'll try to do that in the future.

@iMicknl, would you like to do that for Dutch?

**Comment by tellarin** [comment]
Hi @hansmbakker, 

thanks for the feedback.

I've edited the Contributing sub-section in the main README to give some examples of starting points. It also has links to some tutorials on the project structure. 

Hope it helps.

I also like your suggestion of having more detailed tracking under /Projects. We'll try to do that in the future.

@iMicknl, would you like to do that for Dutch?

**Comment by iMicknl** [comment]
@tellarin @hansmbakker good idea! I have an (internal) planner board for the Dutch implementation at the moment (sorted at priority), but I was planning to bring that to issues soon. I will add it to the 'projects' section soon.

Should we do a planner board per language?

**Comment by tellarin** [comment]
GitHub is having issues the whole day today and issues and comments appear and disappear often.
For now, let's create a board for Dutch/.NET as a try out. What do you think, @iMicknl?

**Comment by iMicknl** [comment]
@hansmbakker @tellarin I updated the project board with all open issues for Dutch. Not sure yet if we should keep them as notes or if I should convert them to (high level) issues. Having issues will make it easier to track + discuss in the end, since you can't link to a note.

https://github.com/Microsoft/Recognizers-Text/projects/3
