### ISSUE TITLE
[Infra] Installation problem - python - using Installation from PyPI

### ISSUE THREAD

**Issue by NoaKel** [Microsoft/Recognizers-Text#938]
when importing the files:
`from recognizers_number import NumberRecognizer
` 

File "/home/..../site-packages/recognizers_number/number/models.py", line 35
    self.parser: Parser = parser
               ^
SyntaxError: invalid syntax

`from recognizers_date_time import DateTimeRecognizer 
`
  File "/home/..../site-packages/recognizers_text/culture.py", line 2
    English: str = 'en-us'
           ^
SyntaxError: invalid syntax

**Comment by tellarin** [comment]
Hi @NoaKel, 
we found out that someone was name-squatting the recognizers package names on PyPI and we're working with the admins there to remove those.
When our packages are officially published, we'll update the main GitHub README to point to the correct packages, ok?
Thanks for reporting the issue!

**Comment by TechExceed** [comment]
Hi @tellarin,
Do you have any estimate about when the Python's recognizers package should be published?
Thanks!
