### ISSUE TITLE
[Open Question] Where is GeographyV2 library for python?    

### ISSUE THREAD

**Issue by Mary268** [Microsoft/Recognizers-Text#941]
I am a customer of LUIS, and there are many prescription about the prebuilt entities in LUIS on the Microsoft documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-geographyv2.  However, some of them are not available or not released. I am wondering that when others entities library (e.g. GeographyV2) for python will publish on https://github.com/Microsoft/Recognizers-Text/tree/master/Python/libraries ?

**Comment by tellarin** [comment]
Hi @Mary268,
while LUIS leverages Recognizers-Text for their base-type prebuilt entities, not all of their entities come from this project. GeographyV2 and Person use completely different pipelines from the recognizers here.
As such, they are not part of the project and won't be released through here.
Unfortunately, we're also not aware of any plans to release those outside of LUIS.
