### ISSUE TITLE
[TimexExpression] JavaScript implementation of TIMEX expression does not expose value resolution

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/Recognizers-Text#974]
Package: microsoft/recognizers-text-data-types-timex-expression
Version: 1.1.3

The JavaScript implementation of the TIMEX expression manipulation includes a function that allows you to recreate the result from LUIS or the Recognizer given the distinct TIMEX array.

The function exists in the implementation but is not exposed in the package. It should be exposed by the package which means included in the exports in the package root index.js file.

Note this is not as useful as the evaluate of TIMEX expressions against constraints expressed as TIMEX expression but it is still useful as an aid to understanding and debugging.

**Comment by dividor** [comment]
Probably stating the obvious, but just to please note, the [sample for timex resolution](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/40.timex-resolution/resolution.js) doesn't work because of this issue.

**Comment by PathTech** [comment]
We are experiencing this issue also.

**Comment by johnataylor** [comment]
add entry in index.js

**Comment by marawanshalaby** [comment]
Hello, could you please update the version in npm? The current version there is 1.1.4, which has been published over a year ago and doesn't include the valueResolver export https://www.npmjs.com/package/@microsoft/recognizers-text-data-types-timex-expression
